### ISSUE TITLE
＜

### ISSUE THREAD

**Issue by laraok** [programthink/zhao#10]

**Comment by posclegom** [comment]
只要不是违反GitHub的ToS的内容都可以放在GitHub上，楼主不要做精赵，不要自我阉割，不要做奴才。

**Comment by posclegom** [comment]
你也配姓赵？

**Comment by vczhan** [comment]
看来以后可能要翻墙访问了。话说UP主看过[Connected China](http://china.fathom.info/)吗？可以做成数据可视化网页版

**Comment by XL2014** [comment]
来来来,觉得违反ToS就到 https://github.com/contact 这里举报
看官方怎么回应你

**Comment by posclegom** [comment]
愚弟狂顶xiaolan兄！！！

**Comment by laraok** [comment]
OK ，多谢，我以侵犯个人隐私的条款，举报了。

**Comment by zjuguxi** [comment]
呵呵，举报婊还真是哪都有。不过政治人物属于公众人物，其家属情况不算个人隐私。

**Comment by yeahwu** [comment]
@laraok 哈哈，这位仁兄还算磊落，举报了，还不忘招呼一声。
其实github丢包已经很严重了，不翻墙体验很差。封，也是迟早的事。
要么多学学翻墙姿势，要么举报去，其它的也不要瞎bb了。

**Comment by towry** [comment]
妹的，感觉上面几位跟文革里面的人差不多。有人想不翻墙用这个网站，人家不想封，和举报有什么关系？和条款有什么关系？乱扣帽子。你们这些和某些人真的没啥区别，只是这样显得更低贱点。

感觉微博上的那群傻逼都过来了

**Comment by vincentha766** [comment]
github不是你家开的，共享啥东西人有自由。
后面封了，那也是你党的不对，那墙在道义上就输了。君不见你党从没承认过墙的存在？
想玩git，叫大陆复制一个类似网站就行，大家上去玩，又稳定又和谐。到时候看看有多少人能忍住不翻墙？

**Comment by vincentha766** [comment]
因为怕党封github，而替党做事，还以侵犯隐私为由做这事，那骨气这让我服了。

**Comment by wbsdty331** [comment]
最高人民法院的司法解释规定
对未经他人同意，擅自公布他人的隐私材料或以书面、口头形式宣扬他人的隐私，致使他人的名誉受到损害的，按照侵害他人名誉权处理。

**Comment by programthink** [comment]
@laraok 
你还真是个奇葩 :)
你估计没仔细看项目首页的说明吧？
俺这里汇总的权贵家族资料，信息来源主要是：维基百科、国际权威媒体、天朝政府官网、百度百科

如果要说泄露个人隐私，那也是这些 网站先泄漏。
你滴明白？

**Comment by programthink** [comment]
@vincentha766 
所以俺称之为“奇葩”。
你说的这类人，学术上称之为“斯德哥尔摩综合症”
以下是俺前几年写的博文：
[《天朝民众的心理分析：斯德哥尔摩综合症》](url 天朝民众的心理分析：斯德哥尔摩综合症)

**Comment by programthink** [comment]
@XL2014 
多谢老熟人捧场 :)

**Comment by programthink** [comment]
@zjuguxi 
同意你所说——政治人物属于公众人物，其家属情况不算个人隐私

退一步讲，
俺这些资料都是从公开的大型网站上收集的，有些网站就是天朝喉舌（比如：新华网）。
某些奇葩想要举报俺侵犯个人隐私，那应该先去举报天朝政府的网站啊 :)

**Comment by programthink** [comment]
@vczhan 
你提到的 “Connected China”，俺前几年看过。
俺也想做一个 web 版本，可以更直观地体现权贵家族的关系。
如果你对 web 开发有心得，欢迎提建议

**Comment by posclegom** [comment]
狂顶编程兄！！！

**Comment by venj** [comment]
“就好比强盗拿刀杀人，围观者不但没有谴责强盗，反而去谴责卖刀的店家” 

GFW的情况是强盗拿到刀威胁着围观者，你这个店家在墙外围观。不知道你这比方是怎么打出来的。

**Comment by breaking-gfw** [comment]
这可不是纯技术网站。
https://government.github.com/community/

**Comment by venj** [comment]
@breaking-gfw  你的名字叫的挺大气，不过理解能力似乎有点问题。有政府机构和国家级研究机构在用github就说明github不是纯技术网站了？呵呵。

**Comment by breaking-gfw** [comment]
@venj 那你看过吗

**Comment by breaking-gfw** [comment]
@venj Government agencies at the national, state, and local level use GitHub to share and collaborate. If you don't see your organization on this list, follow the instructions below to add it!

**Comment by breaking-gfw** [comment]
不管下面放的你有没有全部看过，单看标题你觉得呢？谁的理解能力有问题？

**Comment by breaking-gfw** [comment]
@venj https://github.com/government/welcome

**Comment by breaking-gfw** [comment]
@venj https://github.com/CommerceGov/Policies-and-Guidance

**Comment by breaking-gfw** [comment]
@venj GitHub is a third-party website that offers code repositories that developers can use to collaborate on software development projects in real-time. Many users also use GitHub to publish and track documents, such as style guides and policies.

**Comment by itisbenjamin** [comment]
我覺得還是牆了吧...反正這對我沒什麼影響，倒是能把這群人弄到牆裡別出來...牆裡不是有gitcafe什麼的嗎....照樣可以玩兒啊...

**Comment by wangxf91** [comment]
呵呵，无非想表现得特立独行，耍帅而已，楼上有些别还真以为楼主是什么热血青年，其实么中二病，告诉大家“你们这些国内的渣渣，没言论自由，看我多屌”，楼主你要真是牛就不要躲在国外（在国外？），到国内来搞这些东西，然后四处宣扬看看

**Comment by CMB-news** [comment]
這裡向各位用戶稟報一下：推翻中共、顛覆中共偽政權是所有中國人義不容辭的責任！新一代技術人員，特別是計算機軟件人員更應該作爲先鋒存在，而不是一個頭腦麻木的豬狗般的奴才苟且活在世上。這與中共暴政是否封殺一個站點毫無關係。淪陷區的人民有權要求解放！如果只是表達異議，那沒有什麽關係，但是，對於那些阻礙革命的人、迫害民主人士的人、包括而不限於中共充當奴犬的程序員、向中共偽政權當局通風報信、與共匪合作的技術人員，在以後的革命風暴中將被視之為敵人，將會被清除消滅！

**Comment by gmail12** [comment]
顶 编程随想^_^因为编程随想伟大，

**Comment by antipoliongithub** [comment]
@CMB-news 解释一下啥叫伪政权？我等码农不知道什么是政治，也不愿谈政治，既不是共产主义先锋也不原做你等民逗的颠覆现政权的先锋。别把那么大的帽子扣在技术人员头上。我等现在生活安康，如果你们一定要搞的大家都不自在，我等虽是屁民，维护自己生存权益的本能还是犹存的。

顺便说一下，你现在的口气跟几十年前的GCD的口气好接近啊，是想在造一个GCD么？
