### ISSUE TITLE
对于部分信息不详的赵家人怎么收录?

### ISSUE THREAD

**Issue by XL2014** [programthink/zhao#11]
RT
赵家百科的很多词条可以做自动同步到这里....不过有些人信息实在是不详
比如性别/出生年月不详,只有姓名和照片怎么办?(一些小赵家人)...
sex 必填。填写性别。用 M/F 代表 男/女
birth 必填。填写出生时间，用【4位数年份】表示。未知年份用 N/A 表示。

是不收录了还是有什么好的建议么?

===========

题外话1：太监言论别在issues里BB,自己去 https://github.com/contact 举报.
题外话2：安利下赵家百科免翻墙镜像 https://github.com/XL2014/wikizhao/wiki 求被太监举报

**Comment by posclegom** [comment]
愚弟狂顶xiaolan兄！！！尤其是题外话1！！！

**Comment by yangzhaofeng** [comment]
對於小趙家人，我覺得如果沒有利用自己的身份地位來做一些權貴通常做的事情，是否可以“網開一面”不收錄？

**Comment by wbsdty331** [comment]
智商堪忧
把这里的「赵家人」 换成 「美国主子」，依然成立

**Comment by posclegom** [comment]
「赵家人」vs「美国主子」，选择你的阵营吧！

**Comment by wbsdty331** [comment]
@posclegom 我选择死亡

**Comment by posclegom** [comment]
@wbsdty331 我尊重你的选择！

**Comment by programthink** [comment]
@XL2014 
对于权贵家族中知名度比较低的人，主要看此人是否在“党/政/军”界混得很好。
如果混得很好，有非常大的概率说明此人是利用了权贵家族向上爬的。

关于“必填项”
其实俺在 yaml 文件中的规定，并不算严格：
常用名至少得有吧？
性别至少得有吧？
然后就是简介得有吧？
其它都可以不填，或者像 birth 可以填 N/A 表示未知

**Comment by programthink** [comment]
@XL2014 
关于“自动同步”的问题
俺定义目录结构的时候，给每一个 person 留了一个目录
目前每人的目录下存放的是一个简介的 yaml 文件和一个头像的 png 文件
还可以继续扩充，比如增加一个 wiki 文件或 html 文件，用来放更详细的描述。
照片的话，除了头像，还可以扩充，放其它照片。
比如江蛤蟆有很多搞笑的照片，都可以收集了放上来

**Comment by posclegom** [comment]
狂顶编程兄！！！
