### ISSUE TITLE
这跟斯德哥尔摩综合症有什么关系？

### ISSUE THREAD

**Issue by sxcooler** [programthink/zhao#114]
现在所有的翻墙方式GFW都有办法应对，只是想封不想封而已。你在一个技术网站上放政治敏感内容，真影响到github在墙内的访问，你考虑没考虑过别人的感受？
有本事肉身回国推墙，躲在国外给别人工作生活添麻烦算什么英雄？
你就是柴玲那种“流血别人去，我不去”（CNN采访，大意）的“民主人士”吧？

**Comment by SinGeno** [comment]
在github上放“政治敏感内容”？
请问什么是政治敏感内容，GitHub有定义这个变量吗？GitHub会因为你所谓的政治敏感内容阻止你访问吗？
谁不让你访问GitHub你找谁啊，拉不出屎，怪地球没引力吗？

**Comment by sxcooler** [comment]
@SinGeno 第一，请问这和斯德哥尔摩综合症有什么关系？斯德哥尔摩综合症是什么你知道么？
第二，还是那句话，有本事你去肉身推墙，没这个本事光会嘴炮有什么用？
第三，做什么事都要尊重现实，实事求是，现实就是中国是这么个环境，而广大开发者也确实有这个需求，你给别人添麻烦还恬不知耻，你这种人就是自私。有那么多网站可以放这些东西，为什么一定要在github？
第四，你要真是肉身翻墙了，那墙内的事和你有什么关系呢你这么积极？你要没翻，你这么搞，不怕坑自己么？

**Comment by SinGeno** [comment]
抱歉，2月19日刚到美国。您还放嘴炮不？

**Comment by sxcooler** [comment]
@SinGeno 我觉得你看不懂中文……

**Comment by SinGeno** [comment]
有那么多网站不封，为啥封GitHub？Facebook也封了，Twitter也封了，你丫咋不叫唤？谁自私？

**Comment by sxcooler** [comment]
@SinGeno 麻烦你先认真看一下我的话再回复吧，我说的是推墙。
还有我一直没有人身攻击，你丫才叫唤，你全家都叫唤。

**Comment by SinGeno** [comment]
你在墙内，谁让你用墙外的东西了？是不是你自己要用的？没人逼你吧？那凭什么你要逼别人停止项目？

**Comment by SinGeno** [comment]
你的嘴不是长肉身上的？你的指头不是长肉身上的？你的脑子不是和肉身连着的？我用嘴，指头，大脑推墙，不行？
那你的意思肉身推墙怎么推？你脑子里面的墙还是八达岭的那堵墙吧？

**Comment by SinGeno** [comment]
斯德哥尔摩综合征（英语：Stockholm syndrome；瑞典语：Stockholmssyndromet）又称为人质情结、人质综合征，是一种心理学现象，是指犯罪的被害者对于加害者产生情感、同情加害者，认同加害者的某些观点和想法，甚至反过来帮助加害者的一种情结[1]。这些情感被认为是不理性的、滥用同理心[2] 斯德哥尔摩综合征可以被看作是一种创伤羁绊，不一定只发生在人质身上，只要加害者对被害者实施骚扰，都可能使被害者对加害者产生强烈的情感[3] 。根据弗洛伊德的理论 ，斯德哥尔摩综合征是一种自我防卫机制，当受害者相信加害者的想法时，他们会觉得自己不再受到威胁[4]。斯德哥尔摩综合征并非正式精神疾病名词[5]。

@sxcooler 谁让你不能访问GitHub的？谁绑架了你，让你不能访问GitHub的？你能分清不？

**Comment by soulofc** [comment]
Richard Sun，


github是你开的？你有什么资格管别人在上面放什么东西？被GFW墙了不去抗争，却来这里嚎，对于你这种逻辑混乱的脑残，我只想说：你叫你ma个bi，不喜欢就滚出github啊



在 2017-02-24 12:17:13，"Richard Sun" <notifications@github.com> 写道：


@SinGeno 麻烦你先认真看一下我的话再回复吧，我说的是推墙。
还有我一直没有人身攻击，你丫才叫唤，你全家都叫唤。

**Comment by sxcooler** [comment]
@SinGeno 我很理解你肉身翻墙的喜悦，但是真的没必要这么着急来怼墙内的人。不是因为你出去了我们就成了敌人了。
关于斯德哥尔摩综合症，你自己也贴了，你从我哪句话看出我同情或者理解中共当局了？对不对。

**Comment by soulofc** [comment]
@sxcooler 我就是墙内的人，我没有觉得SinGeno 在“怼墙内的人“，相反我很支持SinGeno，请你不要代表我。你这种动辄代表别人的作风很中共哦
我曾经开的帖子里有五毛特别喜欢用”怼“， 你很像那个人的小号

**Comment by sxcooler** [comment]
@soulofc 不知道从小你妈是怎么教育你的，我只是质疑下repo主关于“斯德哥尔摩综合症”的说法，你这满嘴喷粪是干什么？
另外，你怎么知道我没有抗争？你为推墙做了什么贡献？
我没有代表谁，我只是告诉他我很理解他的心情罢了。
整个issue我也只是想说，照顾一下暂时还没肉身翻墙的人的感受。
咱们都是友军，没必要这么激烈的互相攻击，你这种零和博弈的心态才是标准的墙内心态。
这个issue我关了吧。

**Comment by soulofc** [comment]
你妈教育得好，教出了个5毛

在 2017-02-24 13:35:12，"Richard Sun" <notifications@github.com> 写道：


@soulofc 不知道从小你妈是怎么教育你的，我只是质疑下repo主关于“斯德哥尔摩综合症”的说法，你这满嘴喷粪是干什么？
另外，你怎么知道我没有抗争？你为推墙做了什么贡献？
我没有代表谁，我只是告诉他我很理解他的心情罢了。
整个issue我也只是想说，照顾一下暂时还没肉身翻墙的人的感受。
咱们都是友军，没必要这么激烈的互相攻击，你这种零和博弈的心态才是标准的墙内心态。
这个issue我关了吧。

**Comment by sxcooler** [comment]
@soulofc 孩子，你这种动不动就给人贴标签的行为是十分幼稚的，你对我了解多少就认为我是个“5毛”？这个世界上不是只有非黑即白，不是考试只有正确答案和错误答案。
你这个阶段我也经历过，真的，你过几年回头看，你会理解的。

**Comment by gaohahabili** [comment]
幼稚的我特地注册个账号来骂你😂

爱用用 不用滚

嗯……就这样……

**Comment by soulofc** [comment]
你这条装逼装深沉的5毛，哥作为一个长者，有必要跟你传授一些人生经验，那就是多动脑子。


在 2017-02-24 13:41:43，"Richard Sun" <notifications@github.com> 写道：


@soulofc 孩子，你这种动不动就给人贴标签的行为是十分幼稚的，你对我了解多少就认为我是个“5毛”？这个世界上不是只有非黑即白，不是考试只有正确答案和错误答案。
你这个阶段我也经历过，真的，你过几年回头看，你会理解的。
