### ISSUE TITLE
这种东西愿意在哪发在哪发，别来GitHub发。刻意的曲解，抹黑中国，真是够了。

### ISSUE THREAD

**Issue by mc275** [programthink/zhao#135]

**Comment by FkCommunism** [comment]
楼上，什么是国？政府就是国吗？党就是国吗？
反共就是抹黑中国？
爱国就要去爱党吗？

**Comment by mc275** [comment]
不评论内容，第一句就说了，爱去哪发去哪发，来github干嘛，全世界都没别的地方了，来技术社区发这些，无能！！！还有，我来告诉你什么是国，良好的治安，保障的生活，共同的文化认同感和归属感，这就是国家。你不认同，你就走，国家是有共同归属感的社会群体的集合。你没归属感，不说离开找你自己的归属感，缺跳出来说哪些有归属感的人们不好，这个群体有问题，不是抹黑和曲解是什么。 发自网易邮箱手机版 在2017年11月27日 18:46，Rao 写道： 楼上，什么是国？政府就是国吗？党就是国吗？ 反共就是抹黑中国？ 爱国就要去爱党吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by huiyifyj** [comment]
@mc275  同意，Github是技术类不是政治论坛。
而且这种曲解国家是真的sb，有点邪教的感觉，真的是无脑黑，也许国家是有不对，但绝没有这么夸张。

**Comment by flashflexpro** [comment]
北京最近的暴力驱赶“低端人口”，youtube上有视频，还什么治安？！每个民企都强制建立党支部，这是啥文化？谁抹黑谁？谁归属谁？

**Comment by panjiangyi** [comment]
楼主是低端人口，建议自觉离开中国。

**Comment by jacobcyl** [comment]
看了一下评论，啼笑皆非，或许有人说我是5毛，但如果一定要站边的话，我想我是站在客观的中立的角度的。如果是一定要分个阵营，我不得不给自己封个自干五的称号。

我想问下各位，口口声声说什么罪行，什么黑暗，不用说那么多了，这些谁不知道，那个朝代那个国家不是这样？所以才会有改朝换代，但是我想问下，历史的河流中，是否出现过改朝换代后就能实现你们那些所谓的乌托邦了？

我就想问下，如果是你把天下打下来了，你会给你的小弟什么福利？给那些跟着你打天下的兄弟什么好处？--梦想？别痴人说梦了？天下熙熙皆为利来，天下攘攘皆为利往。你等今日看似为了普天老百姓争自由，实则为了自己的利益。古人早已道破天机，历朝历代，那些跟着打天下的小弟你以为他们真的为了追随一个君王？他们只是为了升官发财，除非圣人当权。但是圣人是不屑于当权的。

说到罪恶，我想到了“感恩节”。当年欧洲人登录美洲，当地的土著印第安人热情的接待了他们，教他们打猎。额你们崇尚的欧洲人，高等人种，最后他们从印第安人手中夺取了土地，杀害了曾经接济他们的印第安人，剥了他们的皮，看了他们的头，还对杀的多的军人给予奖励。你去推翻这个黑暗的政府吧。

再说说欧洲贩卖黑奴的事。欧洲今天的发达，早期是建立在掠夺、殖民的基础上，有了本钱，才激发了科技的发展，才有资本推动工业革命，才有今天的辉煌，那辉煌正是你等今日无比崇拜的辉煌。可是背后，沾染了多少人的血。你去推翻欧洲吧。

你可以推翻你所在的朝代建立新的朝代，但是你能做到没有黑历史？或许你会说不要在意这些细节，推翻了再说，好啊，那你那什么来团结人民来站在你这边？人民要的是什么？印度的民主？全民医疗（在澳洲叫个救护车试试）？ 这真叫人为难。好希望你能在现在的基础上实现我们这些屁民的愿望：读书不要钱，老板随便骂，看病不要钱，每周工作4天，不要加班，有房子有车子，没有小偷，不必喝酒应酬，不必为了子女的交易费心，人人有工作... 听起来觉得还不错，你能吗？

要是不能，还是好好工作，该干嘛干嘛，多做点对身边的百姓有意义的事情吧，再不行扛起枪走上街，不要伤到老百姓就好 ，要不然当你恐怖分子。

**Comment by archdevil0** [comment]
楼主你的习猪头主席准备在2020年把你全家消灭，女性可以留下来做肉便器，不知道你怎么看

**Comment by huangzonghao** [comment]
楼主还是先专心学术吧。。。快30了还没有硕士毕业。。。。我都替你不好意思了 。。。。

**Comment by Wicky07** [comment]
发这个怎么抹黑了，他们的血缘/亲戚关系，难道不是事实？

**Comment by flashflexpro** [comment]
真事儿！怎么能叫“曲解，抹黑”？！


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ba460** [comment]
太多人喜欢被些分裂国家的反动分子带节奏，还以为自己看透一切。TM自己生活都处理不好，还一天天做个 键盘侠，给台独分子啥的免费做推广，用着中文 、打着中文字 还要称中国是贵国（敢问你TM是哪儿的），我不知道这种SB 怎么就这么多，传销窝点就缺你们这种没大脑的

**Comment by flashflexpro** [comment]
贵国指的就是站着茅坑不拉屎的，五毛就是 茅坑 里面爬的。

2018-03-02 12:05 GMT-05:00 tickchen <notifications@github.com>:

**Comment by ba460** [comment]
@flashflexpro 你又是哪里来的野鸡，中国的是需要你这这里带节奏，滚去用你father语，别用中文了好吗，看着很恶心。 你觉得 世界其他地方不是坑，你赶紧去舔、好干净的。，为何非要来github带这种无聊的节奏，你自己去建个站宣传行不。

**Comment by flashflexpro** [comment]
哈哈，没有外面带着玩，中国现在还得和北朝鲜一样，像你这样不干净，看来是爬不出来了。

2018-03-02 21:01 GMT-05:00 tickchen <notifications@github.com>:

**Comment by soulofc** [comment]
你以为你是中国人么，你只是中国奴隶而已

在 2018-03-03 01:05:16，"tickchen" <notifications@github.com> 写道：


太多人喜欢被些分裂国家的反动分子带节奏，还以为自己看透一切。TM自己生活都处理不好，还一天天做个 键盘侠，给台独分子啥的免费做推广，用着中文 、打着中文字 还要称中国是贵国（敢问你TM是哪儿的），我不知道这种SB 怎么就这么多，传销窝点就缺你们这种没大脑的

**Comment by flashflexpro** [comment]
抬举它了，太监而已。

2018-03-04 8:19 GMT-05:00 soulofc <notifications@github.com>:

**Comment by zzy1996** [comment]
事实就是事实，什么叫曲解抹黑？真是奴性深入骨髓，为你主子的独裁登基操碎了心。中国就你这种奴才太多了，永远成不了民主宪政的现代文明国家。

**Comment by Dawingwan** [comment]
习国人爱来来，不来可以走，这是言论自由的地方。 慢走不送

**Comment by kimchi-shi** [comment]
大家都想荫蔽家族，后代，但是不代表合法，有这种家族图的出现，只能说人民英雄纪念碑代表的那些烈士的血都白流了。
其次，我们就是应该在github这种地方发，越是能够给国内的程序员制造障碍，才越能激化他们和TG的矛盾。
只有国内的矛盾激化到一定程度了，才可能团结国内的同志，才可能有所改变。

**Comment by ZhouHoubin** [comment]
一群键盘侠，除了BB还是BB

**Comment by soulofc** [comment]
，你是什么呢，键盘跪舔？键盘跪族

在 2018-03-23 14:46:16，Z-HB <notifications@github.com> 写道：


一群键盘侠，除了BB还是BB

**Comment by flashflexpro** [comment]
对付这群自干五和监狱服刑人员，主要是打击它们的主人，巧妙揭露 让它们不敢传播的 敏感信息，比如两会的那个气质姐的背景～～～

**Comment by flashflexpro** [comment]
最好在代码里面嵌入，比如巴拿马姐夫之类的，绝不违法，但是绝对有效。

**Comment by 00Zhang** [comment]
mc275 你只是一条赵家的狗。

**Comment by fasthing** [comment]
@flashflexpro 哎哟会写代码好连不起哦 ，我们都看不懂的啦，全世界只有皿煮国家的人会写代码哦，可以 很强，服！

**Comment by fasthing** [comment]
@soulofc 那你又是什么，美日的狗？是不是说你是狗还抬举你了？恐怕你连绿蛆都不如？ 能不能搞个头像？不知道的以为你才是水军小号呢 2333......

**Comment by fasthing** [comment]
@flashflexpro 除非你没爹妈，否则操你妈，就这么简单！ 来啊 傻逼

**Comment by sjshaj** [comment]
哪里曲解？指出来
既然是曲解，我希望你把这些东西实名发到墙内，让大家看看随想的嘴脸

**Comment by fansangg** [comment]
github已经。。那么低龄化了吗

**Comment by fengluoye** [comment]
@fansangg 好多都是职业的。翻墙之前都是各种觉得中国不好，翻了之后，发现国外也那样，没有完美的体制，能做的只能是健全体制。
我能做的也还是那样，赚钱养家。。。毕竟我发言没人给钱。。。

**Comment by wonderay** [comment]
挺无脑的还感觉自己特正义

**Comment by Seedarchangel** [comment]
@fengluoye 
git和github, 傻傻分不清楚
翻个墙就能知道国外啥样，和老外以为中国没有茶叶蛋没有什么区别

**Comment by sjshaj** [comment]
看到五毛在这洗地，我就想笑，你再怎么洗，还能改变这份资料的真实性？

**Comment by sjshaj** [comment]
别出来丢中国人的脸，五毛

**Comment by razertory** [comment]
You can you up, no can no BB

**Comment by jieekie** [comment]
被墙的不正常了，还用抹黑？多看看、多听听、多想想

**Comment by KwinsWang** [comment]
> 北京最近的暴力驱赶“低端人口”，youtube上有视频，还什么治安？！每个民企都强制建立党支部，这是啥文化？谁抹黑谁？谁归属谁？

嗯。。。经过判断，你不过就是个脑残，估计被台独洗脑洗多了。
我就来教教你，让你以后死也死得明白点，不然你这样的人跑到了国外，都丢了中国的脸。

youtube上的那个强制拆迁一大批（看似穷人区）百姓的住房的视频，你这傻逼只要找一找，就很快能在youtube上找到答案：

因为哪个地区在过去，本来就是一大片危房（危房指房龄太旧，已经有部分或者整个坍塌的危险），让后很多外省或外地的背井离乡的穷人家，在当地找工作收入太低或者没找到，就聚集在那个区域，经过了很长时间，那个区域就出现了像美国一样的穷人区。
过去政府在这方面没有去管理，但中国已经高度发展，要顾及百姓的生命安全，如果因为危楼倒塌，那当官的就会被百姓谴责然后下台。所以才会大力整顿这样的一个区域。在那里的都是楼龄过了安全期的，并且那些人都是因为非当地人，不适当地的户籍，不能在那个破烂楼房里居住，再住下去，哪天楼房坍塌压死人，那才是中国的不人道。
所以，拜托你这傻逼傻冒，以后看视频找点完整版去看，不要去找国内的纪录片的“部分”去看。说你脑残，然而你却是个开发人员，你这智商也不至于被戏弄到这样的地步，但你说的话已经是个弱智儿童的表现。多看看健康的时频，这段驱赶平民的视频是台独分子截取了部分国内发布的视频，然后加点文字，就把你们这群脑残台湾人给引导到屎坑里了。
