### ISSUE TITLE
会不会成为国外间谍的获取信息的通道？

### ISSUE THREAD

**Issue by flyhero** [programthink/zhao#137]
请注意点。

**Comment by archdevil0** [comment]
外国间谍获取信息不会直接去中南海吗？
再说你只是一头家豚，没必要提你的主子担心。

**Comment by MARESFAC** [comment]
没别的就想笑，太特么好笑了，间谍们真要把你国颠覆了，上github也不用挂代理加速了，不用挂代理上谷歌了，可以享受真实的网速了：）

**Comment by flashflexpro** [comment]
西朝鲜正向北朝鲜靠拢，最后也是，不准带拍照，不准擅自离队，不准～～～～～～

**Comment by cvmax** [comment]
赵家人的事情，轮得到你操心？你算个什么东西？
