### ISSUE TITLE
这些所谓家族图有什么的，普通民众况且吃穿不愁了，这些有权势的家族难道你还要指望混成不如普通人吗？

### ISSUE THREAD

**Issue by zhangjh** [programthink/zhao#147]
看了下整理的这些家族图，对于开放领导层家族关系信息让普通大众了解还是有益的。

但如果说因为他们有权力有关系混到这个位置上就是“有罪”的那就不一定了。

即使是普通人，你家里亲戚你还想着照顾点的，何况这些大领导子女们。

说白了，换谁在那个位子上都是差不多的，开国元老们抛头颅洒热血的革命斗争，大家不都想过个好日子，都想荫蔽下自己家族，后代？

虽然对天朝现在的政治现状有所不满，但看不惯国外敌对势力的恶意抹黑。什么大纪元，法轮功，健身教练之流，简直是丧心病狂的抹黑，可以理解，毕竟“杀父夺妻”血海深仇

**Comment by kimchi-shi** [comment]
大家都想荫蔽家族，后代，但是不代表合法，有这种家族图的出现，只能说人民英雄纪念碑代表的那些烈士的血都白流了。

**Comment by kehao95** [comment]
如果你拿不定主意，记录事实就行了，自由后世来评判。

**Comment by xiaomuzhu** [comment]
当初的建国理念和后来的发展可真是背道而驰....够恶心的了
