### ISSUE TITLE
关于反对这个项目放在Github上的

### ISSUE THREAD

**Issue by towry** [programthink/zhao#15]
大家可以尽管反对，想举报的可以举报，虽然没用。

那些反对这些反对的，你们可以尽管反对，但是不要无凭无据乱扣帽子，这样很傻，跟“某些人”没什么区别。

----

请别乱给我扣帽子，谢谢。

**Comment by towry** [comment]
我的博客在Github上，虽然没什么访问量，里面的内容很烂，但是我不想在给别人看或者放在我简历里面让别人看的时候别人访问不了。

所以我不想Github被封，我也不会去举报这个项目，我支持这个项目放到Github以外的地方，比如bitbucket，那里也可以协作呀。

这是我的观点，谢谢。

---

请别乱给我扣帽子，谢谢。

**Comment by TheLoneliness** [comment]
谁都不想GitHub被封，就像当初不想Google被封一样，理解你的观点，但是GitHub使用自由也由不得您了

**Comment by posclegom** [comment]
不想给楼主扣帽子，但是还是要告诉楼主只要不是违反GitHub的ToS的内容都可以放在GitHub上，楼主不要做精赵，不要自我阉割，不要做奴才。

**Comment by programthink** [comment]
@towry 
如果你是担心 GitHub 上的简历，俺来帮你分析一下。
首先，
把简历放在 GitHub 上的，通常都是程序员。
其次，
你的简历的目标读者，应该用人单位里面懂技术的人。
而且此人还要审核简历，通常技术主管之类的职务。
因此，
如果审核简历的这个人，居然不懂翻墙，从而看不到你的简历。
这说明啥捏？说明这个公司的水平也不怎么样。你就算去不了这个公司，其实也没啥损失。

当然啦，
或许你放在 GitHub 上的简历还有其它用途，不在俺上述分析的范围之内。你可以补充。
俺可以继续你参谋一下。
没准有其它的解决之道，不受 GFW 封杀 GitHub 的影响。

**Comment by posclegom** [comment]
狂顶编程兄！！！
