### ISSUE TITLE
请项目负责人不要把github当做百度贴吧使用

### ISSUE THREAD

**Issue by captainCoconut** [programthink/zhao#172]
这儿就是个代码托管网站……该发天涯的发天涯，该发贴吧的发贴吧，别什么乱七八糟的都往这儿放

**Comment by soulofc** [comment]
github都没意见，你逼逼撒？滚回墙内看新闻联播吧，那里面某个胖子天天都上头条，很合你这种人的胃口

在 2018-06-12 14:41:07，"captainCoconut" <notifications@github.com> 写道：


这儿就是个代码托管网站……该发天涯的发天涯，该发贴吧的发贴吧，别什么乱七八糟的都往这儿放

**Comment by 73883999** [comment]
那么楼主你来干嘛？

**Comment by da-shen-anonym** [comment]
总有人把自己个人的失败归咎给政府，殊不知政府的功能和作用是什么，殊不知美国也有Roosevelt's new deal，政策与PRC并无差别。
总有人把自己的不努力归咎于天朝应试教育，填鸭教育，殊不知《Harvard inequality》在美国已经延绵几十年的抗议，底特律的nigger不知道什么叫做上学，这就是所谓的素质教育。

总有人只知道九四事件，却从未参与过当时中国，殊不知包括吾尔开希在内的民运人士早已陈清事实真相，侯建德则称完全没看到有坦克碾压。**而到现在仍然坚持反党的柴玲最早撤退，竟说自己目睹了一切**，此人大学期间四次堕胎，博主愿意相信这样的人，却不相信侯建德，吾尔开希，北京的工人市民。天安门聚集了九万人，博主为什么就听柴玲一人？喝着美国的可口可乐，香港的桔子汁，坐在人民群众的土地上，流着中国人的血液，叫喊着CIA递给他们稿子。

几十吨重的坦克，几百匹马力的发动机，钢铁履带碾压在地面的震动，广场上的广播就没有停过，提前撤离的柴玲竟口口声声说自己的同学在熟睡中被碾死。

如果博主只愿意相信外国人，为什么不相信朝鲜、巴基斯坦、古巴、罗马尼亚、捷克斯洛伐克和東德等國？如果博主只相信资本主义，为何不相信在长安街住着的卡洛斯·加洛？

总有人只知道中国禁止言论自由，华盛顿邮报，华尔街日报完全被驴象二党的党报。只知道美国可以辱骂总统，不知道稍微提及一点财团的关系就被民主。


也罢，毕竟像你这样的人，生活不好找点理由还不行么

**Comment by da-shen-anonym** [comment]
开放社会的叙利亚，多民族融合的南非，自由网络环境的津巴布韦，这些都是博主向往的国家，为什么不移民？你在中国一穷二白，但孩子还可以通过高考，成为中产，去了美国，抱歉，考哈佛不需要分数，不过可能博主在美国呆到地球爆炸都不会有校友。
你如果喜欢挖中国的黑料，去看大纪元，看法轮功好了，天天有报道，wiki不都写得很清楚么，自焚是假的，李大师是一个普通的宗教徒，去学习吧 
http://gb.falundafa.org/chigb/flg.htm

不要写这些没有意义的东西了，学会了博主可以用意念推翻政府，何必每天这么累`

**Comment by soulofc** [comment]
按楼主的逻辑，只要大家不去抗争，安安静静的做牛做马，就没人被杀死了， 不怪凶手却怪学生去抗争了，怪坚持抗争的人，这逻辑，这洗地。那是否抗日战争也不用打了呀？大屠杀什么的，怪就怪当时中国要抵抗。

在 2018-07-08 05:13:39，"da-shen-anonym" <notifications@github.com> 写道：


总有人把自己个人的失败归咎给政府，殊不知政府的功能和作用是什么，殊不知美国也有Roosevelt's new deal，政策与PRC并无差别。
总有人把自己的不努力归咎于天朝应试教育，填鸭教育，殊不知《Harvard inequality》在美国已经延绵几十年的抗议，底特律的nigger不知道什么叫做上学，这就是所谓的素质教育。

总有人只知道九四事件，却从未参与过当时中国，殊不知包括吾尔开希在内的民运人士早已陈清事实真相，侯建德则称完全没看到有坦克碾压。而到现在仍然坚持反党的柴玲最早撤退，竟说自己目睹了一切，此人大学期间四次堕胎，博主愿意相信这样的人，却不相信侯建德，吾尔开希，北京的工人市民。天安门聚集了九万人，博主为什么就听柴玲一人？喝着美国的可口可乐，香港的桔子汁，坐在人民群众的土地上，流着中国人的血液，叫喊着CIA递给他们稿子。

几十吨重的坦克，几百匹马力的发动机，钢铁履带碾压在地面的震动，广场上的广播就没有停过，提前撤离的柴玲竟口口声声说自己的同学在熟睡中被碾死。

如果博主只愿意相信外国人，为什么不相信朝鲜、巴基斯坦、古巴、罗马尼亚、捷克斯洛伐克和東德等國家的表态？如果博主只相信资本主义，为何不相信在长安街住着的卡洛斯·加洛？

总有人只知道中国禁止言论自由，华盛顿邮报，华尔街日报完全被驴象二党的党报。只知道美国可以辱骂总统，不知道稍微提及一点财团的关系就被民主。

也罢，毕竟像你这样的人，生活不好找点理由还不行么

**Comment by soulofc** [comment]
啧啧，全世界200多个国家，只盯着最差的几个，楼主的表演令人作呕。

在 2018-07-08 05:29:01，"da-shen-anonym" <notifications@github.com> 写道：


开放社会的叙利亚，多民族融合的南非，自由网络环境的津巴布韦，这些都是博主向往的国家，为什么不移民？你在中国一穷二白，但孩子还可以通过高考，成为中产，去了美国，抱歉，一辈子二等公民。
你如果喜欢挖中国的黑料，去看大纪元，看法轮功好了，天天有报道，wiki不都写得很清楚么，自焚是假的，李大师是一个普通的宗教徒，去学习吧 http://gb.falundafa.org/chigb/flg.htm

**Comment by shijian123** [comment]
github是一个技术分享平台，别把乱七八糟的东西都往这上面写！

**Comment by soulofc** [comment]
GitHub网站都没意见你逼逼啥，滚吧

在 2018-07-13 14:02:18，"时间shiwo" <notifications@github.com> 写道：


github是一个技术分享平台，别把乱七八糟的东西都往这上面写！

**Comment by shijian123** [comment]
github举报 
1、进入用户主页选择
2、选择Block or report user

**Comment by captainCoconut** [comment]
我不是在反对你们抗议政府，我是在反对你们在github上抗议政府。
都是程序员，楼上诸位的逻辑怎么这么令人捉急

**Comment by captainCoconut** [comment]
一个技术网站，怎么整这么多乱七八糟的，还能雄赳赳气昂昂地来diss我，我真是服了你们……你们来github干啥的？
问题关了

**Comment by soulofc** [comment]
快给你的共产党爸爸也报告去吧，五毛🐶

在 2018-07-16 11:23:38，"时间shiwo" <notifications@github.com> 写道：


github举报
1、进入用户主页选择
2、选择Block or report user

**Comment by Sonic853** [comment]
请楼主只把github当代码托管网站用就好。
如果你反对github中的这些“乱七八糟的东西”，那就请你不要过多干涉“乱七八糟的东西”，屏蔽就好。
