### ISSUE TITLE
我相信换你治国国家一定会崩塌的更快

### ISSUE THREAD

**Issue by xgz123** [programthink/zhao#176]
老实说咱门中国的体制虽然有问题，但事实证明国家的制度并没有成为社会发展的障碍，而是随着社会发展而不断改变、进步的。相反，看所谓的西方民主国家，效率低下，难民、恐怖主义横行，到底是哪种更先进呢？

**Comment by posclegom** [comment]
国民党时代的人如果也像你那么想该多好呢，不就没有后来滴折腾了嘛！

**Comment by xgz123** [comment]
国民党时代军阀割据，国家名义上统一实则四分五裂，怎么能和今天比呢？
一个小小的台湾都治理不好，台湾乱象，完全是由于国民党的无能。
几十万日杂就能搞垮台湾，你想想中国大陆要面对的多少比日杂更复杂、更强大的势力，其难度不在一个等级。
我认为现在的中国是纵观几千年历史，最好的时代。首先古代和现代是没法比的，就不多说了。横向来看，中国是当今世界上和平、稳定的大国。

说实在的，我们中国几千来的政治经验，真的不是外国人用一点理想主义就能当老师的。
自由、民主，喊几句就万事大吉、成真了？事实证明这些都是政治工具而已。

制度不符合生产力，就会被推翻，这是真理，不是谁能左右的。
长不长久，还看发展自我的能力，这是马克思主义的基本观点。

**Comment by soulofc** [comment]
马克思主义是一坨屎，中国是高科技信息时代的奴隶主义大国，奴隶们打着毒疫苗，喝着毒奶粉，交着高昂的税费，奴隶主们平时吃你这种夹头丘八入伍去搞生态农庄的特供，住高干病房，能报销几千万一年，器官坏了就从奴隶身上摘下来移植。

在 2018-07-23 12:32:02，"xgz123" <notifications@github.com> 写道：


国民党时代军阀割据，国家名义上统一实则四分五裂，怎么能和今天比呢？
一个小小的台湾都治理不好，台湾乱象，完全是由于国民党的无能。
几十万日杂就能搞垮台湾，你想想中国大陆要面对的多少比日杂更复杂、更强大的势力，其难度不在一个等级。
我认为现在的中国是纵观几千年历史，最好的时代。首先古代和现代是没法比的，就不多说了。横向来看，中国是当今世界上和平、稳定的大国。

说实在的，我们中国几千来的政治经验，真的不是外国人用一点理想主义就能当老师的。
自由、民主，喊几句就万事大吉、成真了？事实证明这些都是政治工具而已。

制度不符合生产力，就会被推翻，这是真理，不是谁能左右的。
长不长久，还看发展自我的能力，这是马克思主义的基本观点。

**Comment by soulofc** [comment]
徐汇区小学生才被砍，至于昆明火车站砍人，你这个傻逼不知道啊 ？

在 2018-07-22 19:03:50，"xgz123" <notifications@github.com> 写道：


老实说咱门中国的体制虽然有问题，但事实证明国家的制度并没有成为社会发展的障碍，而是随着社会发展而不断改变、进步的。相反，看所谓的西方民主国家，效率低下，难民、恐怖主义横行，到底是哪种更先进呢？

**Comment by xgz123** [comment]
@soulofc 徐汇区小学生才被砍，至于昆明火车站砍人，你这个傻逼不知道啊 ？ ？这是谁的错？你连这个都搞不清。。。智障。请不要再回复我，浪费我的时间。

**Comment by soulofc** [comment]
垃圾， 你这共狗，滚回去看新闻联播把，那里面你认的大大天天都出镜

在 2018-07-28 23:34:54，"xgz123" <notifications@github.com> 写道：


@soulofc 徐汇区小学生才被砍，至于昆明火车站砍人，你这个傻逼不知道啊 ？ ？这是谁的错？你连这个都搞不清。。。智障。请不要再回复我，浪费我的时间。

**Comment by soulofc** [comment]
你老母的错，你老母没有献出身体去慰安，没为创造和谐社会出力




在 2018-07-28 23:34:54，"xgz123" <notifications@github.com> 写道：


@soulofc 徐汇区小学生才被砍，至于昆明火车站砍人，你这个傻逼不知道啊 ？ ？这是谁的错？你连这个都搞不清。。。智障。请不要再回复我，浪费我的时间。
