### ISSUE TITLE
能不能还技术一个净地，让技术归于技术，政治归于政治，这些破事我们知道也没屌用哇，tg怎么样大家心里没点acde数吗，还想愉快地玩 GitHub 呢。

### ISSUE THREAD

**Issue by Sobcat** [programthink/zhao#183]
能不能还技术一个净地，让技术归于技术，政治归于政治，这些破事我们知道也没屌用哇，tg怎么样大家心里没点acde数吗，还想愉快地玩 GitHub 呢。

**Comment by soulofc** [comment]
专制之下哪里有净地? 别把头埋在沙子了! 何况又不是Zhao让你上不了github, 你应该去找中宣部请愿啊

在 2018-08-25 00:04:15，"Sobcat" <notifications@github.com> 写道：


能不能还技术一个净地，这些我们破事知道也没屌用，tg怎么样大家没数吗，可不想GitHub都再墙了。

**Comment by rainbow702** [comment]
纯技术，不要掺杂政治，好么

**Comment by soulofc** [comment]
谁封github找谁去，zhao没有去你的repo下推送留言吧，不影响你研究纯技术的

在 2018-08-29 13:31:31，"Zheng Wang" <notifications@github.com> 写道：


纯技术，不要掺杂政治，好么
