### ISSUE TITLE
xx

### ISSUE THREAD

**Issue by ZikeX** [programthink/zhao#184]

**Comment by soulofc** [comment]
github都同意放轮到你来这里唧唧歪歪？who are you ? who care about you ?

在 2018-08-27 15:35:42，"ZikeX" <notifications@github.com> 写道：


还技术一片清净，别把那些屁股流脓的政治傻叉弄上来。看着恶心

**Comment by ZikeX** [comment]
@soulofc who are you ? who care about you ?

跳梁小丑，闹得欢实。

**Comment by soulofc** [comment]
共狗你好，用爱国打造一个代码托管平台吧，别来github，共狗再见。

At 2018-08-27 16:24:58, "ZikeX" <notifications@github.com> wrote:


@soulofc who are you ? who care about you ?

跳梁小丑，闹得欢实。

**Comment by ZikeX** [comment]
傻逼，你妈逼！
简直无理取闹，共不共的，跟老子有球关系。

和你这种脑残讲，自己都觉得low。给老子死远点，傻逼！

**Comment by soulofc** [comment]
共狗恼羞成怒了




在 2018-08-27 20:10:28，"ZikeX" <notifications@github.com> 写道：


傻逼，你妈逼！
简直无理取闹，共不共的，跟老子有球关系。

和你这种脑残讲，自己都觉得low。给老子死远点，傻逼！

**Comment by captainCoconut** [comment]
@soulofc 你哪只眼睛看到github同意了？

**Comment by soulofc** [comment]
你哪只眼睛看到github没同意？

在 2018-08-30 20:33:58，captainCoconut <notifications@github.com> 写道：


@soulofc 你哪只眼睛看到github同意了？

**Comment by captainCoconut** [comment]
@soulofc 好的，既然咱们都不知道，那我就去找github举报一下，看看这种只聊政治不聊技术的项目放在github上，github和微软会不会同意

**Comment by IUSR** [comment]
https://help.github.com/articles/github-terms-of-service/#2-content-restrictions

**Comment by angiie** [comment]
“花生瓜子八宝粥，啤酒饮料矿泉水，哎，那位旅客，让一让，谢谢~”

**Comment by BonnieCabrera** [comment]
本站是唯一能访问的国外网站，请珍惜吧
