### ISSUE TITLE
本站是唯一能访问的国外网站，请珍惜吧

### ISSUE THREAD

**Issue by BonnieCabrera** [programthink/zhao#186]
本站是唯一能访问的国外网站，请珍惜吧

**Comment by gfw-breaker** [comment]
是应该珍惜，把被屏蔽的资源都搬到GitHub上来，让大家不翻墙也都能访问

**Comment by soulofc** [comment]
666, 哈哈，谁封的找谁去阿，在这里要求大家自我阉割，按这帮5毛的逻辑，全世界都得接受中共审查了，不然害得大家上不了谷歌的罪名就安上来了

在 2018-09-01 20:15:50，"HelloWorld" <notifications@github.com> 写道：


是应该珍惜，把被屏蔽的资源都搬到GitHub上来，让大家不翻墙也都能访问

**Comment by xuantie8ji** [comment]
> 本站是唯一能访问的国外网站，请珍惜吧

大门都关上了，留了个狗洞可以出去，是该珍惜。

**Comment by gfw-breaker** [comment]
@huang-yuan 新增内容，敬请关注 https://github.com/gfw-breaker/banned-news
