### ISSUE TITLE
奇怪， 为什么好多反对这个项目的人根本就没在GitHub上提交过代码？

### ISSUE THREAD

**Issue by gfw-breaker** [programthink/zhao#187]
翻看了好多issue，发现好多反对这个项目的人一上来就是破口大骂，打的旗号就是还GitHub清净，想愉快地写代码，不应该往上发政治相关的内容。
但是，查看了它们的主页后才发现，好多没头像没repo，即使有repo也基本上都是fork的，没改动一行代码。。。

**Comment by angiie** [comment]
对于这个项目，我的观点一直觉得是个科普性质的，不存在煽动反动行为的问题。没头像很正常啊，就是注册上来骂你一顿呗，搞的有多爱GitHub一样，要头像和代码干嘛呢...

**Comment by Dluo2** [comment]
骂人肯定不用大号来骂啊
