### ISSUE TITLE
要搞自己搭服务器搞，别把这么好的社区搞没了！

### ISSUE THREAD

**Issue by qzshadow** [programthink/zhao#19]
这些图改变不了你所谓的“高官”的任何事情，但可能断送千千万万程序员的梦想。

**Comment by posclegom** [comment]
只要不是违反GitHub的ToS的内容都可以放在GitHub上，楼主不要做精赵，不要自我阉割，不要做奴才。

**Comment by hellogfw** [comment]
https://github.com/programthink/zhao/issues/20

**Comment by programthink** [comment]
@qzshadow 
如果言论无法改变天朝的现状，为啥中宣部要疯狂地删除网上的政治言论？
显然说明：这些言论对朝廷的威胁很大哦 :)
俺不但要继续放这个项目，而且要再接再厉哦 :)

**Comment by posclegom** [comment]
狂顶编程兄！！！

**Comment by Naville** [comment]
心疼你们墙国人民wwwwwwwwww

**Comment by Naville** [comment]
翻墙都不会的程序员大概也就只能是个垃圾程序员呢wwwwwwww
这都怕还是混高贵的CocoaChina&MSDN吧wwww

**Comment by zencitta** [comment]
翻墙麻烦

**Comment by antipoliongithub** [comment]
@programthink 中宣部不是个东西，不过你这样的人多了，他怕是才有点工作的乐趣。最终就是苦了我等码农。我非常好奇，到底是什么动机让你如此不遗余力地`在GitHub上反党活动/反政府活动`（贵博原文）？

**Comment by jianxiaoBai** [comment]
@posclegom 想法太狭隘
