### ISSUE TITLE
站在统治者的角度，GFW 真的需要存在么？

### ISSUE THREAD

**Issue by razertory** [programthink/zhao#199]
中国是为数不多保留了数千年文化的国家，人口众多，战争不断，土地庞大，民族众多... 在这里理性看待这个问题，GFW 真的需要存在么？

**Comment by voicevon** [comment]
如果统治者以“愚民易于被统治，我位可长久”为出发点，那么GFW是当代统治者的有效的统治工具。与“数千年文化”没有关系。从华夏文化传承来看，今天的中国大陆远不如马来西亚华人社区，我说“远不如”，是定性；如果量化，可以用<10%。(如果不包含历史遗留的建筑，要修改10%为1%)

**Comment by soulofc** [comment]
现在的中国人大多是当年奴隶的后代，只能用意淫来安慰自己，说入侵者文化被汉族同化了，所以最终还是汉族文化胜利了。而事实是，国土被占，人和子孙后代都被奴役，男的杀女的轮，嘉定三屠，扬州十日，连郑成功母亲都沦为清军营妓。

在 2018-11-27 22:58:28，"Xuming Feng" <notifications@github.com> 写道：


如果统治者以“愚民易于被统治，我位可长久”为出发点，那么GFW是当代必要的统治工具。与“数千年文化”没有关系。从华夏文化传承来看，中国大陆远不如马来西亚华人社区，我说“远不如”，是定性，如果量化，可以用<10%。(如果不包含历史遗留的建筑，要修改10%为1%)
