### ISSUE TITLE
政治请上Twitter，不要污染Github

### ISSUE THREAD

**Issue by smallprogram** [programthink/zhao#213]
政治请上Twitter，不要污染Github，Github是程序员社区，软件代码的共享平台。如果您要讨论政治话题请您移步twitter或者其他平台。谢谢。

**Comment by jieekie** [comment]
自己跪着还不行，看到别了站着说话就受不了了。funny

**Comment by soulofc** [comment]
Be careful! CCP's dog wants you to shut up!

在 2019-05-29 09:34:28，"jieekie" <notifications@github.com> 写道：
自己跪着还不行，看到别了站着说话就受不了了。funny

**Comment by xuchendev** [comment]
您这种行为只会给Github用户带来风险，为了广大Github用户的权益，请您停止这种行为。并且我会像相关部门举报您这样的行为。

**Comment by jieekie** [comment]
阿贵：汪，汪，汪

《阿Q正传》

**Comment by smallprogram** [comment]
> 自己跪着还不行，看到别了站着说话就受不了了。funny
> […](#)
> On May 29, 2019, at 9:20 AM, zhusir ***@***.***> wrote: 政治请上Twitter，不要污染Github，Github是程序员社区，软件代码的共享平台。如果您要讨论政治话题请您移步twitter或者其他平台。谢谢。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

凡事都要讲个规矩，我并没有跪着，我靠我本事吃饭，我对政治不敏感，我只是说Github这个平台是用于讨论程序与代码相关的问题的地方，不是讨论政治的地方。这么说你能明白我的意思了吗？
要讨论政治请上别的平台讨论。不要把这个用于源码、开源、技术平台搞得乱七八糟。
还有我的回复里没有一个字眼是针对某人的侮辱。请不要一张嘴一回复就人身攻击。这样显得你们很疯狂，很不讲道理，很不讲究。

**Comment by jieekie** [comment]
Github不能讨论政治，请问这是你自己这么认为的，还是github官方有这样的明文规定？你有不讨论政治的自由，我也有讨论的自由（前提是官方没有限制，如果有限制，请告知，我确实是不知道，如果是不遵守规则，那是我的问题，我可以道歉，并且今后不再在此讨论）不知道我说明白了没有？不知道你是否清楚这个项目是干什么的？

**Comment by smallprogram** [comment]
> Github不能讨论政治，请问这是你自己这么认为的，还是github官方有这样的明文规定？你有不讨论政治的自由，我也有讨论的自由（前提是官方没有限制，如果有限制，请告知，我确实是不知道，如果是不遵守规则，那是我的问题，我可以道歉，并且今后不再在此讨论）不知道我说明白了没有？不知道你是否清楚这个项目是干什么的？
> […](#)
> On Jun 3, 2019, at 9:42 AM, zhusir ***@***.***> wrote: 自己跪着还不行，看到别了站着说话就受不了了。funny … On May 29, 2019, at 9:20 AM, zhusir @.***> wrote: 政治请上Twitter，不要污染Github，Github是程序员社区，软件代码的共享平台。如果您要讨论政治话题请您移步twitter或者其他平台。谢谢。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. 凡事都要讲个规矩，我并没有跪着，我靠我本事吃饭，我对政治不敏感，我只是说Github这个平台是用于讨论程序与代码相关的问题的地方，不是讨论政治的地方。这么说你能明白我的意思了吗？ 要讨论政治请上别的平台讨论。不要把这个用于源码、开源、技术平台搞得乱七八糟。 还有我的回复里没有一个字眼是针对某人的侮辱。请不要一张嘴一回复就人身攻击。这样显得你们很疯狂，很不讲道理，很不讲究。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

请你参考Github Issue的原则
https://help.github.com/en/articles/about-issues
如果你看不懂我可以给你翻译一下。
You can collect user feedback, report software bugs, and organize tasks you'd like to accomplish with issues in a repository. Issues can act as more than just a place to report software bugs.
您可以收集用户反馈，**报告软件错误**，**并组织您希望通过存储库中的问题完成的任务**。问题不仅可以作为报告软件错误的地方。

**Comment by jieekie** [comment]
感谢你的翻译，你能直接贴出来禁止讨论政治的条款么？你知道这个项目是干什么的呢？

**Comment by soulofc** [comment]
你不想讨论政治并没有人去你的 repo下面留言揪着你讨论吧?也没有人推送政治内容给你吧? 你自己跑到揭露朝廷的repo下面想让人封口, 凭什么? 你有不讨论的自由,别人也有讨论的自由!

在 2019-06-03 09:42:23，"zhusir" <notifications@github.com> 写道：


自己跪着还不行，看到别了站着说话就受不了了。funny
…
On May 29, 2019, at 9:20 AM, zhusir @.***> wrote: 政治请上Twitter，不要污染Github，Github是程序员社区，软件代码的共享平台。如果您要讨论政治话题请您移步twitter或者其他平台。谢谢。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

凡事都要讲个规矩，我并没有跪着，我靠我本事吃饭，我对政治不敏感，我只是说Github这个平台是用于讨论程序与代码相关的问题的地方，不是讨论政治的地方。这么说你能明白我的意思了吗？
要讨论政治请上别的平台讨论。不要把这个用于源码、开源、技术平台搞得乱七八糟。
还有我的回复里没有一个字眼是针对某人的侮辱。请不要一张嘴一回复就人身攻击。这样显得你们很疯狂，很不讲道理，很不讲究。

**Comment by smallprogram** [comment]
> 你不想讨论政治并没有人去你的 repo下面留言揪着你讨论吧?也没有人推送政治内容给你吧? 你自己跑到揭露朝廷的repo下面想让人封口, 凭什么? 你有不讨论的自由,别人也有讨论的自由! 在 2019-06-03 09:42:23，"zhusir" <notifications@github.com> 写道： 自己跪着还不行，看到别了站着说话就受不了了。funny … On May 29, 2019, at 9:20 AM, zhusir @.***> wrote: 政治请上Twitter，不要污染Github，Github是程序员社区，软件代码的共享平台。如果您要讨论政治话题请您移步twitter或者其他平台。谢谢。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. 凡事都要讲个规矩，我并没有跪着，我靠我本事吃饭，我对政治不敏感，我只是说Github这个平台是用于讨论程序与代码相关的问题的地方，不是讨论政治的地方。这么说你能明白我的意思了吗？ 要讨论政治请上别的平台讨论。不要把这个用于源码、开源、技术平台搞得乱七八糟。 还有我的回复里没有一个字眼是针对某人的侮辱。请不要一张嘴一回复就人身攻击。这样显得你们很疯狂，很不讲道理，很不讲究。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

呵呵，告辞告辞，道不同不相为谋，您继续讨论，我关了这Issue便是

**Comment by dingdingrun** [comment]
没有为政治服务的程序吗？长城防火墙呢？学习强国app呢？😂这不是道不同，这是幼稚。

**Comment by ghost** [comment]
> 没有为政治服务的程序吗？长城防火墙呢？学习强国app呢？😂这不是道不同，这是幼稚。

恁偷换概念的能力有一手   我寻思这仓库与程序没有任何相关。

**Comment by chinyichun** [comment]
> > 没有为政治服务的程序吗？长城防火墙呢？学习强国app呢？😂这不是道不同，这是幼稚。
> 
> 恁偷换概念的能力有一手 我寻思这仓库与程序没有任何相关。

@OPENGL-ES 那所以呢？这个仓库就不能存在于Github上吗？Github是你开的？

**Comment by OPENGL-ES** [comment]
> > > 没有为政治服务的程序吗？长城防火墙呢？学习强国app呢？😂这不是道不同，这是幼稚。
> 
> > 
> 
> > 恁偷换概念的能力有一手 我寻思这仓库与程序没有任何相关。
> 
> 
> 
> @OPENGL-ES 那所以呢？这个仓库就不能存在于Github上吗？Github是你开的？

你说得太对了😭

**Comment by ghost** [comment]
> > > 没有为政治服务的程序吗？长城防火墙呢？学习强国app呢？😂这不是道不同，这是幼稚。
> 
> > 
> 
> > 恁偷换概念的能力有一手 我寻思这仓库与程序没有任何相关。
> 
> 
> 
> @OPENGL-ES 那所以呢？这个仓库就不能存在于Github上吗？Github是你开的？

我也没说不可存在啊  我只是说本仓库与程序无关系  他是你爹？😰

**Comment by chinyichun** [comment]
> > > > 没有为政治服务的程序吗？长城防火墙呢？学习强国app呢？😂这不是道不同，这是幼稚。
> > 
> > 
> > > 
> > 
> > 
> > > 恁偷换概念的能力有一手 我寻思这仓库与程序没有任何相关。
> > 
> > 
> > @OPENGL-ES 那所以呢？这个仓库就不能存在于Github上吗？Github是你开的？
> 
> 我也没说不可存在啊 

@OPENGL-ES 那不就结了，瞎哔哔那么多废话干嘛？

**Comment by ghost** [comment]
> > > > > 没有为政治服务的程序吗？长城防火墙呢？学习强国app呢？😂这不是道不同，这是幼稚。
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 恁偷换概念的能力有一手 我寻思这仓库与程序没有任何相关。
> 
> > > 
> 
> > > 
> 
> > > @OPENGL-ES 那所以呢？这个仓库就不能存在于Github上吗？Github是你开的？
> 
> > 
> 
> > 我也没说不可存在啊 
> 
> 
> 
> @OPENGL-ES 那不就结了，瞎哔哔那么多废话干嘛？

不是你在bb？真无语了，GitHub是你开的？

**Comment by chinyichun** [comment]
> > > > > > 没有为政治服务的程序吗？长城防火墙呢？学习强国app呢？😂这不是道不同，这是幼稚。
> > > > > 恁偷换概念的能力有一手 我寻思这仓库与程序没有任何相关。
> > > > @OPENGL-ES 那所以呢？这个仓库就不能存在于Github上吗？Github是你开的？
> > > 我也没说不可存在啊
> > @OPENGL-ES 那不就结了，瞎哔哔那么多废话干嘛？
> 不是你在bb？真无语了，GitHub是你开的？

@OPENGL-ES  不是你在bb？真无语了，GitHub是你开的？

**Comment by chinyichun** [comment]
> 不是你在bb？真无语了，GitHub是你开的？

@OPENGL-ES 劳烦你往上卷一下，看看是谁先在这个帖子里开始bb的，谁是随后回应bb的。

**Comment by ghost** [comment]
> > 不是你在bb？真无语了，GitHub是你开的？
> 
> 
> 
> @OPENGL-ES 劳烦你往上卷一下，看看是谁先在这个帖子里开始bb的，谁是随后回应bb的。

你觉得我在bb别回我就是了   胡搅蛮缠有意思？我纯看这人上来就说别人幼稚很不爽而已啊，有说这个仓库不能存在吗？你是编程随想？

**Comment by chinyichun** [comment]
> > > 不是你在bb？真无语了，GitHub是你开的？
> > 
> > 
> > @OPENGL-ES 劳烦你往上卷一下，看看是谁先在这个帖子里开始bb的，谁是随后回应bb的。
> 
> 你觉得我在bb别回我就是了 胡搅蛮缠有意思？我纯看这人上来就说别人幼稚很不爽而已啊，有说这个仓库不能存在吗？你是编程随想？

@OPENGL-ES 就许你bb，不许我回你？GitHub是你开的？

**Comment by ghost** [comment]
> > > > 不是你在bb？真无语了，GitHub是你开的？
> 
> > > 
> 
> > > 
> 
> > > @OPENGL-ES 劳烦你往上卷一下，看看是谁先在这个帖子里开始bb的，谁是随后回应bb的。
> 
> > 
> 
> > 你觉得我在bb别回我就是了 胡搅蛮缠有意思？我纯看这人上来就说别人幼稚很不爽而已啊，有说这个仓库不能存在吗？你是编程随想？
> 
> 
> 
> @OPENGL-ES 就许你bb，不许我回你？GitHub是你开的？

**对对对就是我开的**

**Comment by chinyichun** [comment]
> > > > > 不是你在bb？真无语了，GitHub是你开的？
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > @OPENGL-ES 劳烦你往上卷一下，看看是谁先在这个帖子里开始bb的，谁是随后回应bb的。
> > 
> > 
> > > 
> > 
> > 
> > > 你觉得我在bb别回我就是了 胡搅蛮缠有意思？我纯看这人上来就说别人幼稚很不爽而已啊，有说这个仓库不能存在吗？你是编程随想？
> > 
> > 
> > @OPENGL-ES 就许你bb，不许我回你？GitHub是你开的？
> 
> **对对对就是我开的**

@OPENGL-ES 好好说话，尊重所有人在这里言论自由的权利，对于你们这些墙内的人来说，怎么就那么难呢？

**Comment by OPENGL-ES** [comment]
> > > > > > 不是你在bb？真无语了，GitHub是你开的？
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > @OPENGL-ES 劳烦你往上卷一下，看看是谁先在这个帖子里开始bb的，谁是随后回应bb的。
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 你觉得我在bb别回我就是了 胡搅蛮缠有意思？我纯看这人上来就说别人幼稚很不爽而已啊，有说这个仓库不能存在吗？你是编程随想？
> 
> > > 
> 
> > > 
> 
> > > @OPENGL-ES 就许你bb，不许我回你？GitHub是你开的？
> 
> > 
> 
> > **对对对就是我开的**
> 
> 
> 
> @OPENGL-ES 好好说话，尊重所有人在这里言论自由的权利，对于你们这些墙内的人来说，怎么就那么难呢？

你墙外婆罗门，我完完全全的墙内🐭人

**Comment by ghost** [comment]
> > > > > > 不是你在bb？真无语了，GitHub是你开的？
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > @OPENGL-ES 劳烦你往上卷一下，看看是谁先在这个帖子里开始bb的，谁是随后回应bb的。
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 你觉得我在bb别回我就是了 胡搅蛮缠有意思？我纯看这人上来就说别人幼稚很不爽而已啊，有说这个仓库不能存在吗？你是编程随想？
> 
> > > 
> 
> > > 
> 
> > > @OPENGL-ES 就许你bb，不许我回你？GitHub是你开的？
> 
> > 
> 
> > **对对对就是我开的**
> 
> 
> 
> @OPENGL-ES 好好说话，尊重所有人在这里言论自由的权利，对于你们这些墙内的人来说，怎么就那么难呢？

令人感叹，我哪句话不尊重言论自由了呢？
我承认赵国不是那么言论自由，我也巴不得维尼下台，精神墙外人大可不必

**Comment by chinyichun** [comment]
@

> > > > > > > 不是你在bb？真无语了，GitHub是你开的？
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > @OPENGL-ES 劳烦你往上卷一下，看看是谁先在这个帖子里开始bb的，谁是随后回应bb的。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 你觉得我在bb别回我就是了 胡搅蛮缠有意思？我纯看这人上来就说别人幼稚很不爽而已啊，有说这个仓库不能存在吗？你是编程随想？
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > @OPENGL-ES 就许你bb，不许我回你？GitHub是你开的？
> > 
> > 
> > > 
> > 
> > 
> > > **对对对就是我开的**
> > 
> > 
> > @OPENGL-ES 好好说话，尊重所有人在这里言论自由的权利，对于你们这些墙内的人来说，怎么就那么难呢？
> 
> 令人感叹，我哪句话不尊重言论自由了呢？
> 我承认赵国不是那么言论自由，我也巴不得维尼下台
> 精神墙外人 大可不必

@OPENGL-ES 好！为你刚才这几句话点👍！
