### ISSUE TITLE
只能说西方洗脑真厉害

### ISSUE THREAD

**Issue by r1cebank** [programthink/zhao#237]
这段时间香港的事情大家也看到了，本人在墙外，只要是反对中国政府的言论就可以得到很多赞，star，fork。。等等。。

**先说该不该评论中国政府吧：**
我个人认为任何政府都做过有争议的事情，本人不才，没办法一一列出。但是在美国9年加拿大五年我可以跟愤青说，“民主”，“自由”这个东西的定义就是西方政府定义的。现在在国外反对共产党的声音很强，你们说是“言论自由”。但是支持共产党的人一发言就被说成是“无脑爱国”，“斯德哥尔摩综合症“。那请问这是什么言论自由？你可以评论，我也可以反对。

**中国怎么才能达到美国所说的“民主”？**
在我看来，除非建立了傀儡政府，每年竞选的候选人都是CIA内定的，中国永远达不到西方社会所说的“民主”。

**民主好不好？**
我个人觉得民主，还有专政，都有好处和坏处。但是在国内居住的人也感受到了吧，中国近几年把专政的好处发挥到极致。而西方的“民主”，除了民众可以投几次票，这个政权真的有帮助过人民吗？

**可是共产党xxxx，他们无法无天，只要是政府的人，杀了人不坐牢，迫害坐牢的人，摘器官。。**
我无法证实有些事情是否发生，也懒得去自己考证。但是在国外生活了这么多年，这些事情难道真的不会在自由的美利坚发生吗？自由民主就是人类的救赎？

**可是共产党不好。。。**
我知道不好，我从小的教育也告诉我共产党不好。共产党会毁掉人类。可是我离开了学校以后看到的并不是这样，我们难道就是因为共产党是共产党，就忽略了中国70年的进步吗？在我看来，如果当年不是共产党当政，我们现在还会像台湾一样吧。

**可是我认识的xxx，她的家人被共产党xxx，我也经历过xxx**
每个黑中共的人都说自己有个亲戚/女朋友/男朋友 被共产党迫害过。。。。

**你不在国内，怎么知道共产党多黑暗。。。**
你不在国外。。怎么知道西方“民主”这么光明？

最后留给大家一个可以考虑的事情吧，这个repo的readme是这样写的。
> 对这个项目，俺会【持续更新】。比如朝廷每次换届的时候，俺都会补充新的素材。
> 
> 为了确保数据的可信度，俺主要参考“维基百科”以及一些国际权威媒体的报道（比如《纽约时报》、《华尔街日版》、《金融时报》等等）。

貌似只有西方媒体才是可信的。。

You always find what you want to find.

**Comment by chinyichun** [comment]
我在西方二十年。其实我是否拥护共产党十分简单：共产党把墙拆了我拥护，否则我就不拥护。

这够简单，够实在了吧。好了现在请你回答。谢谢。

**Comment by r1cebank** [comment]
你不拥护就不拥护啊，没有人求你。不想要墙就不在中国呆着，很简单吧。

**Comment by chinyichun** [comment]
你跑到这儿来论证共产党的优越性，不是吗?
我指出了问题，你叫我肉身翻墙，那就代表你也觉得墙是一个问题。
还有中国朝代没有超过三百年的，你不会天真到认为共产党可以维持三百年吧。

**Comment by r1cebank** [comment]
是的，我就是来说共产党优越性的。因为我觉得最适合治理中国的就是共产党。墙是个问题，我也没有说共产党是无可挑剔的。

**Comment by GaryYufei** [comment]
怎么说呢，我觉得大趋势上来说，这是早晚的事。你看中美的协议上不都写了要金融开放嘛～

但凡事都要讲究个度，步子迈太大就会扯蛋，过于激进没什么好处。

说个笑话哈，其实你觉不觉得墙是在保护西方人？要是把墙撤了，那些美国键盘侠分分钟要被中国键盘侠给淹没，到时候恐怕美国要建墙了。

**Comment by chinyichun** [comment]
> 是的，我就是来说共产党优越性的。因为我觉得最适合治理中国的就是共产党。墙是个问题，我也没有说共产党是无可挑剔的。

那我现在指出一个非常容易办到的小事--拆墙，一旦办到了，共产党就更加完美，更加适合治理中国了。那不是好事一桩嘛。

**Comment by chinyichun** [comment]
> 说个笑话哈，其实你觉不觉得墙是在保护西方人？要是把墙撤了，那些美国键盘侠分分钟要被中国键盘侠给淹没，到时候恐怕美国要建墙了。

@GaryYufei 我不觉得，互联网足够大，容纳得了both美国键盘侠和中国键盘侠。再说语言不通的话，美国键盘侠无视中国键盘侠不就行了。😁😁😁

**Comment by GaryYufei** [comment]
但如果是交叉议题，比如轮子之类的，或者华人和中国人键盘侠之类的，我觉得中国人很可能因为人数多而胜出。不过呢，这不是共产党建墙的理由，墙是一定要拆的，因为我们终究要走向世界。

**Comment by chinyichun** [comment]
> 墙是一定要拆的，因为我们终究要走向世界。

@GaryYufei 点赞点赞👍👍👍👍👍👍👍👍👍👍👍👍👍。我不能更加严重同意你这句话了。

> 我觉得中国人很可能因为人数多而胜出。

无所谓胜出，因为真理越辩越明。关键是中国人与全球各个角落的人从此就可以自由交流了，这才是最最重要的一点。

**Comment by KangChien** [comment]
**先说该不该骂楼主吧：**
我个人认为任何人都有傻逼的时候。但是作为一个一直以来遵守言论自由的人我可以很负责的告诉楼主“言论自由”一般来说要符合公序良俗的，你是傻逼，可是我们一般不说，因为这是素质。

**楼主怎么才能不傻逼：**
在我看来，除非切了额叶，否则是救不了了。

**智力好不好？**
我觉得智力高低有好处也有坏处。楼主反正放弃了做个鸵鸟，显得很心安理得。反倒是没有放弃智商的人，明明自己不是被统治者却担忧被统治的劳苦大众，给自己找事，这点属实要向楼主学习。

**可是还有很多人比楼主还要傻逼。。**
我无法证实有些事情是否发生，也懒得去自己考证。但是楼主真的不至于比他们更傻逼吗？我不觉得啊？反正他回答问题都是靠“我觉得我觉得”，确实是可以做到的。

**在我看来，如果当年不是共产党当政，我们现在还会像台湾一样吧。**
你在逗我吗？中国人比台湾好？我承认在这里说话的各位基本上在中国投胎技术也算不是太差，但你们总认识、或者说能从一些统计数据看得出中国平民远不如台湾平民吧？你非要说中国就是上海那随便，只要上海的工人愿意做畜生那赶英超美不是梦。
