### ISSUE TITLE
大哥，你语文是不是有问题？

### ISSUE THREAD

**Issue by niefufeng** [programthink/zhao#24]
> 就好比强盗拿刀杀人，围观者不但没有谴责强盗，反而去谴责卖刀的店家——这就是传说中的“斯德哥尔摩综合症”。

大家担心你这个项目导致github被gfvv封杀，正确的例子是：

就好比强盗拿刀杀人，围观者不但没有谴责卖刀的店家（对应github，给你提供文件托管和展示的平台），反而取谴责拿刀杀人的强盗（即对应你，你用github提供的服务`杀人`）

当然，无论你的出发点是怎样（就算你杀的是一个无恶不作的），而导致店家关门，那么要买刀的人都不会原谅你！

**Comment by wang1988ming** [comment]
你的逻辑好混乱

**Comment by lyx32** [comment]
大哥，你语文是不是有问题？

**Comment by programthink** [comment]
@niefufeng 
你指责俺：
“用github提供的服务杀人”

这个说法太牵强了吧？
俺只不过是汇总了网上可以找到的公开资料。
其中有些资料甚至是来自天朝政府自己的网站。

**Comment by mx1700** [comment]
“病”的不轻

**Comment by posclegom** [comment]
正确的逻辑和比喻是不是应该这样表述：一位**不受**强盗（zhao）挟持（**会**翻墙）的顾客（programthink）在店家（github）这里**做**了一把危胁强盗（zhao）打劫的刀（ https://github.com/programthink/zhao/ ）， 结果导致强盗（zhao）可能会来报复店家（github）的另一些**受**强盗（zhao）挟持（**不会**翻墙）顾客，（强盗（zhao）之所以采用这么间接的报复方式是因为１。找不到打刀的那位顾客（programthink）的真人肉身加以摧毁２。店家（GitHub）开在番国（美帝），强盗拿不到签证，不能前来关闭捣毁店家（GitHub）３。强盗（zhao）以前曾经试图远程砸店（GitHub PK GFW第一、第二季）两次，均以失败告终），于是店家（github）的另一些**受**强盗（zhao）挟持（**不会**翻墙）的顾客（比如niefufeng）就忿忿的出来表示对这位**不受**强盗（zhao）挟持（**会**翻墙）的顾客（programthink）的不満。

**Comment by niefufeng** [comment]
@programthink 
我只是想表达你最后那个比喻不对而已，想不到自己也表达不清楚！！！悲伤！！！
可以看看 @posclegom 的版本。。。

@lyx32 别拆穿我～～～～（＞＿＜）～～～～

@mx1700 ｏ（╯□╰）ｏ

**Comment by posclegom** [comment]
@niefufeng 多谢赏识我那个版本。

**Comment by chenjiaqiang** [comment]
当然，无论你的出发点是怎样（就算你杀的是一个无恶不作的），
而导致店家关门，那么要买刀的人都不会原谅你！

什么逻辑？是你语文功力差了吧？
应该要把博主谴责成卖炸药的，那你还可能占点道德高地。

“不去谴责用炸药杀人的，却去谴责卖炸药的人？谁叫你卖炸药来着，你不卖炸药，他们用什么去炸人？”

**Comment by myahmao** [comment]
总结汇总一些资料就成了卖刀的了，多么神奇的比喻，大概是跪久了吧，站一会儿就浑身不自在。
