### ISSUE TITLE
南中國海發生核子事故

### ISSUE THREAD

**Issue by gogobook** [programthink/zhao#246]
https://halturnerradioshow.com/index.php/en/news-page/world/there-has-been-an-incident-in-the-south-china-sea?fbclid=IwAR1mJO5uNDr4SwVAhQve5s2vAeDSUqwiqg-9xKjXQUih4fu0eYu0XLYzs-4

## 目前不確定是哪國家的核彈在這裡炸了，爆炸當量是1萬噸到2萬噸間。
![圖片](https://user-images.githubusercontent.com/9208031/69326096-31455600-0c86-11ea-8503-cd49ad62e88f.png)

Oceanographic instruments monitoring the South China Sea have reportedly registered a significant undersea EXPLOSION. 

Details are sketchy as of 6:22 PM eastern US time, but military sources are saying an explosion took place at a depth of approximately 50 Meters, which caused an underwater shock wave of such sudden presence, and of such strength, that the explosion itself "had to be between 10 and 20 Kilotons."  Those sources (military) also say explicitly "An earthquake has been ruled out."

United States submarines routinely operate in that area of the world's oceans.

If an explosion of that magnitude took place, it could reek havoc with the submarine(s) and their instruments; perhaps forcing them to leave an area, or perhaps put into port for re-calibration or repairs.

There is nothing in the area of the South China Sea which, on its own, can account for such a possible event.  

Details remain very sketchy at this hour, but tune-in to the Hal Turner Show tonight on WBCQ (7.490 or 5.130 AM) or WRMI (9.455 AM) or KYAH 540-AM "Utah's Talk Authority" for the latest details.  You can also tune-in here on the net using the LISTEN ONLINE button in the menu bar above.  (Those internet links do not go active until about an hour before the show starts, and stream commercial-free music until the show begins at 9:00 PM eastern US time (GMT -0500)

 
UPDATE 11:17 PM EST --

Radiation is now being detected at shore monitoring points around the South China Sea!

According to this official map from the uRADMonitor Global Environmental Monitoring Network, "significant" radiation readings are now registering on their radiation monitors, shown on the map below:
![圖片](https://user-images.githubusercontent.com/9208031/69326144-4621e980-0c86-11ea-95fe-b125fbe663cd.png)

**Comment by gogobook** [comment]
目前只有一家媒體報導，後續待確認。

**Comment by jieekie** [comment]
也有人说是假新闻，自行判断


https://vpk-news.ru/news/53785

_ _
诸事顺遂
jieekie


发件人: gogobook
发送时间: 2019年11月21日 17:42
收件人: programthink/zhao
抄送: Subscribed
主题: [programthink/zhao] 南中國海發生核子事故 (#246)

https://halturnerradioshow.com/index.php/en/news-page/world/there-has-been-an-incident-in-the-south-china-sea?fbclid=IwAR1mJO5uNDr4SwVAhQve5s2vAeDSUqwiqg-9xKjXQUih4fu0eYu0XLYzs-4
目前不確定是哪國家的核彈在這裡炸了，爆炸當量是1萬噸到2萬噸間。

Oceanographic instruments monitoring the South China Sea have reportedly registered a significant undersea EXPLOSION.
Details are sketchy as of 6:22 PM eastern US time, but military sources are saying an explosion took place at a depth of approximately 50 Meters, which caused an underwater shock wave of such sudden presence, and of such strength, that the explosion itself "had to be between 10 and 20 Kilotons." Those sources (military) also say explicitly "An earthquake has been ruled out."
United States submarines routinely operate in that area of the world's oceans.
If an explosion of that magnitude took place, it could reek havoc with the submarine(s) and their instruments; perhaps forcing them to leave an area, or perhaps put into port for re-calibration or repairs.
There is nothing in the area of the South China Sea which, on its own, can account for such a possible event.
Details remain very sketchy at this hour, but tune-in to the Hal Turner Show tonight on WBCQ (7.490 or 5.130 AM) or WRMI (9.455 AM) or KYAH 540-AM "Utah's Talk Authority" for the latest details. You can also tune-in here on the net using the LISTEN ONLINE button in the menu bar above. (Those internet links do not go active until about an hour before the show starts, and stream commercial-free music until the show begins at 9:00 PM eastern US time (GMT -0500)
UPDATE 11:17 PM EST --
Radiation is now being detected at shore monitoring points around the South China Sea!
According to this official map from the uRADMonitor Global Environmental Monitoring Network, "significant" radiation readings are now registering on their radiation monitors, shown on the map below:

**Comment by jieekie** [comment]
https://gizmodo.com/no-china-did-not-secretly-detonate-a-nuke-in-the-south-1839988450

_ _
诸事顺遂
jieekie


发件人: jieekei
发送时间: 2019年11月22日 12:24
收件人: programthink/zhao; programthink/zhao
抄送: Subscribed
主题: 回复: [programthink/zhao] 南中國海發生核子事故 (#246)

也有人说是假新闻，自行判断


https://vpk-news.ru/news/53785

_ _
诸事顺遂
jieekie


发件人: gogobook
发送时间: 2019年11月21日 17:42
收件人: programthink/zhao
抄送: Subscribed
主题: [programthink/zhao] 南中國海發生核子事故 (#246)

https://halturnerradioshow.com/index.php/en/news-page/world/there-has-been-an-incident-in-the-south-china-sea?fbclid=IwAR1mJO5uNDr4SwVAhQve5s2vAeDSUqwiqg-9xKjXQUih4fu0eYu0XLYzs-4
目前不確定是哪國家的核彈在這裡炸了，爆炸當量是1萬噸到2萬噸間。

Oceanographic instruments monitoring the South China Sea have reportedly registered a significant undersea EXPLOSION.
Details are sketchy as of 6:22 PM eastern US time, but military sources are saying an explosion took place at a depth of approximately 50 Meters, which caused an underwater shock wave of such sudden presence, and of such strength, that the explosion itself "had to be between 10 and 20 Kilotons." Those sources (military) also say explicitly "An earthquake has been ruled out."
United States submarines routinely operate in that area of the world's oceans.
If an explosion of that magnitude took place, it could reek havoc with the submarine(s) and their instruments; perhaps forcing them to leave an area, or perhaps put into port for re-calibration or repairs.
There is nothing in the area of the South China Sea which, on its own, can account for such a possible event.
Details remain very sketchy at this hour, but tune-in to the Hal Turner Show tonight on WBCQ (7.490 or 5.130 AM) or WRMI (9.455 AM) or KYAH 540-AM "Utah's Talk Authority" for the latest details. You can also tune-in here on the net using the LISTEN ONLINE button in the menu bar above. (Those internet links do not go active until about an hour before the show starts, and stream commercial-free music until the show begins at 9:00 PM eastern US time (GMT -0500)
UPDATE 11:17 PM EST --
Radiation is now being detected at shore monitoring points around the South China Sea!
According to this official map from the uRADMonitor Global Environmental Monitoring Network, "significant" radiation readings are now registering on their radiation monitors, shown on the map below:
