### ISSUE TITLE
@TwTravel 我操你祖宗十八代！

### ISSUE THREAD

**Issue by chinyichun** [programthink/zhao#258]
@TwTravel 你在编程随想这儿还搞一言堂，还禁止我在你的帖子下发言。我艹你妈的逼，艹你祖宗十八代！

不服来骂！老子是不会禁言🚭你的。

操你妈的。

**Comment by chinyichun** [comment]
@TwTravel 看来我误解你了，我在我自己的repo下面可以回复你。就此关闭此issue。

**Comment by AnyWAT** [comment]
😥骂人能解决问题？
还禁止我在你的帖子下发言——貌似被拉黑，乃各自的权利😂

**Comment by chinyichun** [comment]
> 还禁止我在你的帖子下发言——貌似被拉黑，乃各自的权利😂

这个真的很奇妙，在 @TwTravel 的楼里，@TwTravel 作为楼主还可以控制自己楼层里的言论自由，@TwTravel 的楼是 @TwTravel 的领地，除非编程随想出面管理，但是我们已经知道编程随想是不会这么做的。
