### ISSUE TITLE
满朝文武能把董卓哭死？

### ISSUE THREAD

**Issue by expyhist** [programthink/zhao#261]
这些东西其实也就是屁民们的小打小闹。看issue，你让中共灭亡，习滚蛋。就能实现？满朝文武能把董卓哭死？哈哈哈。
不过中共现在确实烂，民主化进程不仅没有进展，反而后退了。
反正历史的最终会做出抉择。大家等着看就是了。
如果中共一直烂下去，自然有新的组织出现并代替他，时机未到罢了。
如果中共好转，那你好，我好大家好。

**Comment by KINGVON1** [comment]
那你说的是个什么玩意儿，阴阳怪气。

**Comment by expyhist** [comment]
怎么？现实里唯唯诺诺，996都不敢反抗。网上重拳出击？说issue里的人都是嘴强王者就是阴阳怪气？怕是戳到你心里痛处哦。哈哈

KINGVON1 <notifications@github.com>于2019年12月17日 周二16:49写道：
