### ISSUE TITLE
github什么时候出举报功能，举报和代码无关的东西

### ISSUE THREAD

**Issue by liuyatao** [programthink/zhao#264]

**Comment by Changgang-Zheng** [comment]
Github 已经被有些人用于政治了。。为啥不出个举报功能啊

**Comment by chinyichun** [comment]
> Github 已经被有些人用于政治了。。为啥不出个举报功能啊

@Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。

**Comment by Changgang-Zheng** [comment]
老哥我在uk。。。。你在哪？

**Comment by Changgang-Zheng** [comment]
> > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> 
> @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。

老哥我在uk。。。。你在哪？
别整的哪天这小站被block了何必呢。。。。。

**Comment by Changgang-Zheng** [comment]
> > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> 
> @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。

真的，在这里搞搞代码就可以了，天天在这里发泄不满搞政治何必呢。你看看你的repository里都是些啥😂

**Comment by chinyichun** [comment]
> > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > 
> > 
> > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> 
> 老哥我在uk。。。。你在哪？
> 别整的哪天这小站被block了何必呢。。。。。

@Changgang-Zheng 你在uk那就更加不怕GitHub被墙啦。而且到这个小站来的都是码农，需要查阅谷歌才能写码。码农如果连墙都不会翻的话，那还是不要做码农了。乘早卷铺盖走人。

**Comment by chinyichun** [comment]
> > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > 
> > 
> > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> 
> 真的，在这里搞搞代码就可以了，天天在这里发泄不满搞政治何必呢。你看看你的repository里都是些啥😂

@Changgang-Zheng 因为这是墙外我们可以行使的言论自由。而且GitHub上面还有 government.github.com呢，你又作何解释？

**Comment by Edmodo-Luo** [comment]
> > > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > > 
> > > 
> > > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> > 
> > 
> > 真的，在这里搞搞代码就可以了，天天在这里发泄不满搞政治何必呢。你看看你的repository里都是些啥😂
> 
> @Changgang-Zheng 因为这是墙外我们可以行使的言论自由。而且GitHub上面还有 government.github.com呢，你又作何解释？

自由尼🐎️呢 张口闭口就知道民主自由

**Comment by TgDaosheng** [comment]
> Github 已经被某些人用政治了。。为啥不出个升级功能啊

GitHub妖魔鬼怪特别多，很多都是垃圾忽悠

**Comment by xwjj** [comment]
> > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> 
> @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。

github是用来搞政治的吗，顺便说一句github国内是允许访问的，白痴，墙不是屏蔽一切外国网站，是屏蔽不遵守中国国家法律规定的网站，白痴，在程序员的网站上搞政治，本身就令人作呕，反华分子骗一骗低智商人群就算了，还想来这骗，随便查一查就知道说的有几句话是真的，弱智，naive idiot

**Comment by Atomadeus** [comment]
> > > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > > 
> > > 
> > > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> > 
> > 
> > 真的，在这里搞搞代码就可以了，天天在这里发泄不满搞政治何必呢。你看看你的repository里都是些啥😂
> 
> @Changgang-Zheng 因为这是墙外我们可以行使的言论自由。而且GitHub上面还有 government.github.com呢，你又作何解释？

笑死我了，还言论自由呢，你是指你美爹的双标自由？

**Comment by posclegom** [comment]
> > > > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > > > 
> > > > 
> > > > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> > > 
> > > 
> > > 真的，在这里搞搞代码就可以了，天天在这里发泄不满搞政治何必呢。你看看你的repository里都是些啥😂
> > 
> > 
> > @Changgang-Zheng 因为这是墙外我们可以行使的言论自由。而且GitHub上面还有 government.github.com呢，你又作何解释？
> 
> 笑死我了，还言论自由呢，你是指你美爹的双标自由？

@Atomadeus 你明知道我美爹的双标自由，还跑来使用我美爹的GitHub？你为何不滚回墙内去用你墙内的GitCafe/Gitee呢？

**Comment by Atomadeus** [comment]
你美爹都没BAN我你急什么，皇帝不急太监急。看好了，我这可是你在你主子的允许下使用GitHub的，小辣鸡。

posclegom ***@***.***> 于2023年5月10日周三 08:17写道：

**Comment by QuincyQAQ** [comment]
> > > > > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > > > > 
> > > > > 
> > > > > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> > > > 
> > > > 
> > > > 真的，在这里搞搞代码就可以了，天天在这里发泄不满搞政治何必呢。你看看你的repository里都是些啥😂
> > > 
> > > 
> > > @Changgang-Zheng 因为这是墙外我们可以行使的言论自由。而且GitHub上面还有 government.github.com呢，你又作何解释？
> > 
> > 
> > 笑死我了，还言论自由呢，你是指你美爹的双标自由？
> 
> @Atomadeus 你明知道我美爹的双标自由，还跑来使用我美爹的GitHub？你为何不滚回墙内去用你墙内的GitCafe/Gitee呢？

差不多得了，你爹都没禁止哥们用，你把自己当皇帝了是吧

**Comment by CharlotteDiamond** [comment]
> > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> 
> @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。

既然不是中国人，就别用中文

**Comment by Poiob** [comment]
> > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > 
> > 
> > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> 
> 既然不是中国人，就别用中文

这么能建议去剥夺台湾和马来西亚的中文使用权

**Comment by C1nese** [comment]
> > > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > > 
> > > 
> > > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> > 
> > 
> > 既然不是中国人，就别用中文
> 
> 这么能建议去剥夺台湾和马来西亚的中文使用权

怎么生活不容易啊 还tm建政 傻逼玩意

**Comment by FahaxikiLz** [comment]
用户首页下面有举报
![微信图片_20240306161326](https://github.com/programthink/zhao/assets/54607522/0e19fa1b-bf91-4e92-8651-48f6e455e953)

**Comment by braveBoyToT** [comment]
> > > > > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > > > > 
> > > > > 
> > > > > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> > > > 
> > > > 
> > > > 真的，在这里搞搞代码就可以了，天天在这里发泄不满搞政治何必呢。你看看你的repository里都是些啥😂
> > > 
> > > 
> > > @Changgang-Zheng 因为这是墙外我们可以行使的言论自由。而且GitHub上面还有 government.github.com呢，你又作何解释？
> > 
> > 
> > 笑死我了，还言论自由呢，你是指你美爹的双标自由？
> 
> @Atomadeus 你明知道我美爹的双标自由，还跑来使用我美爹的GitHub？你为何不滚回墙内去用你墙内的GitCafe/Gitee呢？

瞎jb叫你妈，人狗粮给你了吗这就认爹了，我们爱用不用管你屁事，你美爹有本事把我们禁了啊傻逼

**Comment by braveBoyToT** [comment]
> > > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > > 
> > > 
> > > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> > 
> > 
> > 老哥我在uk。。。。你在哪？
> > 别整的哪天这小站被block了何必呢。。。。。
> 
> @Changgang-Zheng 你在uk那就更加不怕GitHub被墙啦。而且到这个小站来的都是码农，需要查阅谷歌才能写码。码农如果连墙都不会翻的话，那还是不要做码农了。乘早卷铺盖走人。

叫叫叫，你是码农吗，给几根骨头就作妖的狗罢了

**Comment by posclegom** [comment]
> > > > > > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > > > > > 
> > > > > > 
> > > > > > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> > > > > 
> > > > > 
> > > > > 真的，在这里搞搞代码就可以了，天天在这里发泄不满搞政治何必呢。你看看你的repository里都是些啥😂
> > > > 
> > > > 
> > > > @Changgang-Zheng 因为这是墙外我们可以行使的言论自由。而且GitHub上面还有 government.github.com呢，你又作何解释？
> > > 
> > > 
> > > 笑死我了，还言论自由呢，你是指你美爹的双标自由？
> > 
> > 
> > @Atomadeus 你明知道我美爹的双标自由，还跑来使用我美爹的GitHub？你为何不滚回墙内去用你墙内的GitCafe/Gitee呢？
> 
> 瞎jb叫你妈，人狗粮给你了吗这就认爹了，我们爱用不用管你屁事，你美爹有本事把我们禁了啊傻逼

明知道GitHub是美国的东西还用？你这人不是贱还是什么？

**Comment by posclegom** [comment]
> > > > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > > > 
> > > > 
> > > > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> > > 
> > > 
> > > 老哥我在uk。。。。你在哪？
> > > 别整的哪天这小站被block了何必呢。。。。。
> > 
> > 
> > @Changgang-Zheng 你在uk那就更加不怕GitHub被墙啦。而且到这个小站来的都是码农，需要查阅谷歌才能写码。码农如果连墙都不会翻的话，那还是不要做码农了。乘早卷铺盖走人。
> 
> 叫叫叫，你是码农吗，给几根骨头就作妖的狗罢了

你不也是一条用GitHub的狗嘛。你这么有骨气，为什么不去使用Gitee呢。哦对了，你代码里面所有的x86-64都被Gitee转换成x86-**了。

**Comment by posclegom** [comment]
> > > > > > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > > > > > 
> > > > > > 
> > > > > > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> > > > > 
> > > > > 
> > > > > 真的，在这里搞搞代码就可以了，天天在这里发泄不满搞政治何必呢。你看看你的repository里都是些啥😂
> > > > 
> > > > 
> > > > @Changgang-Zheng 因为这是墙外我们可以行使的言论自由。而且GitHub上面还有 government.github.com呢，你又作何解释？
> > > 
> > > 
> > > 笑死我了，还言论自由呢，你是指你美爹的双标自由？
> > 
> > 
> > @Atomadeus 你明知道我美爹的双标自由，还跑来使用我美爹的GitHub？你为何不滚回墙内去用你墙内的GitCafe/Gitee呢？
> 
> 差不多得了，你爹都没禁止哥们用，你把自己当皇帝了是吧

是你把自己当皇帝了吧，GitHub都没禁止编程随想的GitHub仓库，你倒先着急起来了？

**Comment by posclegom** [comment]
> > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > 
> > 
> > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> 
> github是用来搞政治的吗，顺便说一句github国内是允许访问的，白痴，墙不是屏蔽一切外国网站，是屏蔽不遵守中国国家法律规定的网站，白痴，在程序员的网站上搞政治，本身就令人作呕，反华分子骗一骗低智商人群就算了，还想来这骗，随便查一查就知道说的有几句话是真的，弱智，naive idiot

你有本事就让GitHub把编程随想的这个仓库撤掉啊。另外government.github.com麻烦你自己去看一下。还有GitHub上面挺乌克兰挺巴勒斯坦的仓库还少吗？你用墙内的井底之蛙的视野来看墙外的GitHub，你自己墙内不能搞政治就认为GitHub也不应该用来搞政治，你不觉得你自己很荒唐可笑吗？

**Comment by posclegom** [comment]
> > > > > > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > > > > > 
> > > > > > 
> > > > > > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> > > > > 
> > > > > 
> > > > > 真的，在这里搞搞代码就可以了，天天在这里发泄不满搞政治何必呢。你看看你的repository里都是些啥😂
> > > > 
> > > > 
> > > > @Changgang-Zheng 因为这是墙外我们可以行使的言论自由。而且GitHub上面还有 government.github.com呢，你又作何解释？
> > > 
> > > 
> > > 笑死我了，还言论自由呢，你是指你美爹的双标自由？
> > 
> > 
> > @Atomadeus 你明知道我美爹的双标自由，还跑来使用我美爹的GitHub？你为何不滚回墙内去用你墙内的GitCafe/Gitee呢？
> 
> 瞎jb叫你妈，人狗粮给你了吗这就认爹了，我们爱用不用管你屁事，你美爹有本事把我们禁了啊傻逼

编程随想在GitHub上爱开不开仓库管你屁事，你共爹有本事把编程随想禁了啊傻逼

**Comment by posclegom** [comment]
> > > > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > > > 
> > > > 
> > > > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> > > 
> > > 
> > > 老哥我在uk。。。。你在哪？
> > > 别整的哪天这小站被block了何必呢。。。。。
> > 
> > 
> > @Changgang-Zheng 你在uk那就更加不怕GitHub被墙啦。而且到这个小站来的都是码农，需要查阅谷歌才能写码。码农如果连墙都不会翻的话，那还是不要做码农了。乘早卷铺盖走人。
> 
> 叫叫叫，你是码农吗，给几根骨头就作妖的狗罢了

我至少有几根骨头。你有什么呢？996.ICU？过劳死？

**Comment by kKXAXG7Ryx1** [comment]
> > > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > > 
> > > 
> > > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> > 
> > 
> > 老哥我在uk。。。。你在哪？
> > 别整的哪天这小站被block了何必呢。。。。。
> 
> @Changgang-Zheng 你在uk那就更加不怕GitHub被墙啦。而且到这个小站来的都是码农，需要查阅谷歌才能写码。码农如果连墙都不会翻的话，那还是不要做码农了。乘早卷铺盖走人。

哟哟哟，这么快就有优越感了！真可悲！！！

**Comment by AnnualfireCHW** [comment]
> > > > > > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> > > > > 
> > > > > 
> > > > > @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。
> > > > 
> > > > 
> > > > 真的，在这里搞搞代码就可以了，天天在这里发泄不满搞政治何必呢。你看看你的repository里都是些啥😂
> > > 
> > > 
> > > @Changgang-Zheng 因为这是墙外我们可以行使的言论自由。而且GitHub上面还有 government.github.com呢，你又作何解释？
> > 
> > 
> > 笑死我了，还言论自由呢，你是指你美爹的双标自由？
> 
> @Atomadeus 你明知道我美爹的双标自由，还跑来使用我美爹的GitHub？你为何不滚回墙内去用你墙内的GitCafe/Gitee呢？

GitHub根本不属于任何一个国家，只不过它的总部在美国。作为全球最大的开源社区。能不能别搞那些政治东西？要烦死了，防火墙就是拦住某些不用大脑独立思考的人。

**Comment by AnnualfireCHW** [comment]
> > Github 已经被有些人用于政治了。。 为啥不出个举报功能啊
> 
> 有举报功能啊。 你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。 另外欢迎你去举报这个仓库。 举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。

程序员网站搞这些乱七八糟没有用的，你有本事去外面什么推特还有什么油管上去，开源网站上发这玩意儿，脑子的确不正常，而且你在墙外有优越感了，墙的是你们这些没有脑子的吧🤣

**Comment by 2315506431** [comment]
> > Github 已经被有些人用于政治了。。为啥不出个举报功能啊
> 
> @Changgang-Zheng 有举报功能啊。你自己读不懂英文，看不懂"Report"这个字，就不要瞎怪GitHub。另外欢迎你去举报这个仓库。举报完了以后赶紧滚回你的墙内去用你的那个没有政治的GitCafe去，慢走不送。

Github墙内就能访问，望周知

**Comment by yuanpusheng** [comment]
这些美狗是真的烦
