### ISSUE TITLE
这是程序猿交流学习地方，无关政治

### ISSUE THREAD

**Issue by leijinjun** [programthink/zhao#272]
请不要利用这个地方来传播与技术交流学习无关的东西，不要污染这个纯净的地方，虽然说早已有很多不相关的东西出现在这里。不管你的内容是否正确，但是你的内容与技术交流毫无相关！

**Comment by fangqiangqiang007** [comment]
？？？？？？

**Comment by chinyichun** [comment]
> 请不要利用这个地方来传播与技术交流学习无关的东西，不要污染这个纯净的地方，虽然说早已有很多不相关的东西出现在这里。不管你的内容是否正确，但是你的内容与技术交流毫无相关！

@leijinjun 热烈欢迎你去GitHub举报本仓库以及 @programthink 。

**Comment by hilizx** [comment]
可以可以是这个理

**Comment by XiJingpingthePooh** [comment]
学你母亲的b有多深吗

**Comment by leijinjun** [comment]
> 学你母亲的b有多深吗

sb

**Comment by fangqiangqiang007** [comment]
学你母亲的b有多深吗

**Comment by hilizx** [comment]
这些网络喷子没有妈么,

**Comment by hilizx** [comment]
> 学你母亲的b有多深吗
傻逼玩意出来丢人现眼

**Comment by hilizx** [comment]
> 学你母亲的b有多深吗

傻逼玩意出来丢人现眼

**Comment by haohaoh4** [comment]
github觉得可以放什么就可以放什么，比如你在github上可以合作写小说。还有爆照项目，是否也不能放？

**Comment by soulofc** [comment]
对有些人: 你不想看, repo主没有求着你关注阿, 自己腆着脸进来还比比划划, 看来你的目标不是不看,而是想封口,这德性就是宣传部手下的五毛.



在 2020-03-21 14:20:14，"haohaoh4" <notifications@github.com> 写道：

github觉得可以放什么就可以放什么，比如你在github上可以合作写小说。还有爆照项目，是否也不能放？
