### ISSUE TITLE
不是别人反对，在有情绪再不堪，你去换个地方啊，bbc,cnn，投稿啊，在这上面真的不大好，这就简单的编程社区。

### ISSUE THREAD

**Issue by yinft** [programthink/zhao#286]

**Comment by stevenchew83** [comment]
不如你换个地方吧

**Comment by yinft** [comment]
> 不如你换个地方吧

我可没闲功夫去搞些没用到玩意，再见了您勒

**Comment by chinyichun** [comment]
> > 不如你换个地方吧
> 
> 我可没闲功夫去搞些没用到玩意，再见了您勒

@yinft 那 @programthink 也没闲功夫去搞些没用到玩意，再见了您勒，赶紧滚出这个仓库，慢走不送。

**Comment by haohaoh4** [comment]
github觉得可以放什么就可以放什么，比如在github上合作写小说也是可以的。
