### ISSUE TITLE
CCP制裁开始了，是否考虑建个制裁实体/个人的repo？

### ISSUE THREAD

**Issue by ghost** [programthink/zhao#317]
目前制裁个人包括
- 被[ 香港人权与民主法](https://zh.wikipedia.org/wiki/%E9%A6%99%E6%B8%AF%E4%BA%BA%E6%AC%8A%E8%88%87%E6%B0%91%E4%B8%BB%E6%B3%95)制裁的个人
- [CCP 个人visa限制，名单还没出](https://twitter.com/SecPompeo/status/1276552627724181504?s=20)

制裁实体
- [8家大外宣机构](https://www.state.gov/designation-of-additional-chinese-media-entities-as-foreign-missions/)
- Huawei

以及未来更多

**Comment by dyyhf123** [comment]
美国通过了 适用于 中国香港地区的 《香港人权与民主法案》 还好意思嚷嚷着民主自由，那其他国家是不是也应该通过一个 《美国黑人生命权法案》？？？就世界流氓罢了，自己退出了伊核协议之后，却又反过来对伊核协议指指点点，没见过这么不要脸的，至少遮一下啊，别“自由”的这么直接好吗？？当年对付伊拉克也是所谓的人权问题，看看现在的伊拉克人民都被美国祸害成什么样子了？一包洗衣粉就可以发动一场战争，战争打完以后，那包洗衣粉解释过吗？赤裸裸的侵略行为，说到底，人权有没有不重要，大规模杀伤性洗衣粉有没有也不重要，但是那里油石倒是有很多。

**Comment by chinyichun** [comment]
> 美国通过了 适用于 中国香港地区的 《香港人权与民主法案》 还好意思嚷嚷着民主自由，那其他国家是不是也应该通过一个 《美国黑人生命权法案》？？？就世界流氓罢了，自己退出了伊核协议之后，却又反过来对伊核协议指指点点，没见过这么不要脸的，至少遮一下啊，别“自由”的这么直接好吗？？当年对付伊拉克也是所谓的人权问题，看看现在的伊拉克人民都被美国祸害成什么样子了？一包洗衣粉就可以发动一场战争，战争打完以后，那包洗衣粉解释过吗？赤裸裸的侵略行为，说到底，人权有没有不重要，大规模杀伤性洗衣粉有没有也不重要，但是那里油石倒是有很多。

@dyyhf123 你翻墙到这儿来，派出所知道吗？还不赶快滚回你的墙内？

**Comment by GaryYufei** [comment]
> > 美国通过了 适用于 中国香港地区的 《香港人权与民主法案》 还好意思嚷嚷着民主自由，那其他国家是不是也应该通过一个 《美国黑人生命权法案》？？？就世界流氓罢了，自己退出了伊核协议之后，却又反过来对伊核协议指指点点，没见过这么不要脸的，至少遮一下啊，别“自由”的这么直接好吗？？当年对付伊拉克也是所谓的人权问题，看看现在的伊拉克人民都被美国祸害成什么样子了？一包洗衣粉就可以发动一场战争，战争打完以后，那包洗衣粉解释过吗？赤裸裸的侵略行为，说到底，人权有没有不重要，大规模杀伤性洗衣粉有没有也不重要，但是那里油石倒是有很多。
> 
> @dyyhf123 你翻墙到这儿来，派出所知道吗？还不赶快滚回你的墙内？

@chinyichun 其实认真读一下您和 @dyyhf123 的说法，都是想说明一个道理：自己国家都做不到的事，别叫别人做。美国不保护黑人的人权，那么有什么资格来香港叫嚣呢？同理，中共也没什么人权，那么也没什么资格批评美国，对吧？

**Comment by chinyichun** [comment]
> @chinyichun 其实认真读一下您和 @dyyhf123 的说法，都是想说明一个道理：自己国家都做不到的事，别叫别人做。美国不保护黑人的人权，那么有什么资格来香港叫嚣呢？同理，中共也没什么人权，那么也没什么资格批评美国，对吧？

@GaryYufei 这句话我同意你。我已经为你的原话点了赞。

**Comment by dyyhf123** [comment]
> > 美国通过了 适用于 中国香港地区的 《香港人权与民主法案》 还好意思嚷嚷着民主自由，那其他国家是不是也应该通过一个 《美国黑人生命权法案》？？？就世界流氓罢了，自己退出了伊核协议之后，却又反过来对伊核协议指指点点，没见过这么不要脸的，至少遮一下啊，别“自由”的这么直接好吗？？当年对付伊拉克也是所谓的人权问题，看看现在的伊拉克人民都被美国祸害成什么样子了？一包洗衣粉就可以发动一场战争，战争打完以后，那包洗衣粉解释过吗？赤裸裸的侵略行为，说到底，人权有没有不重要，大规模杀伤性洗衣粉有没有也不重要，但是那里油石倒是有很多。
> 
> @dyyhf123 你翻墙到这儿来，派出所知道吗？还不赶快滚回你的墙内？

   @GaryYufei 标榜人权和自由的香蕉人，还不允许别人发表看法吗？若是想讨论问题，最起码不要张口喷粪，你这用中文全世界喷粪，侮辱的可不止是中国，还有你的祖宗啊。

**Comment by chinyichun** [comment]
> > > 美国通过了 适用于 中国香港地区的 《香港人权与民主法案》 还好意思嚷嚷着民主自由，那其他国家是不是也应该通过一个 《美国黑人生命权法案》？？？就世界流氓罢了，自己退出了伊核协议之后，却又反过来对伊核协议指指点点，没见过这么不要脸的，至少遮一下啊，别“自由”的这么直接好吗？？当年对付伊拉克也是所谓的人权问题，看看现在的伊拉克人民都被美国祸害成什么样子了？一包洗衣粉就可以发动一场战争，战争打完以后，那包洗衣粉解释过吗？赤裸裸的侵略行为，说到底，人权有没有不重要，大规模杀伤性洗衣粉有没有也不重要，但是那里油石倒是有很多。
> > 
> > 
> > @dyyhf123 你翻墙到这儿来，派出所知道吗？还不赶快滚回你的墙内？
> 
> @GaryYufei 标榜人权和自由的香蕉人，还不允许别人发表看法吗？若是想讨论问题，最起码不要张口喷粪，你这用中文全世界喷粪，侮辱的可不止是中国，还有你的祖宗啊。

@dyyhf123 怎么，戳到你的痛处了？墙没得洗吧。

**Comment by GaryYufei** [comment]
> > > 美国通过了 适用于 中国香港地区的 《香港人权与民主法案》 还好意思嚷嚷着民主自由，那其他国家是不是也应该通过一个 《美国黑人生命权法案》？？？就世界流氓罢了，自己退出了伊核协议之后，却又反过来对伊核协议指指点点，没见过这么不要脸的，至少遮一下啊，别“自由”的这么直接好吗？？当年对付伊拉克也是所谓的人权问题，看看现在的伊拉克人民都被美国祸害成什么样子了？一包洗衣粉就可以发动一场战争，战争打完以后，那包洗衣粉解释过吗？赤裸裸的侵略行为，说到底，人权有没有不重要，大规模杀伤性洗衣粉有没有也不重要，但是那里油石倒是有很多。
> > 
> > 
> > @dyyhf123 你翻墙到这儿来，派出所知道吗？还不赶快滚回你的墙内？
> 
> @GaryYufei 标榜人权和自由的香蕉人，还不允许别人发表看法吗？若是想讨论问题，最起码不要张口喷粪，你这用中文全世界喷粪，侮辱的可不止是中国，还有你的祖宗啊。

我这话的语气可能有点问题，但我必须声明，我跟你是友军。我在不同话题底下都跟 @chinyichun 怼过。我认为大国之间其实没什么道德可言，都是利益，所以只要大家别美化美国政府的行径就可以了（因为绝大部分反华人士对中国政府都是做最坏的揣测），起码我们可以在一个出发点讨论问题。

**Comment by dyyhf123** [comment]
> > > > 美国通过了 适用于 中国香港地区的 《香港人权与民主法案》 还好意思嚷嚷着民主自由，那其他国家是不是也应该通过一个 《美国黑人生命权法案》？？？就世界流氓罢了，自己退出了伊核协议之后，却又反过来对伊核协议指指点点，没见过这么不要脸的，至少遮一下啊，别“自由”的这么直接好吗？？当年对付伊拉克也是所谓的人权问题，看看现在的伊拉克人民都被美国祸害成什么样子了？一包洗衣粉就可以发动一场战争，战争打完以后，那包洗衣粉解释过吗？赤裸裸的侵略行为，说到底，人权有没有不重要，大规模杀伤性洗衣粉有没有也不重要，但是那里油石倒是有很多。
> > > 
> > > 
> > > @dyyhf123 你翻墙到这儿来，派出所知道吗？还不赶快滚回你的墙内？
> > 
> > 
> > @GaryYufei 标榜人权和自由的香蕉人，还不允许别人发表看法吗？若是想讨论问题，最起码不要张口喷粪，你这用中文全世界喷粪，侮辱的可不止是中国，还有你的祖宗啊。
> 
> @dyyhf123 怎么，戳到你的痛处了？墙没得洗吧。

@chinyichun 我有什么痛点？中国能上国际互联网的人多了，真不像你想的那样子会因为单纯的上网被抓。存在既有理，你针具的中共真的像那些西方媒体说的能靠骗、靠洗脑控制14亿人？中共搞新疆种族灭绝导致维吾尔族人从200万增长到了2000万，美国靠人权，印第安人从3000万人发展到现在的100万人？反华不要反智，会让人觉得好笑。

**Comment by chinyichun** [comment]
> > > > > 美国通过了 适用于 中国香港地区的 《香港人权与民主法案》 还好意思嚷嚷着民主自由，那其他国家是不是也应该通过一个 《美国黑人生命权法案》？？？就世界流氓罢了，自己退出了伊核协议之后，却又反过来对伊核协议指指点点，没见过这么不要脸的，至少遮一下啊，别“自由”的这么直接好吗？？当年对付伊拉克也是所谓的人权问题，看看现在的伊拉克人民都被美国祸害成什么样子了？一包洗衣粉就可以发动一场战争，战争打完以后，那包洗衣粉解释过吗？赤裸裸的侵略行为，说到底，人权有没有不重要，大规模杀伤性洗衣粉有没有也不重要，但是那里油石倒是有很多。
> > > > 
> > > > 
> > > > @dyyhf123 你翻墙到这儿来，派出所知道吗？还不赶快滚回你的墙内？
> > > 
> > > 
> > > @GaryYufei 标榜人权和自由的香蕉人，还不允许别人发表看法吗？若是想讨论问题，最起码不要张口喷粪，你这用中文全世界喷粪，侮辱的可不止是中国，还有你的祖宗啊。
> > 
> > 
> > @dyyhf123 怎么，戳到你的痛处了？墙没得洗吧。
> 
> @chinyichun 我有什么痛点？中国能上国际互联网的人多了，真不像你想的那样子会因为单纯的上网被抓。存在既有理，你针具的中共真的像那些西方媒体说的能靠骗、靠洗脑控制14亿人？中共搞新疆种族灭绝导致维吾尔族人从200万增长到了2000万，美国靠人权，印第安人从3000万人发展到现在的100万人？反华不要反智，会让人觉得好笑。

@dyyhf123 见下图，有没有感觉被打脸啪啪的响？

![fanqiang](https://user-images.githubusercontent.com/47834434/109249577-f51c7180-77b5-11eb-9763-fb085d3e33ad.jpg)

**Comment by chinyichun** [comment]
> > > > 美国通过了 适用于 中国香港地区的 《香港人权与民主法案》 还好意思嚷嚷着民主自由，那其他国家是不是也应该通过一个 《美国黑人生命权法案》？？？就世界流氓罢了，自己退出了伊核协议之后，却又反过来对伊核协议指指点点，没见过这么不要脸的，至少遮一下啊，别“自由”的这么直接好吗？？当年对付伊拉克也是所谓的人权问题，看看现在的伊拉克人民都被美国祸害成什么样子了？一包洗衣粉就可以发动一场战争，战争打完以后，那包洗衣粉解释过吗？赤裸裸的侵略行为，说到底，人权有没有不重要，大规模杀伤性洗衣粉有没有也不重要，但是那里油石倒是有很多。
> > > 
> > > 
> > > @dyyhf123 你翻墙到这儿来，派出所知道吗？还不赶快滚回你的墙内？
> > 
> > 
> > @GaryYufei 标榜人权和自由的香蕉人，还不允许别人发表看法吗？若是想讨论问题，最起码不要张口喷粪，你这用中文全世界喷粪，侮辱的可不止是中国，还有你的祖宗啊。
> 
> 我这话的语气可能有点问题，但我必须声明，我跟你是友军。我在不同话题底下都跟 @chinyichun 怼过。我认为大国之间其实没什么道德可言，都是利益，所以只要大家别美化美国政府的行径就可以了（因为绝大部分反华人士对中国政府都是做最坏的揣测），起码我们可以在一个出发点讨论问题。

@GaryYufei 我还以为 @dyyhf123 在喷我，只不过他手滑了，错误的@了你。

“我认为大国之间其实没什么道德可言，都是利益” -- 这点我也同意，但是近代以后对本国国民犯下文革和60年饿死三千万这种罪行的，恐怕全球不出中共其二了（当然还有赤柬，苏联，北韩，前两个现在已经被灭了）

"只要大家别美化美国政府的行径就可以了" -- 我没有美化美国政府，天下乌鸦一般黑，但是的确中共政府比其它政府更烂而已。
