### ISSUE TITLE
Unusual Features of the SARS-CoV-2 Genome Suggesting Sophisticated Laboratory Modification Rather Than Natural Evolution and Delineation  of Its Probable Synthetic Route

### ISSUE THREAD

**Issue by gogobook** [programthink/zhao#321]
紀錄一下，從香港WHO逃到美國的閆博士，今天正式提出武漢肺炎病毒SARS-COV-2為實驗室製造的人工病毒的證據。
閆博士這篇論文論證的基礎主要建立在，拿武漢肺炎病毒SARS-CoV-2的序列，與中共宣稱自然演化成武漢肺炎病毒的ZC45/ZXC21相比
1. SARS-CoV-2對比ZC45/ZXC21，Orf8基因序列重複性高達94.2%，與構成病毒外殼的E Protein基因序列則是100%相同，這在自然界中是完全不可能發生的，原因如下：
在類SARS病毒的族群中，只要變異，較不重要的基因序列Orf8的相似度最高是58%，而E protein最高的相似度是83%，現在SARS-COV-2的相似度居然是94.2%/100%，很明顯是從ZC45/ZXC21基因工程而來
2. SARS-COV-2主要致病的Spike protein，雖然相似度只有69%。
但，其中有一段被稱作RBM的蛋白，被完整保留，根本copy & paste，其它的部分卻有略為變異，這種變異在自然界是完全不可能發生的，而且RBM的兩端點剛好對應常見的基因修剪蛋白序列，「正好是石正麗在2008論文中展示過的修剪點位」、「顯示RBM基因序列是被換上的」
3. SARS-COV-2的Spike protein，在S1蛋白與S2蛋白接合處，有beta-SARS系列病毒完全沒有的弗林蛋白酶(Furin cleavage site)，這大大強化了SARS-COV-2感染人類細胞的能力。
而SARS-COV-2如果要自然演化出弗林蛋白酶，唯一有可能的情況是beta-SARS系列病毒曾有祖代與其它冠狀病毒交換基因，但在現有的所有beta-SARS族系中，從未有其它親戚具有弗林蛋白酶的基因序列。
另外，出現在SARS-COV-2的弗林蛋白酶序列為-PRRAR/SVA-，正好與石正麗在2017年發表的另一個AcCoV-JC34，所具有的-RRAR/AR序列相似。
剩下的部分就是如何在實驗室中製造SARS-COV-2，這部分我就不翻了免得造成困擾。

論文的連結:https://drive.google.com/file/d/18-eIJJ2mn0VDJ2SIzMU0PqbdHqwZH1CA/view

**Comment by gogobook** [comment]
在沒有更進一步的訊息前，暫時關閉。

**Comment by chinyichun** [comment]
@gogobook 你是怎么看的，这是真的还是假的？

**Comment by JochenToebe** [comment]
Is this article of Li-Meng yang available in German?

**Comment by tonyqus** [comment]
谁是生物专业的，给评估下，我完全没看懂，哈哈哈。
