### ISSUE TITLE
只是屏蔽了大陆的ip，并没有什么卵用。

### ISSUE THREAD

**Issue by ghost** [programthink/zhao#325]

**Comment by tonyqus** [comment]
还是有用的，只要墙内不能访问，github就不会被GFW Canon攻击

**Comment by chinyichun** [comment]
> 还是有用的，只要墙内不能访问，github就不会被GFW Canon攻击

@tonyqus 不太懂这个逻辑，github不是因为被GFW Canon攻击才把这个仓库屏蔽了大陆的IP，而是应中国政府要求把这个仓库屏蔽了大陆的IP。
