### ISSUE TITLE
打扰下各位,  我实在忍不住想督促某同学提高一下知识水平.

### ISSUE THREAD

**Issue by cupen** [programthink/zhao#326]
实不相瞒, 在下对编程随想前辈是抱持不少敬意的, 无论专业水平还是家国情怀.

只是 @gogobook 这位同学. 你好, 我不想得罪你, 但你在 issues 里的言行格调实在有必要提升一下, 否则在下很难不怀疑你是不是党国派来拆台的.

有空会来这里逛逛的国人多少都了解一些古今中外历史, 能读到世界新闻, 也很能想明白很多道理比如人性其实都差不多, 无论国家, 民族, 乃至人种. 但你和你的同道们来来去去就是些"不xx就是yy", "不xx你就应该xx啊"这种非黑即白言论, 有一丝可讨论的价值吗? 除了吸引一些不擅辩论的笨蛋们跑来掐口水架之外有什么意义? 

#314  看看你这个,  故事邪门, 我没能力证实或证伪, 但现在的文明社会下, 无论在哪里发生这种烂事都会引起一定社会反应.  怎么给你说得像是我们这很享受似的, 你要是这么认为那就太遗憾了. 难道不信教的社会没好人么? 信教的社会里就没坏人么?  我觉得无论是否信教, 无论哪个社会, 都不至于脆弱到连故事中那种烂事都视而不见的地步. 而关于国人的心性如何, 我认为跟世界各地的人没啥两样, 都有好和不好. 所以 ... 你到底是认真的还是假装的?

再者. 如果你想惩戒故事中的坏人, 那你该做什么? 而你实际在做什么? 以鄙人之见, 故事的真实性和你的言行有些"相映成趣".

关于李医生, 他是吹哨人之一, 我们普遍都认为 zf 欠他一个公道, 国内社会公论如此.  而你用李医生的遭遇来支撑你的政治诉求是否有吃人血馒头之嫌? 如果你还尊重李医生, 就不要把他关联到你的政治观点上, 不是你不配, 是政治不配, 全宇宙的政治都不配.  所以你以后再引用李医生, 不妨从医生或吹哨人的角度来谈, 他不是你们的同道, 是我们的. 

最后, 我们其实相当乐意看到黑料, 因为那里边包含一些真实, 哪怕是血淋淋的真实.  所以你不妨磊落点,有什么政治诉求或者隐秘见闻但说无妨, 多爆黑料多吹弊端,  别整些没用的.  更别复制粘贴那几坨轮子新闻糊弄人, 没有赵家人自有别家人, 全世界都是这尿性. 所以问题在哪? 宇宙中存在真理么? 那么多世界级大哲究其一生都无法得窥, 怎么到你这啥事都有定论了? 你要真有两把刷子,为何不干点正经事? 就像编程随想前辈做的那样,
.
抱歉, 请恕我说了这么多疯话. 只因我不想再默默忍受你拆编程随想的台.

以上.

**Comment by chenli523** [comment]
赞👍

**Comment by gogobook** [comment]
不懂什麼是zf ，可以說一下嗎? 至於李醫生的事，你們連公道都要不到了，又怎麼能阻止我要拿他來支持我的政治訴求呢? 他和其他因為肺炎而死的人，難道這筆帳算不到共產黨頭上嗎? 難道不能訴求打倒共產黨，難道不是因為共產黨隱瞞了肺炎的消息，而害死了這多的人嗎? 我的政治訴求就是打倒共產黨，因為共產黨反人性。#314 是我貼來的傳聞，這因為我相信共產黨治下的中國是有可能發生這種事的，@cupen 你覺得這完全不可能發生嗎? 中國太大，太多人是靠著關係在做事，共產黨基本上不守法律，基本上，什麼事都共產黨說了算。

**Comment by foxjie** [comment]
水平确实有待提高。。。我真觉得gogobook是来反向操作的。。。尤其是在现在这个大环境下，他的某些言论真的帮了party不少忙。。

**Comment by TONGlong520** [comment]
捡到宝了

**Comment by RunNorthenEurope** [comment]
什么蛤丝

**Comment by liu89501** [comment]
2021年了 问题越来越明显了 啥时候也弄点64那样的事啊

**Comment by wr131** [comment]
> 水平确实有待提高。。。我真觉得gogobook是来反向操作的。。。尤其是在现在这个大环境下，他的某些言论真的帮了party不少忙。。

party的"p"应该大写，“Party”才有政党的意思。。。。。。。
