### ISSUE TITLE
强烈要求关掉，不要祸害我们的github

### ISSUE THREAD

**Issue by gxlmyacc** [programthink/zhao#34]
强烈要求关掉，不要祸害我们的github! 你所说这些权威媒体都是国外的，难道他们还会安好心？

**Comment by posclegom** [comment]
只要不是违反GitHub的ToS的内容都可以放在GitHub上，楼主不要做精赵，不要自我阉割，不要做奴才。楼主也配姓赵？！

**Comment by gxlmyacc** [comment]
如果没有墙，百度、腾讯、滴滴、人人等这些互联网企业能发展起来吗？如果没有墙，互联网将米国一家独大，米国gov不需出门即可发动对别国的舆论战？这样好吗？

**Comment by zjw88282740** [comment]
这么说楼上这位还支持墙咯  果然是中毒不浅啊

**Comment by zjw88282740** [comment]
gxlmyacc 祸害我们github 不知道这里的“我们”指的是什么，是不懂反抗软弱无能的人吗

**Comment by gxlmyacc** [comment]
你说我们中毒不浅，我们看你何尝也不是中毒呢

**Comment by zjw88282740** [comment]
如果没有墙，百度、腾讯、滴滴、人人等这些互联网企业难道就不能发展起来？难道我国企业一定要墙才能发展吗？如果不能，理应被淘汰

**Comment by gxlmyacc** [comment]
照你这样说，何必要保护民主企业，何必要关税？米国为什么要禁止采购华为、联想的东西？

**Comment by zjw88282740** [comment]
一定要墙才能保护吗，我们也可以只采购华为、联想的东西啊，我并不反对正常的保护措施

**Comment by gxlmyacc** [comment]
但不可否则，墙起到了很大作用，君不见互联网大企业除了米国就赵国最多了，难道其他国家都是吃干饭的？

**Comment by zjw88282740** [comment]
我不否认墙起到贸易保护的作用，但这是以自由为代价获得的，国家要封杀facebook，google那就要有法律依据和证据。

**Comment by simonasd** [comment]
如果没有墙，这些流氓就不会发展起来。说得很对。

**Comment by gxlmyacc** [comment]
国家也没有禁止它们来，只要遵守国家法律即可，还有把服务器放在赵国，以前这些大公司是坚决不会与赵国谈判的，现在也开始慢慢接受了，它们迟早回来赵国的，这个我敢跟你打赌^_^

**Comment by Cavolo** [comment]
Github怎么block人啊，求告知

**Comment by gaocegege** [comment]
re @Cavolo 没有这个设定

**Comment by HyXieS** [comment]
国外媒体不安好心--典型的美帝阴谋论。国内的媒体就是安好心啊？天天歌功颂德，恶不恶心。捧杀知道嘛。国外媒体不少说咱好话的，不要被国内洗脑了。

没有墙，国内的互联网企业发展不起来--阿里巴巴打败ebay，Amazon也没有被墙；腾讯打败msn，whatsapp也打不过微信；Uber也没有被墙吧，打不过滴滴；至于百度，本土化做得很好，谷歌就算进来也不一定打得赢；华为呢，中国也没有把思科禁了吧；所以嘛，你这言论就是典型的智障型言论。

还有啊，美国的媒体不是政府控制的，政府是无权干涉媒体的新闻自由的；媒体是由资本控制的，但是资本派别很多啊，基本不会出现统一的口径，至于某国，媒体都姓党，这舆论战打起来，谁的战斗力更强？

我觉得你这种人啊，简直就是程序员中的败类。
真的，智商感人。

**Comment by gxlmyacc** [comment]
楼上的你他妈才是败类，国内媒体有败类，这我不否认，但国外媒体是要你命的，才100年前的事情你就忘了！你还认贼做父，你不仅是败类，而且还是贱货！
美国媒体不受政府控制，大哥，想想，你看看美国多少所谓的民主基金会有政府背景，你看看有多少媒体背后有这些基金会的支持？你看看苏联的解体没有这些你们所谓自由的媒体的支持？你看看事后美国政府是怎么说的。

**Comment by Cavolo** [comment]
谁素质低下看谁气急败坏了就行，精赵的素质还需要提升啊

**Comment by gxlmyacc** [comment]
大哥，是你先骂人的好不好！我对什么人说什么话！

**Comment by wikimore** [comment]
自我阉割的LZ

**Comment by wikimore** [comment]
我觉得LZ可以用gitcafe或者osc的git，要大力支持民族企业。

**Comment by killxjp** [comment]
LZ，https://coding.net 歡迎你。沒必要來Github啊。

**Comment by quirkaddr** [comment]
> 强烈要求关掉，不要祸害我们的github! 你所说这些权威媒体都是国外的，难道他们还会安好心？

强烈要求你删除Github帐号, Github是国外的, 难道还会安好心?
