### ISSUE TITLE
差不多得了，爬

### ISSUE THREAD

**Issue by Stevepyl** [programthink/zhao#347]
差不多得了😅😅😅😅😅，GitHub是你发这种无聊东西的是吧，自我陶醉也就得了，像宁这号的抓进去又是一个对着镜头痛哭流涕的小丑。

**Comment by Stevepyl** [comment]
已举报

**Comment by posclegom** [comment]
@Stevepyl 举报了这么多次，这个repo还在这儿。有意思吗？

**Comment by derrickmehaffy** [comment]
.

**Comment by neozhu** [comment]
人家肯定全家都在国外，公安抓不到。来这里评论的反而要小心。

**Comment by posclegom** [comment]
@neozhu 除非Github员工被共产党买通导致用户信息外泄，否则来这里评论也是安全的。实在不放心就使用Tor浏览器来此留言。

**Comment by Stevepyl** [comment]
> 差不多得了😅😅😅😅😅，GitHub是你发这种无聊东西的是吧，自我陶醉也就得了，像宁这号的抓进去又是一个对着镜头痛哭流涕的小丑。

**Comment by Dlyoungml** [comment]
笑死，在GitHub上还想通过举报来掩盖你主子的事实吗？狗屁不如的奴才软骨头，看到你主子的关系网比死了亲妈还急，呵呵！
