### ISSUE TITLE
d

### ISSUE THREAD

**Issue by obweix** [programthink/zhao#349]

**Comment by posclegom** [comment]
@obweix 要用Git回到墙内去用GitCafe，不要来GitHub，好吗？

**Comment by cangjietai** [comment]
> @obweix 要用Git回到墙内去用GitCafe，不要来GitHub，好吗？

你他媽算個什麽東西，儅自己是Linus啊？github你家開的啊？我看你真的是有共產黨的資質呢，獨斷專權，幸好你只是個廢物，什麽都做不了，0star，0following,你來這就不是搞技術，而是爲了搞事情，1450真的是該死🤏🤏🤏🤏🤏

**Comment by SkyGrass** [comment]
> @obweix 要用Git回到墙内去用GitCafe，不要来GitHub，好吗？

打着正义高光的旗号，干着偷鸡摸狗的事情

**Comment by daringyun** [comment]
> @obweix 要用Git回到墙内去用GitCafe，不要来GitHub，好吗？

github是你家开的吗,爱在点哪点哪，爱看啥看啥，想说啥就说啥
