### ISSUE TITLE
闷声作大死，要玩特么去别的地方玩啊

### ISSUE THREAD

**Issue by shaoyuan1943** [programthink/zhao#35]
0.0

**Comment by shaoyuan1943** [comment]
。。。。。。

**Comment by posclegom** [comment]
只要不是违反GitHub的ToS的内容都可以放在GitHub上，楼主不要做精赵，不要自我阉割，不要做奴才。GitHub被墙请找赵家人解决。

**Comment by breaking-gfw** [comment]
往github的连接疯狂丢包，也不差翻墙那一步。

**Comment by posclegom** [comment]
@breaking-gfw exactly!

**Comment by chenjiaqiang** [comment]
被墙了就翻墙啊，不会翻墙说明只是个垃圾程序员。

**Comment by sunlianghua** [comment]
如果真的因为这个项目使 Github 被墙了，很明显是设墙的人有问题，而不是这个项目的问题。

**Comment by wangppp** [comment]
翻墙应该会吧。。

**Comment by itisbenjamin** [comment]
殺了人不怪殺人犯，倒怪起賣刀的了，那麼怕被牆，怎麼不建議Github直接關掉算了。

**Comment by CMB-news** [comment]
這裡向各位用戶稟報一下：推翻中共、顛覆中共偽政權，是所有中國人義不容辭的責任！新一代技術人員，特別是計算機軟件人員更應該作爲先鋒存在，而不是如一個頭腦麻木的豬狗般的奴才苟且活在世上。這與中共暴政是否封殺一個站點毫無關係。淪陷區的人民有權要求解放！如果你只是表達異議，沒有反對革命的行爲，那沒有什麽關係，我們支持言論自由，但是，對於那些阻礙革命的人、迫害民主人士的人、包括而不限於為中共充當奴犬的程序員、向中共偽政權當局通風報信、與共匪合作的技術人員，你們在以後的革命風暴中將被視之為敵人，將會被清除消滅！
