### ISSUE TITLE
无疑在趋势版看到，像吃了苍蝇一样恶心。

### ISSUE THREAD

**Issue by zwxf** [programthink/zhao#353]
`本项目上线第二天，就收获 363 个 star 兼 88 个 fork，甚至还挤进 GitHub 的“当日 Trending”——俺很荣幸，也很高兴有这么多人给俺捧场。`
这句话真是笑死人，你看看如果GitHub有举报功能，你这项目有多少人举报。
github是编程网站，为什么要把一锅汤里加老鼠屎呢，想发表政治言论请上twitter、facebook等任意其他网站，何必污染这个环境呢？

**Comment by TripsAc0912** [comment]
996.ICU也是GITHUB平台上的伟大项目之一，体现的是IT群体对劳动法执行不力的不满和对这个国家政治体制的失望，也是一种反抗行动，为什么你不去抨击那个项目呢？是因为你在其中获利了吗？

**Comment by zwxf** [comment]
> 
> 
> 996.ICU也是GITHUB平台上的伟大项目之一，体现的是IT群体对劳动法执行不力的不满和对这个国家政治体制的失望，也是一种反抗行动，为什么你不去抨击那个项目呢？是因为你在其中获利了吗？

为什么作为程序猿有如此低智的非黑即白的逻辑思维？我抨击此项目只是觉得这个项目除了阴谋论，发泄情绪外毫无作用，另外我周末无聊，逛逛趋势榜，学习看新技术，看到issue一堆恨国党，阴谋论很是恶心，
其次说下为何不抨击996ICU，有一些几个理由
1、我没在趋势榜看到，毕竟也没这么无聊，天天看
2、我认为996ICU项目是对资本的抨击，和这个项目有大不同
3、我不认同996ICU项目，github属于编程网站，不应该涉及政治
以上：
    如有不同观点，你是对的，请你以及其他人不要回复。这只是我个人的观点。

**Comment by TripsAc0912** [comment]
哈哈  你知道你的老大刘中东和教育部部长袁贵仁的关系吗  知道为何你们公司每年能承办全国职业技能大赛吗 了解上面两个你身边的例子，就了解这个赵家人项目的意义所在了

**Comment by zwxf** [comment]
> 
> 
> 哈哈 你知道你的老大刘中东和教育部部长袁贵仁的关系吗 知道为何你们公司每年能承办全国职业技能大赛吗 了解上面两个你身边的例子，就了解这个赵家人项目的意义所在了

额额额。。这位兄弟是否看不同中文？
```
以上：
如有不同观点，你是对的，请你以及其他人不要回复。这只是我个人的观点。
```
请勿回复，请勿回复，请勿回复。

**Comment by TripsAc0912** [comment]
完蛋了，这网站在国外了，你限制不了我的言论自由了:xD

**Comment by zwxf** [comment]
> 
> 
> 完蛋了，这网站在国外了，你限制不了我的言论自由了:xD

哈哈哈，我也是无聊。。。已经close了，还要出去吃烧烤了。。浪费时间了，继续享受你在网上的自由：）
