### ISSUE TITLE
参考“维基百科”以及一些国际权威媒体的报道 比如《纽约时报》，大哥你想把我笑死吗

### ISSUE THREAD

**Issue by Theon66** [programthink/zhao#354]
基于这些”权威媒体“总结的东西，能有什么价值？

记得以前有段时间在看《纽约时报》，这是一家什么样的权威媒体呢。
曾经刊登过一篇大肆报道宣传一部指控Michael Jackson娈童的所谓纪录片《Leaving Neverland》。
MJ是什么样的人我就不用多说了，这么多年了，MJ娈童案的真相也不用多说了。
我想说这家所谓的权威媒体，如此不尊重最基本的事实，对于这样一位可以称为伟大的美国人都能如此报道。
可以想象，对于美国认为的头号宿敌中国，他们会用多么权威多么真实的东西来描述中国呢。

哦对了，维基百科，那可太可靠了，那可是互联网上人人都能参与的协作项目呢。

**Comment by Dlyoungml** [comment]
我发现你们这些人都对issue盘点的赵家人的事实避而不谈，转而去攻击其他事物，你觉得这里关于赵家人的信息那点错了就说出来了，尽用些低级的洗地话术也挺搞笑的

**Comment by zhepama** [comment]
他们参考的还有BBC,大纪元.苹果毒报

**Comment by Theon66** [comment]
> 我发现你们这些人都对issue盘点的赵家人的事实避而不谈，转而去攻击其他事物，你觉得这里关于赵家人的信息那点错了就说出来了，尽用些低级的洗地话术也挺搞笑的

我没有指出这里赵家人信息哪里错了，因为我对这些”赵家人的事实“根本判断不了真伪。我根本没有任何可靠的渠道去获取这些信息。就好像你同样没有一样。
我仅仅只是指出根据不可靠的消息来源总结出来的”事实“是多么可笑。

**Comment by Dlyoungml** [comment]
> > 我发现你们这些人都对issue盘点的赵家人的事实避而不谈，转而去攻击其他事物，你觉得这里关于赵家人的信息那点错了就说出来了，尽用些低级的洗地话术也挺搞笑的
> 
> 
> 
> 我没有指出这里赵家人信息哪里错了，因为我对这些”赵家人的事实“根本判断不了真伪。我根本没有任何可靠的渠道去获取这些信息。就好像你同样没有一样。
> 
> 我仅仅只是指出根据不可靠的消息来源总结出来的”事实“是多么可笑。

 你又不知道我的身份和信息获取渠道，就别臆想了。说了半天你无法反驳赵家人关系，不抓住这个关键，就想转移话题，五毛自干五洗地老套路了。

**Comment by zhepama** [comment]
> 我发现你们这些人都对issue盘点的赵家人的事实避而不谈，转而去攻击其他事物，你觉得这里关于赵家人的信息那点错了就说出来了，尽用些低级的洗地话术也挺搞笑的

你是你妈和你爷爷生的..这是不可更改的事实.
我发现你对你爸不是你亲爸的事实避而不谈，转而去攻击其他事物，你觉得这里关于你不是你爸生的信息那点错了就说出来了，尽用些低级的洗地话术也挺搞笑的

你可以让你妈妈上github上来澄清下吗?

**Comment by posclegom** [comment]
@zhepama 你既然这么不喜欢这个仓库。那你就别来这里不就行了。GitHub上那么多根正苗红的仓库你不去，非要跑到这儿来，你不是犯贱嘛。

**Comment by posclegom** [comment]
> 哦对了，维基百科，那可太可靠了，那可是互联网上人人都能参与的协作项目呢。

@Theon66 哦对了，百度百科，那可太可靠了，那可是互联网上人人都能参与的协作项目呢。

**Comment by Theon66** [comment]
> > > 我发现你们这些人都对issue盘点的赵家人的事实避而不谈，转而去攻击其他事物，你觉得这里关于赵家人的信息那点错了就说出来了，尽用些低级的洗地话术也挺搞笑的
> > 
> > 
> > 我没有指出这里赵家人信息哪里错了，因为我对这些”赵家人的事实“根本判断不了真伪。我根本没有任何可靠的渠道去获取这些信息。就好像你同样没有一样。
> > 我仅仅只是指出根据不可靠的消息来源总结出来的”事实“是多么可笑。
> 
> 你又不知道我的身份和信息获取渠道，就别臆想了。说了半天你无法反驳赵家人关系，不抓住这个关键，就想转移话题，五毛自干五洗地老套路了。

你们这些人是真的喜欢给人扣帽子，我质疑一下这些消息来源的不可靠，就变成了五毛。
说我转移话题，你却对我质疑的东西没有一点正面的回答，质疑到了你这里就变成了攻击、洗地。不知道谁的言论看起来更像攻击和洗地。
甚至一来就让我证明车库里的龙并不存在。
看来你似乎觉得一个事物如果没有办法证伪，那么这个事物就是正确且真实存在的。
如果你觉得这个逻辑是正确的。
那我现在说你是一个低教育水平、社会地位低下并且缺乏独立思考能力的人，我说这是一个事实。
现在请你来证明你不是这样一个人，如果你证明不出来，那你就是这样一个人。

**Comment by zhepama** [comment]
> @zhepama 你既然这么不喜欢这个仓库。那你就别来这里不就行了。GitHub上那么多根正苗红的仓库你不去，非要跑到这儿来，你不是犯贱嘛。

@posclegom 
哦我可爱的自由民主..你这就不要我来这个地方了..
你们说好的言论自由呢?
你嘴里的言论自由,就是不让别人发表言论吗?

**Comment by Theon66** [comment]
> > 哦对了，维基百科，那可太可靠了，那可是互联网上人人都能参与的协作项目呢。
> 
> @Theon66 哦对了，百度百科，那可太可靠了，那可是互联网上人人都能参与的协作项目呢。

你对我说的有什么看法，就请直接正面回复。
我甚至连百度都不用，你搁这复制粘贴什么呢？
你觉得我质疑了美国媒体，那我就百分百相信国内媒体。
可是我不是这么非黑即白的，这个世界也从来就不是非黑即白的。
你觉得你这样的二极管思维，真的能大谈政治，真的能客观理性地看待任何事物吗？

**Comment by posclegom** [comment]
> > > 哦对了，维基百科，那可太可靠了，那可是互联网上人人都能参与的协作项目呢。
> > 
> > 
> > @Theon66 哦对了，百度百科，那可太可靠了，那可是互联网上人人都能参与的协作项目呢。
> 
> 你对我说的有什么看法，就请直接正面回复。
> 我甚至连百度都不用，你搁这复制粘贴什么呢？
> 你觉得我质疑了美国媒体，那我就百分百相信国内媒体。
> 可是我不是这么非黑即白的，这个世界也从来就不是非黑即白的。
> 你觉得你这样的二极管思维，真的能大谈政治，真的能客观理性地看待任何事物吗？

@Theon66 okay，那就行了。我并不了解你。既然你这么说，那我觉得你和现在突然出现洗版的五毛不是一路人。这个仓库鱼龙混杂。我不和你交谈不可能了解你的思维是什么样的。
