### ISSUE TITLE
LOL, What a poor TaiwanFrogsssssssssssssssssssssssss🤣 

### ISSUE THREAD

**Issue by Awesom1-Tech** [programthink/zhao#361]
Poor Taiwan frogs can only make rumors in this way. 
However, the fact is that when Taiwan frogs have no electricity, they need to use love to generate electricity and accept the thief as their father. 
IT'S still very happy to get the vaccine that the Japs don't want.  Shame on TaiwanFrogs🐸 , :)  
Now 76 people have died in five days, and they have to continue to get the vaccine from Japs. 

what a pathetic! LOL!!!!!!!!!!! 😆 

🤣 To tell you the truth, if the author has the energy to do this, Taiwan can send more electricity 🤣 
🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸

**Comment by asdf130162** [comment]
他们只向往 “自由民主”，做美帝国主义的🐶狗都不配🤣。用发展中国家的人均标榜吸血全世界的发达国间的人均，笑死。标榜所谓的 “独立思考” 实际上是引入他们的逻辑陷阱，这群人非蠢即坏。但凡读读近代史都知道现在生活来之不易，也就是和肉蛋奶一样恰烂钱的臭🐶

**Comment by posclegom** [comment]
@Awesom1-Tech China has been threatening to take over Taiwan by force for 71 years, and I think China will continue to threaten to take over Taiwan by force for another 71 years. Why don't you tell your commie masters to invade Taiwan? Oh wait, you are just some loser in China whose money has been taken away by your commie masters.

Oh and by the way, China's vaccines suck! That's why Taiwan don't want them.

**Comment by posclegom** [comment]
> 他们只向往 “自由民主”，做美帝国主义的🐶狗都不配🤣。用发展中国家的人均标榜吸血全世界的发达国间的人均，笑死。标榜所谓的 “独立思考” 实际上是引入他们的逻辑陷阱，这群人非蠢即坏。但凡读读近代史都知道现在生活来之不易，也就是和肉蛋奶一样恰烂钱的臭🐶

@adsf130162 那你还来美帝国主义的网站干嘛？还不赶快回到你的墙里面去使用你的GitCafe？

**Comment by asdf130162** [comment]
> > 他们只向“自由民主”，做美帝国主义的🐶狗不配🤣。用精的这点小标榜吸食，笑。标榜榜首的“独立思考幼年”是引入的逻辑，陷阱这群人蠢蠢欲动。但即坏即读读近代史。都知道现在生活来之不易，也就是和肉奶蛋恰烂钱的臭🐶
> 
> @ad130162那你还来美帝国主义的网站吗？还能回到你的墙里面去你的GitCafe吗？

来了就对线的，你没有🧠汁？

**Comment by posclegom** [comment]
> > > 他们只向“自由民主”，做美帝国主义的🐶狗不配🤣。用精的这点小标榜吸食，笑。标榜榜首的“独立思考幼年”是引入的逻辑，陷阱这群人蠢蠢欲动。但即坏即读读近代史。都知道现在生活来之不易，也就是和肉奶蛋恰烂钱的臭🐶
> > 
> > 
> > @ad130162那你还来美帝国主义的网站吗？还能回到你的墙里面去你的GitCafe吗？
> 
> 来了就对线的，你没有🧠汁？

我有说错了什么吗？GitHub难道不是美帝国主义的网站吗？

**Comment by zhepama** [comment]
> > > > 他们只向“自由民主”，做美帝国主义的🐶狗不配🤣。用精的这点小标榜吸食，笑。标榜榜首的“独立思考幼年”是引入的逻辑，陷阱这群人蠢蠢欲动。但即坏即读读近代史。都知道现在生活来之不易，也就是和肉奶蛋恰烂钱的臭🐶
> > > 
> > > 
> > > @ad130162那你还来美帝国主义的网站吗？还能回到你的墙里面去你的GitCafe吗？
> > 
> > 
> > 来了就对线的，你没有🧠汁？
> 
> 我有说错了什么吗？GitHub难道不是美帝国主义的网站吗？

@posclegom 
美帝国主义的网站,我们就不能来了?
说好的言论自由呢?
被你吃到狗肚子里了?

**Comment by posclegom** [comment]
> 美帝国主义的网站,我们就不能来了?

@zhepama 按照中华人民共和国相关法律法规。你们还真就不能来。

**Comment by iamazy** [comment]
> > 美帝国主义的网站,我们就不能来了?
> 
> @zhepama 按照中华人民共和国相关法律法规。你们还真就不能来。
> 

@posclegom 又来又来，哪个法律法规列出来，别总是含糊其辞却煞有其事

**Comment by posclegom** [comment]
> > > 美帝国主义的网站,我们就不能来了?
> > 
> > 
> > @zhepama 按照中华人民共和国相关法律法规。你们还真就不能来。
> 
> @posclegom 又来又来，哪个法律法规列出来，别总是含糊其辞却煞有其事

@iamazy 不是我含糊其辞却煞有其事，而是中国法律就是含糊其辞却煞有其事，可以根据当局喜好而任意更改的。

**Comment by iamazy** [comment]
> > > > 美帝国主义的网站,我们就不能来了?
> > > 
> > > 
> > > @zhepama 按照中华人民共和国相关法律法规。你们还真就不能来。
> > 
> > 
> > @posclegom 又来又来，哪个法律法规列出来，别总是含糊其辞却煞有其事
> 
> @iamazy 不是我含糊其辞却煞有其事，而是中国法律就是含糊其辞却煞有其事，可以根据当局喜好而任意更改的。

![image](https://user-images.githubusercontent.com/16559960/122707069-d4f44f00-d28b-11eb-8590-7b4a33955c39.png)

@posclegom 这里说中共不会纠错，这里又说可以按当局喜好随意改的，反正人民向政府提的要求你们看不见。

**Comment by JingHuaMan** [comment]
> > > > 美帝国主义的网站,我们就不能来了?
> > > 
> > > 
> > > @zhepama 按照中华人民共和国相关法律法规。你们还真就不能来。
> > 
> > 
> > @posclegom 又来又来，哪个法律法规列出来，别总是含糊其辞却煞有其事
> 
> @iamazy 不是我含糊其辞却煞有其事，而是中国法律就是含糊其辞却煞有其事，可以根据当局喜好而任意更改的。

笑死，煞有介事地说什么“相关法律法规”，问什么法规又说不出个一二三四来，反华人士就这？真是有够好笑的呢
![image](https://user-images.githubusercontent.com/49118946/122711588-fe65a880-d294-11eb-9bf0-ab2e896c6c65.png)

**Comment by Awesom1-Tech** [comment]
> > 美帝国主义的网站,我们就不能来了?
> 
> @zhepama 按照中华人民共和国相关法律法规。你们还真就不能来。



> @Awesom1-Tech China has been threatening to take over Taiwan by force for 71 years, and I think China will continue to threaten to take over Taiwan by force for another 71 years. Why don't you tell your commie masters to invade Taiwan? Oh wait, you are just some loser in China whose money has been taken away by your commie masters.
> 
> Oh and by the way, China's vaccines suck! That's why Taiwan don't want them.

LOL A governor of a province even sent a letter to mourn the death of a dog in the United States. It's so funny that she didn't mourn the death of so many people in Taiwan. What's more, my colleague is also from Taiwan Province, and he earns 4 million yuan a year . What are you doing ? You don't even have to go to your father for the next meal. What you said is groundless, so even the Japs say that Taiwa is a fraud island. Hahaha, you will be like this in your whole life. Poor you
🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸

**Comment by posclegom** [comment]
> > > 美帝国主义的网站,我们就不能来了?
> > 
> > 
> > @zhepama 按照中华人民共和国相关法律法规。你们还真就不能来。
> 
> > @Awesom1-Tech China has been threatening to take over Taiwan by force for 71 years, and I think China will continue to threaten to take over Taiwan by force for another 71 years. Why don't you tell your commie masters to invade Taiwan? Oh wait, you are just some loser in China whose money has been taken away by your commie masters.
> > Oh and by the way, China's vaccines suck! That's why Taiwan don't want them.
> 
> LOL A governor of a province even sent a letter to mourn the death of a dog in the United States. It's so funny that she didn't mourn the death of so many people in Taiwan. What's more, my colleague is also from Taiwan Province, and he earns 4 million yuan a year . What are you doing ? You don't even have to go to your father for the next meal. What you said is groundless, so even the Japs say that Taiwa is a fraud island. Hahaha, you will be like this in your whole life. Poor you
> 🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸

@Awesom1-Tech I can't even understand what you are trying to write here. Please go back to school and re-learn your basic skills in English writing and prose so that you can write coherent passages that would allow other people to grasp the meanings you are trying to convey. Alternatively, if you can't write well in English, please consider switching back to writing in your native language.

**Comment by posclegom** [comment]
> > > > > 美帝国主义的网站,我们就不能来了?
> > > > 
> > > > 
> > > > @zhepama 按照中华人民共和国相关法律法规。你们还真就不能来。
> > > 
> > > 
> > > @posclegom 又来又来，哪个法律法规列出来，别总是含糊其辞却煞有其事
> > 
> > 
> > @iamazy 不是我含糊其辞却煞有其事，而是中国法律就是含糊其辞却煞有其事，可以根据当局喜好而任意更改的。
> 
> 笑死，煞有介事地说什么“相关法律法规”，问什么法规又说不出个一二三四来，反华人士就这？真是有够好笑的呢
> ![image](https://user-images.githubusercontent.com/49118946/122711588-fe65a880-d294-11eb-9bf0-ab2e896c6c65.png)

@JingHuaMan https://www.thepaper.cn/newsDetail_forward_8738734

**Comment by posclegom** [comment]
> > > > > 美帝国主义的网站,我们就不能来了?
> > > > 
> > > > 
> > > > @zhepama 按照中华人民共和国相关法律法规。你们还真就不能来。
> > > 
> > > 
> > > @posclegom 又来又来，哪个法律法规列出来，别总是含糊其辞却煞有其事
> > 
> > 
> > @iamazy 不是我含糊其辞却煞有其事，而是中国法律就是含糊其辞却煞有其事，可以根据当局喜好而任意更改的。
> 
> ![image](https://user-images.githubusercontent.com/16559960/122707069-d4f44f00-d28b-11eb-8590-7b4a33955c39.png)
> 
> @posclegom 这里说中共不会纠错，这里又说可以按当局喜好随意改的，反正人民向政府提的要求你们看不见。

@iamazy 你到底有没有基本逻辑思维能力，这两件事有逻辑关联吗？

**Comment by iamazy** [comment]
@posclegom 从来不正面回答问题，质疑这质疑那，找点队友吧，你水平不行

**Comment by Awesom1-Tech** [comment]
> > > > 美帝国主义的网站,我们就不能来了?
> > > 
> > > 
> > > @zhepama 按照中华人民共和国相关法律法规。你们还真就不能来。
> > 
> > 
> > > @Awesom1-Tech China has been threatening to take over Taiwan by force for 71 years, and I think China will continue to threaten to take over Taiwan by force for another 71 years. Why don't you tell your commie masters to invade Taiwan? Oh wait, you are just some loser in China whose money has been taken away by your commie masters.
> > > Oh and by the way, China's vaccines suck! That's why Taiwan don't want them.
> > 
> > 
> > LOL A governor of a province even sent a letter to mourn the death of a dog in the United States. It's so funny that she didn't mourn the death of so many people in Taiwan. What's more, my colleague is also from Taiwan Province, and he earns 4 million yuan a year . What are you doing ? You don't even have to go to your father for the next meal. What you said is groundless, so even the Japs say that Taiwa is a fraud island. Hahaha, you will be like this in your whole life. Poor you
> > 🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸
> 
> @Awesom1-Tech I can't even understand what you are trying to write here. Please go back to school and re-learn your basic skills in English writing and prose so that you can write coherent passages that would allow other people to grasp the meanings you are trying to convey. Alternatively, if you can't write well in English, please consider switching back to writing in your native language.

You can't rely on 'don't understand' to cover up your inner inferiority 😆. 
If you don't understand it, That you should to go back to study. 
You don't deserve me to speak to you in Chinese. I just think it's funny to tease Taiwanfrogs🐸🐸🐸. I just happened to meet a Taiwanfrog🐸. What you🐸 said just proved your ignorance and incompetence. By the way, what you🐸 said before seems that you🐸 know Chinese law very well? Did you🐸 study it seriously? Did you🐸 hear what others said or did you🐸 really know? Truth seeking is the most basic quality, but you🐸 don't even have the most basic things. What qualifications do you🐸 have to say these here. But spreading rumors is really a tradition of Taiwan frogs. Think about why there has BLM action, and think about why Taiwan frogs, who even have to fake infection data, don't even have the most basic quality of being human. That's the funniest part.

**Comment by zhangrunxu** [comment]
多谢一直支持结束一党专政，多谢一直支持天安门母亲，多谢一直支持维权律师，多谢一直为反送中发声，你上次提供的关于港警恶行的资料非常有价值，自当重谢。

**Comment by Awesom1-Tech** [comment]
> 多谢一直支持结束一党专政，多谢一直支持天安门母亲，多谢一直支持维权律师，多谢一直为反送中发声，你上次提供的关于港警恶行的资料非常有价值，自当重谢。

滚你妈的, 垃圾东西

**Comment by Awesom1-Tech** [comment]
> 多谢一直支持结束一党专政，多谢一直支持天安门母亲，多谢一直支持维权律师，多谢一直为反送中发声，你上次提供的关于港警恶行的资料非常有价值，自当重谢。

滚你妈的, 老子就支持中国共产党你能把我怎么样, 杂种, 就你这香港垃圾除了分裂国家你还会干嘛? 废物, 如果你是中国人那你花250把国籍退了, 如果你认为你不是中国人, 那请赶紧滚, 香港台湾就是中国的, 气不气, 打又不敢打, 打又打不过, 你除了是一个老废物你还是什么

**Comment by Awesom1-Tech** [comment]
> > > > > > 美帝国主义的网站,我们就不能来了?
> > > > > 
> > > > > 
> > > > > @zhepama 按照中华人民共和国相关法律法规。你们还真就不能来。
> > > > 
> > > > 
> > > > @posclegom 又来又来，哪个法律法规列出来，别总是含糊其辞却煞有其事
> > > 
> > > 
> > > @iamazy 不是我含糊其辞却煞有其事，而是中国法律就是含糊其辞却煞有其事，可以根据当局喜好而任意更改的。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/16559960/122707069-d4f44f00-d28b-11eb-8590-7b4a33955c39.png)
> > @posclegom 这里说中共不会纠错，这里又说可以按当局喜好随意改的，反正人民向政府提的要求你们看不见。
> 
> @iamazy 你到底有没有基本逻辑思维能力，这两件事有逻辑关联吗？

杂种, 法律法规是一成不变的? 真有意思, 我们不会纠错就你会是吧, 有一说一, 现在台湾死那么多人了
我就问例句
你妈死了没
😆 😆 😆 😆 😆 😆
