### ISSUE TITLE
。。。。。。。。。。。。。。。。。。

### ISSUE THREAD

**Issue by chanlyang** [programthink/zhao#377]

**Comment by posclegom** [comment]
@chanlyang 求求你做一个守法的墙内公民，别再翻墙跑这儿来了。

**Comment by chanlyang** [comment]
沃日你妈哟 这地方踏马的没你们这些智障能被墙？  这地方是让你们这群傻逼干这种事情的地方？

**Comment by XueMeijing** [comment]
> 沃日你妈哟 这地方踏马的没你们这些智障能被墙？ 这地方是让你们这群傻逼干这种事情的地方？

1.方滨兴说此系统起步于1998年
2.GitHub平台于2007年10月1日开始开发
3.你是没有手还是没有脑子？查一下先后顺序很难吗？

**Comment by daringyun** [comment]
there is no wall at all. they can visit github on its own. China doesn’t even bother with you clowns.

**Comment by chanlyang** [comment]
无语，，，，
