### ISSUE TITLE
编程随想好像已被抓，大快人心

### ISSUE THREAD

**Issue by iamazy** [programthink/zhao#378]

**Comment by itsxt** [comment]
有链接吗，想去瞅瞅

**Comment by iamazy** [comment]
@itsxt [中文维基-编程随想](https://zh.wikipedia.org/wiki/%E7%BC%96%E7%A8%8B%E9%9A%8F%E6%83%B3%E7%9A%84%E5%8D%9A%E5%AE%A2)，好像就是上个月的事情

**Comment by cloudmusiccc** [comment]
正道的光，这种人最好全部坐牢去把

**Comment by SkyGrass** [comment]
博客不更新嘛

**Comment by dzemmo** [comment]
舒服了

**Comment by iamazy** [comment]
链接在此: [“编程随想”被捕：IHIS为期5个月的地下工作正式告终](https://mp.weixin.qq.com/s/aoVwR5vfr0LQjOsXcVBnNw)
