### ISSUE TITLE
《满江红·和郭沫若同志》

### ISSUE THREAD

**Issue by iamazy** [programthink/zhao#384]
小小寰球，有几个苍蝇碰壁。嗡嗡叫，几声凄厉，几声抽泣。蚂蚁缘槐夸大国，蚍蜉撼树谈何易。正西风落叶下长安，飞鸣镝。
多少事，从来急；天地转，光阴迫。一万年太久，只争朝夕。四海翻腾云水怒，五洲震荡风雷激。要扫除一切害人虫，全无敌。

**Comment by posclegom** [comment]
@iamazy 

★郭沫若——足够厚颜无耻的党棍

不见图 请翻墙

　　为啥俺把郭沫若放到最后，因为此人是民国知名文人里面，最厚颜无耻的家伙，活脱脱一根党棍。此人能在官方排名的“鲁郭茅巴老曹”中名列第二，靠的就是【比城墙还厚的脸皮】。

◇郭沫若的雷人语录赏析

　　在1966年文革刚开始的头几天，精明的郭沫若立马看清了形势并发表公开讲话，开始为“政治站队”作准备了。
在一般的朋友、同志们看来，我是一个文化人，甚至于好些人都说我是一个作家，还是一个诗人，又是一个什么历史学家。几十年来，一直拿着笔杆子在写东西，也翻译了些东西。按字数来讲，恐怕有几百万字了。但是，拿今天的标准来讲，我以前所写的东西，严格地说，应该全部把它烧掉，没有一点价值。
　　文革期间，郭参加了某次纪念鲁迅的活动，他说道：
鲁迅如果还活在今天，他是会多么高兴啊！他一定会站在文化革命战线的前头行列，冲锋陷阵，同我们一起，在毛主席的领导下，踏出前人所没有走过的道路......
　　再来看看郭沫若是如何吹捧毛太祖的书法，连其中的【错别字】都被他肉麻地夸赞。
主席并无心成为诗家或词家，但他的诗词却成了诗词的顶峰。主席更无心成为书家，但他的墨迹却成了书法的顶峰。
例如这首《清平乐》的墨迹而论，“黄粱”写作“黄梁”，无心中粱字简化了。龙岩多写一个龙字。“分田分地真忙”下没有句点。这就是随意挥洒的证据。
然而这幅字写得多麽生动，多麽潇洒，多麽磊落。每一个字和整个篇幅都充满了豪放不羁的革命气韵。在这里给我们从事文学艺术工作的人，乃至从事任何工作的人，一个深刻的启示：那就是人的因素第一，政治工作第一，思想工作第一，抓活的思想第一，四个第一。

◇郭沫若的马屁诗词赏析

　　在本文即将结束时，再分享他的六首诗词，作为压轴戏。看完这些诗词，你就能领略到郭大诗人厚脸皮的风采。

《我向你高呼万岁》
我向你高呼万岁，斯大林元帅，你是全人类的解放者，今天是你的70寿辰，我向你高呼万岁。
原子弹的威力在你面前只是儿戏，细菌战的威协在你面前只是梦呓。
你的光暖使南北两冰洋化为暖流，你的润泽使撒哈拉沙漠化为沃土。
不朽的马克思和你同在，你和马克思一样永远不朽了！
不朽的恩格斯和你同在，你和恩格斯一样永远不朽了！
不朽的列宁和你同在，你和列宁一样永远地不朽了！

《毛主席赛过我亲爷爷》
天安门上红旗扬，毛主席画像挂墙上，亿万人民齐声唱毛主席万岁万万岁！万岁万岁寿无疆！
毛主席呀毛主席，你真赛过我亲爷爷！

《题毛主席在飞机中工作的摄影》
在一万公尺的高空，在图104的飞机之上，难怪阳光是加倍地明亮，机内和机外有着两个太阳！
不倦的精神啊，崇高的思想，凝成了交响曲的乐章，象静穆的丛山峻岭，也象浩渺无际的重洋！

《宇宙充盈歌颂声》
国庆年年益光辉，今年又有新景象。
人民英雄纪念碑，屹立天安门广场。
广场浩荡人如海，丰碑巍峨天变矮。
人间出现双太阳，天上地下增光彩。

《献给在座的江青同志》
（编程随想注：本诗写于1967年6月5日，纪念毛泽东《在延安文艺座谈会上的讲话》25周年讨论会的闭幕式）
亲爱的江青同志，你是我们学习的好榜样
你善于活学活用战无不胜的毛泽东思想
你奋不顾身地在文化战线上陷阵冲锋
使中国舞台充满了工农兵的英雄形象

《水调歌头——庆祝无产阶级文化大革命十周年》
（编程随想注：本诗写于1976年5月12日，打倒四人帮之前）
四海《通知》遍，
文革卷风云。
阶级斗争纲举，
打倒刘和林。

十载春风化雨
喜见山花烂漫
莺梭织锦勤
茁茁新苗壮
天下凯歌声

走资派
奋螳臂
邓小平
妄图倒退
奈“翻案不得人心”

“三项为纲”批透
复辟罪行怒讨
动地走雷霆
主席挥巨手
团结大进军

《水调歌头——粉碎四人帮》
（编程随想注：本诗写于1976年10月21日，打倒四人帮之后）
大快人心事
揪出四人帮
政治流氓文痞
狗头军师张

还有精生白骨
自比则天武后
铁帚扫而光
篡党夺权者
一枕梦黄梁

野心大
阴谋毒
诡计狂
真是罪该万死
迫害红太阳

接班人是俊杰
遗志继承果断
功绩何辉煌
拥护党中央

（大家请注意：末尾的这两首诗词，间隔仅仅5个月；前一首把江青捧上天，后一首把四人帮骂成臭头。咱们这位郭大诗人，翻脸比翻书还利索啊）

**Comment by iamazy** [comment]
@posclegom

战士战死了的时候，苍蝇们所首先发见的是他的缺点和伤痕，嘬着，营营地叫着，以为得意，以为比死了的战士更英雄。但是战士已经战死了，不再来挥去他们。于是乎苍蝇们即更其营营地叫，自以为倒是不朽的声音，因为它们的完全，远在战士之上。

的确的，谁也没有发见过苍蝇们的缺点和创伤。

然而，有缺点的战士终竟是战士，完美的苍蝇也终竟不过是苍蝇。

去罢，苍蝇们!虽然生着翅子，还能营营，总不会超过战士的。你们这些虫豸们!

**Comment by posclegom** [comment]
@iamazy 

《水调歌头——庆祝无产阶级文化大革命十周年》
（编程随想注：本诗写于1976年5月12日，打倒四人帮之前）
四海《通知》遍，
文革卷风云。
阶级斗争纲举，
打倒刘和林。

十载春风化雨
喜见山花烂漫
莺梭织锦勤
茁茁新苗壮
天下凯歌声

走资派
奋螳臂
邓小平
妄图倒退
奈“翻案不得人心”

“三项为纲”批透
复辟罪行怒讨
动地走雷霆
主席挥巨手
团结大进军

《水调歌头——粉碎四人帮》
（编程随想注：本诗写于1976年10月21日，打倒四人帮之后）
大快人心事
揪出四人帮
政治流氓文痞
狗头军师张

还有精生白骨
自比则天武后
铁帚扫而光
篡党夺权者
一枕梦黄梁

野心大
阴谋毒
诡计狂
真是罪该万死
迫害红太阳

接班人是俊杰
遗志继承果断
功绩何辉煌
拥护党中央

（大家请注意：末尾的这两首诗词，间隔仅仅5个月；前一首把江青捧上天，后一首把四人帮骂成臭头。咱们这位郭大诗人，翻脸比翻书还利索啊）

**Comment by Dlyoungml** [comment]
> @posclegom
> 
> 
> 
> 战士战死了的时候，苍蝇们所首先发见的是他的缺点和伤痕，嘬着，营营地叫着，以为得意，以为比死了的战士更英雄。但是战士已经战死了，不再来挥去他们。于是乎苍蝇们即更其营营地叫，自以为倒是不朽的声音，因为它们的完全，远在战士之上。
> 
> 
> 
> 的确的，谁也没有发见过苍蝇们的缺点和创伤。
> 
> 
> 
> 然而，有缺点的战士终竟是战士，完美的苍蝇也终竟不过是苍蝇。
> 
> 
> 
> 去罢，苍蝇们!虽然生着翅子，还能营营，总不会超过战士的。你们这些虫豸们!

这些歪曲中的另一个例子是关于外蒙古的独立的。在这一点上我想多说几句。反动分子企图煽动某些中国人的大汉族主义的感情，反对外蒙古人民建立自主的人民国家。但是请问。外蒙古附属于中国的时候，中国人对于外蒙古人民究竟给了些什么福利呢？难道不是某些中国的侵略主义者，派兵攻入外蒙古，在政治经济方面压迫外蒙古人民，这才激起外蒙古人民脱离中国而独立的要求吗？我们自己在封建主义与帝国主义双重压迫之下差不多不能自保，难道一定要强迫外蒙古人民跟着我们殉葬吗？我们在双重压迫之下，稍微有点觉悟的人便知道要求解放，难道外蒙古人民就不应该有点觉悟，不应该有解放的要求吗？  

认真说，倒是外蒙古人民比我们争气些，比我们觉悟的早，比我们更清醒地能和社会主义地苏联做朋友，因而得到了帮助，而比我们早解放了。我们假如是站在大公无私地立场，我们倒应该向外蒙古人民告罪、向外蒙古人民致敬、向外蒙古人民学习地。更那里有什么理由跟在美帝国主义和蒋介石反动地后面，来对苏联“愤慨”呢？再请问，由于外蒙古的独立，在苏联方面究竟得到了些什么呢？岂不是和我们一样，仅仅得到了一个邻邦？

问题应该是——外蒙古脱离了我们之后，外蒙古人民是不是更加幸福了？事实告诉我们，外蒙古人民是更加幸福了。前几年国民党政府派到库仑去监视公民投票的一位姓包的，事毕回重庆，曾经在报上发过谈话。“库仑街头差不多每家人家都有了无线电。”这是国民党说的话，而且是有报可查的。在得到解放之后，外蒙古人民的生活和生产不是都已经充分地提高了吗？  

人民中国和人民蒙古今后应该是亲密的兄弟，我们不能够固执着那种宗主和藩属的落后观念了。那是丝毫也不足引为光荣的！  

今年四月，我们中国代表团到欧洲去，在捷克的布拉格参加拥护世界和平大会的时候， 外蒙古代表团的团长齐登巴而先生，曾经为我们革命战争的辉煌胜利向我们致敬。他说：“日本帝国主义在远东称霸的时候，蒙古人民是寝息不安的，今天民主中国做了东方的盟主，我们蒙古人民就可以放心了。”  

请看看蒙古朋友们的这种坦白的风度吧。难道我们不应该有同样坦白的气概吗？ 

以上文字摘自郭沫若《中苏友好同盟条约四周年纪念日在北京新华广播电台对全国的广播

**Comment by posclegom** [comment]
> 以上文字摘自郭沫若《中苏友好同盟条约四周年纪念日在北京新华广播电台对全国的广播

@Dlyoungml 你发的贴太贴切了。郭沫若就是那个时代的蒙独、疆独、藏独、台独、港独、满独分子。

**Comment by iamazy** [comment]
> > 以上文字摘自郭沫若《中苏友好同盟条约四周年纪念日在北京新华广播电台对全国的广播
> 
> @Dlyoungml 你发的贴太贴切了。郭沫若就是那个时代的蒙独、疆独、藏独、台独、港独、满独分子。

外蒙是国民党和前苏联割裂出去的，和共产党一点关系都没有。不过你的观点我赞同，一切试图分裂中国的台独藏独份子都不可能得逞。你们搞这些舆论搞反华活动反而帮助我们更快的揭露了一些两面派，甚至反华人士的真面孔，揪出这些泥鳅让中国人态度更加坚定团结，期待清算的那天

**Comment by posclegom** [comment]
> > > 以上文字摘自郭沫若《中苏友好同盟条约四周年纪念日在北京新华广播电台对全国的广播
> > 
> > 
> > @Dlyoungml 你发的贴太贴切了。郭沫若就是那个时代的蒙独、疆独、藏独、台独、港独、满独分子。
> 
> 外蒙是国民党和前苏联割裂出去的，和共产党一点关系都没有。不过你的观点我赞同，一切试图分裂中国的台独藏独份子都不可能得逞。你们搞这些舆论搞反华活动反而帮助我们更快的揭露了一些两面派，甚至反华人士的真面孔，揪出这些泥鳅让中国人态度更加坚定团结，期待清算的那天

你双标玩的溜儿。不过你赞同郭沫若是蒙独、疆独、藏独、台独、港独、满独分子还是不错的。

**Comment by iamazy** [comment]
> > > > 以上文字摘自郭沫若《中苏友好同盟条约四周年纪念日在北京新华广播电台对全国的广播
> > > 
> > > 
> > > @Dlyoungml 你发的贴太贴切了。郭沫若就是那个时代的蒙独、疆独、藏独、台独、港独、满独分子。
> > 
> > 
> > 外蒙是国民党和前苏联割裂出去的，和共产党一点关系都没有。不过你的观点我赞同，一切试图分裂中国的台独藏独份子都不可能得逞。你们搞这些舆论搞反华活动反而帮助我们更快的揭露了一些两面派，甚至反华人士的真面孔，揪出这些泥鳅让中国人态度更加坚定团结，期待清算的那天
> 
> 你双标玩的溜儿。不过你赞同郭沫若是蒙独、疆独、藏独、台独、港独、满独分子还是不错的。

@posclegom 你哪只狗眼看到我说郭沫若是独了，我第一句话就说了外蒙独立和共产党无关，郭沫若是共产党你个双标狗

**Comment by iamazy** [comment]
@posclegom 就这还质疑别人文化水平有问题，美国现在已经请不起文化人了吗?

**Comment by posclegom** [comment]
> @posclegom 就这还质疑别人文化水平有问题，美国现在已经请不起文化人了吗?

@iamazy 五毛抄袭的速度还是挺快，已经抄袭我的留言方式了。

**Comment by posclegom** [comment]
> > > > > 以上文字摘自郭沫若《中苏友好同盟条约四周年纪念日在北京新华广播电台对全国的广播
> > > > 
> > > > 
> > > > @Dlyoungml 你发的贴太贴切了。郭沫若就是那个时代的蒙独、疆独、藏独、台独、港独、满独分子。
> > > 
> > > 
> > > 外蒙是国民党和前苏联割裂出去的，和共产党一点关系都没有。不过你的观点我赞同，一切试图分裂中国的台独藏独份子都不可能得逞。你们搞这些舆论搞反华活动反而帮助我们更快的揭露了一些两面派，甚至反华人士的真面孔，揪出这些泥鳅让中国人态度更加坚定团结，期待清算的那天
> > 
> > 
> > 你双标玩的溜儿。不过你赞同郭沫若是蒙独、疆独、藏独、台独、港独、满独分子还是不错的。
> 
> @posclegom 你哪只狗眼看到我说郭沫若是独了，我第一句话就说了外蒙独立和共产党无关，郭沫若是共产党你个双标狗

@iamazy "不过你的观点我赞同" -- 睁大你自己的眼睛看一看你自己写的东西！
