### ISSUE TITLE
好好的网站,就被你们一群傻逼搞得乌烟瘴气的,真滴服了.建议多吃点饭多睡点觉,少上网

### ISSUE THREAD

**Issue by stdAri** [programthink/zhao#414]
好好的网站,就被你们一群傻逼搞得乌烟瘴气的,真滴服了.建议多吃点饭多睡点觉,少上网

**Comment by stdAri** [comment]
目前所谓知识分子，实际上最无知识。工农分子反而有一点知识。

**Comment by gongchandangshisb** [comment]
五毛党滚回墙内，看看习包子给不给你五毛

**Comment by adrielliu** [comment]
> 五毛党滚回墙内，看看习包子给不给你五毛

香蕉人不好过吧 继续舔 哈哈

**Comment by gongchandangshisb** [comment]
> > 五毛党滚回墙内，看看习包子给不给你五毛
> 
> 香蕉人不好过吧继续舔哈哈

haha，你要笑死我，共产党权贵多要把你妈妈强奸了，你还不回去跪舔他们？

**Comment by gongchandangshisb** [comment]
> > 五毛党滚回墙内，看看习包子给不给你五毛
> 
> 香蕉人不好过吧继续舔哈哈

赶紧回去看看，看看你的妈妈有没有被共产党权贵们强奸，看看习包子会不会给你拨款

**Comment by xijinpingshigou** [comment]
> > 五毛党滚回墙内，看看习包子给不给你五毛
> 
> 香蕉人不好过吧 继续舔 哈哈

haha，为自由而发生就是香蕉人？老子向往自由，如果向往自由就把我们定义为香蕉人，那你们内心那股奴性，是什么？

**Comment by xijinpingshigou** [comment]
> 目前所谓知识分子，实际上最无知识。工农分子反而有一点知识。

啧啧，被共匪洗脑洗到这种程度，可见墙内愚民的智商了

**Comment by xijinpingshigou** [comment]
> 目前所谓知识分子，实际上最无知识。工农分子反而有一点知识。

或者是流在身上几千年的奴性，喜欢被统治，被剥削，宁愿当中共权贵的韭菜

**Comment by freedomgeeks** [comment]
这是你家吗傻逼，你管的着吗

**Comment by NanoMichael** [comment]
代码没见写得多好，搞事倒是有一套，好好的技术开源社区搞得乌烟瘴气的，服了

**Comment by cirosantillifather** [comment]
> 这是你家吗傻逼，你管的着吗

这是你家吗？你管得着？

**Comment by xioajiumi** [comment]
你这话可以对辛亥革命的那群人说，好好种地，闹什么革命？

**Comment by liu89501** [comment]
> 目前所谓知识分子，实际上最无知识。工农分子反而有一点知识。

你这已经被洗脑洗的无可救药了

**Comment by cirowayne** [comment]
> 无可救药

你的认知已经无可救药了

**Comment by tonyqus** [comment]
这repo都存在好多年了，你们是新来的吧，别大惊小怪~ 再说这个repo中国区又看不了，你们慌个啥~

**Comment by lcsxia** [comment]
> 目前所谓知识分子，实际上最无知识。工农分子反而有一点知识。

一帮泥腿子有知识？亩产万斤是真有知识

**Comment by 3GxnX82** [comment]
> 目前所谓知识分子，实际上最无知识。工农分子反而有一点知识。

看来你是看反华猪的文章或视频被洗脑得差不多了，真以为是他们所讲的那样都不行，太他妈好笑了，谁会想救你呢？弱智玩意，和你的废物狗逃去国外的叛徒所洗脑的人一起骂中国

**Comment by fgheng** [comment]
> 这是你家吗傻逼，你管的着吗

你家可以让其他人来乱搞么，一个好好的代码平台非要搞些乱七八糟的

**Comment by tonyqus** [comment]
@3GxnX82 兄弟，你的commit尽然是空的啊，你是特意注册github来骂的吗？还买了梯子？

![image](https://user-images.githubusercontent.com/772561/167311060-69789e35-7f67-4be0-8e47-06d4b647afeb.png)

听我一句劝，gitee和oschina少用，github才是涨工资的东西。
