### ISSUE TITLE
Why u guys want to politicalize GitHub?

### ISSUE THREAD

**Issue by ryderfang** [programthink/zhao#42]
It's just a technical exchange site, DO NOT fill it with nationalism & politics! OK?

**Comment by LaoDaGe** [comment]
滚你的小确幸！ 

https://github.com/LaoDaGe/HellSlave

**Comment by MiniSoda** [comment]
Anything posted here without violating the site's regulation is considered to be accountable.

**Comment by antipoliongithub** [comment]
@MiniSoda 大擦边球很有意思吗？

**Comment by biggoldstein** [comment]
@FongRay if you don't like this project you can choose to ignore it, the earth does not spin around you.

**Comment by xuxiansenTaurus** [comment]
@FongRay外國人不需要關心中國的內容，樓主可以get out了

**Comment by heimonsy** [comment]
明明大家都是中国人，说什么英文？

**Comment by codintsh** [comment]
明明大家都是中国人，说什么英文呀？
