### ISSUE TITLE
侮辱毛岸青烈士可太恶心了

### ISSUE THREAD

**Issue by Cherrymelon** [programthink/zhao#426]
要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧

**Comment by mikemaike** [comment]
cope n seethe

**Comment by liu89501** [comment]
> 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧

请停止你的傻逼行为，不是毛腊肉这个垃圾 志愿军战士不会白死20w的，所以骂他儿子有什么问题吗？

**Comment by cirowayne** [comment]
> > 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧
> 
> 请停止你的傻逼行为，不是毛腊肉这个垃圾 志愿军战士不会白死20w的，所以骂他儿子有什么问题吗？

白死20w，你的认知真的是绝了，看来小学肯定没读完。

**Comment by Perino74** [comment]
> 
> 
> 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧

支那猪知不知道死在北韩的叫什么名字啊？

**Comment by liu89501** [comment]
> > > 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧
> > 
> > 
> > 请停止你的傻逼行为，不是毛腊肉这个垃圾 志愿军战士不会白死20w的，所以骂他儿子有什么问题吗？
> 
> 白死20w，你的认知真的是绝了，看来小学肯定没读完。

呵呵，守在中国境内能死20w我吃屎，而且我也不觉得美国佬会打中国。而且以毛腊肉的尿性他真的把这些死去军人当人看了吗？我觉得他没有，要不然后面1960年左右发生的大饥荒他这个狗日的就不会放任饿死上千万人而不顾

**Comment by liu89501** [comment]
> > > > 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧
> > > 
> > > 
> > > 请停止你的傻逼行为，不是毛腊肉这个垃圾 志愿军战士不会白死20w的，所以骂他儿子有什么问题吗？
> > 
> > 
> > 白死20w，你的认知真的是绝了，看来小学肯定没读完。
> 
> 守在中国境内能死20w我吃屎，况且我也不觉得美国佬会打中国。而且以毛腊肉的尿性他真的把这些死去军人当人看了吗？我觉得他没有，要不然后面1960年左右发生的大饥荒他这个狗日的就不会放任饿死上千万人而不顾

**Comment by liu89501** [comment]
> > > 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧
> > 
> > 
> > 请停止你的傻逼行为，不是毛腊肉这个垃圾 志愿军战士不会白死20w的，所以骂他儿子有什么问题吗？
> 
> 白死20w，你的认知真的是绝了，看来小学肯定没读完。

守在中国境内能死20w我吃屎，况且我也不觉得美国佬会打中国，你看现在北朝鲜现在这样子对中国有什么卵用，能让中国经济增长还是怎么地？很多方面还不是得靠跟美国合作才能得到发展。而且当时以毛腊肉的尿性他真的把这些赴朝作战的人当人看了吗？我觉得他没有，要不然后面1960年左右发生的大饥荒他这个狗日的就不会放任饿死上千万人而不顾

**Comment by cirowayne** [comment]
> > 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧
> 
> 支那猪知不知道死在北韩的叫什么名字啊？

你知不知道你祖宗叫什么名字啊？什么祖宗都不认识？野种孩子

**Comment by cirowayne** [comment]
> > > > 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧
> > > 
> > > 
> > > 请停止你的傻逼行为，不是毛腊肉这个垃圾 志愿军战士不会白死20w的，所以骂他儿子有什么问题吗？
> > 
> > 
> > 白死20w，你的认知真的是绝了，看来小学肯定没读完。
> 
> 守在中国境内能死20w我吃屎，况且我也不觉得美国佬会打中国，你看现在北朝鲜现在这样子对中国有什么卵用，能让中国经济增长还是怎么地？很多方面还不是得靠跟美国合作才能得到发展。而且当时以毛腊肉的尿性他真的把这些赴朝作战的人当人看了吗？我觉得他没有，要不然后面1960年左右发生的大饥荒他这个狗日的就不会放任饿死上千万人而不顾

我看到你就烦，你这智商连跟我对话我都觉得是耻辱，拜拜了，你慢点吃

**Comment by liu89501** [comment]
> > > > > 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧
> > > > 
> > > > 
> > > > 请停止你的傻逼行为，不是毛腊肉这个垃圾 志愿军战士不会白死20w的，所以骂他儿子有什么问题吗？
> > > 
> > > 
> > > 白死20w，你的认知真的是绝了，看来小学肯定没读完。
> > 
> > 
> > 守在中国境内能死20w我吃屎，况且我也不觉得美国佬会打中国，你看现在北朝鲜现在这样子对中国有什么卵用，能让中国经济增长还是怎么地？很多方面还不是得靠跟美国合作才能得到发展。而且当时以毛腊肉的尿性他真的把这些赴朝作战的人当人看了吗？我觉得他没有，要不然后面1960年左右发生的大饥荒他这个狗日的就不会放任饿死上千万人而不顾
> 
> 我看到你就烦，你这智商连跟我对话我都觉得是耻辱，拜拜了，你慢点吃

你爸是赵家人吗？这样维护人家。还专门注册个账号到处喷人的傻逼狗屎玩意儿。

**Comment by cirowayne** [comment]
> > > > > > 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧
> > > > > 
> > > > > 
> > > > > 请停止你的傻逼行为，不是毛腊肉这个垃圾 志愿军战士不会白死20w的，所以骂他儿子有什么问题吗？
> > > > 
> > > > 
> > > > 白死20w，你的认知真的是绝了，看来小学肯定没读完。
> > > 
> > > 
> > > 守在中国境内能死20w我吃屎，况且我也不觉得美国佬会打中国，你看现在北朝鲜现在这样子对中国有什么卵用，能让中国经济增长还是怎么地？很多方面还不是得靠跟美国合作才能得到发展。而且当时以毛腊肉的尿性他真的把这些赴朝作战的人当人看了吗？我觉得他没有，要不然后面1960年左右发生的大饥荒他这个狗日的就不会放任饿死上千万人而不顾
> > 
> > 
> > 我看到你就烦，你这智商连跟我对话我都觉得是耻辱，拜拜了，你慢点吃
> 
> 你爸是赵家人吗？这样维护人家。还专门注册个账号到处喷人的傻逼狗屎玩意儿。

叫你去读书，非要去喂猪

**Comment by lcsxia** [comment]
毛岸青是烈士？谁封的，一个神经病患者而已

**Comment by liu89501** [comment]
> 

不好意思我看错了。 我以为那傻逼说的毛岸英

**Comment by liu89501** [comment]
> 毛岸青是烈士？谁封的，一个神经病患者而已

不好意思我看错了。 我以为那傻逼说的毛岸英

**Comment by 3GxnX82** [comment]
> 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧

这也是确实，他们那些傻逼猪脑子里只信那些逃出去的废物反华🐖的话，听他们怎么瞎掰，瞎扯，简直是弱智。

**Comment by liu89501** [comment]
> > 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧
> 
> 这也是确实，他们那些傻逼猪脑子里只信那些逃出去的废物反华🐖的话，听他们怎么瞎掰，瞎扯，简直是弱智。

呵呵一笑，朝鲜战争之后的十几年中国发生了什么心里没点B数吗。神TM和平安定的生活！！！

**Comment by chinaschichi** [comment]
> > > 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧
> > 
> > 
> > 支那猪知不知道死在北韩的叫什么名字啊？
> 
> 你知不知道你祖宗叫什么名字啊？什么祖宗都不认识？野种孩子

被毛岸青这头牲口操出来的畜生连话都说不清，让彭丽媛给你的野爹毛岸青口出来的你这个支那废物

**Comment by chinaschichi** [comment]
> > 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧
> 
> 这也是确实，他们那些傻逼猪脑子里只信那些逃出去的废物反华🐖的话，听他们怎么瞎掰，瞎扯，简直是弱智。

傻逼毛岸青操出来的脑瘫玩意儿还知道专门注册个账号来给你的野爹们增加笑料呢，你的脑瘫亲爹毛岸青和蛋炒饭毛岸英在老腊肉的大吊下看你这样一定孝得很开心

**Comment by clintisgoodboy** [comment]
> > > > 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧
> > > 
> > > 
> > > 请停止你的傻逼行为，不是毛腊肉这个垃圾 志愿军战士不会白死20w的，所以骂他儿子有什么问题吗？
> > 
> > 
> > 白死20w，你的认知真的是绝了，看来小学肯定没读完。
> 
> 守在中国境内能死20w我吃屎，况且我也不觉得美国佬会打中国，你看现在北朝鲜现在这样子对中国有什么卵用，能让中国经济增长还是怎么地？很多方面还不是得靠跟美国合作才能得到发展。而且当时以毛腊肉的尿性他真的把这些赴朝作战的人当人看了吗？我觉得他没有，要不然后面1960年左右发生的大饥荒他这个狗日的就不会放任饿死上千万人而不顾

真是个傻逼啊，不抗美援朝，国家安全都没有保障。真是个大傻逼

**Comment by liu89501** [comment]
> > > > > 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧
> > > > 
> > > > 
> > > > 请停止你的傻逼行为，不是毛腊肉这个垃圾 志愿军战士不会白死20w的，所以骂他儿子有什么问题吗？
> > > 
> > > 
> > > 白死20w，你的认知真的是绝了，看来小学肯定没读完。
> > 
> > 
> > 守在中国境内能死20w我吃屎，况且我也不觉得美国佬会打中国，你看现在北朝鲜现在这样子对中国有什么卵用，能让中国经济增长还是怎么地？很多方面还不是得靠跟美国合作才能得到发展。而且当时以毛腊肉的尿性他真的把这些赴朝作战的人当人看了吗？我觉得他没有，要不然后面1960年左右发生的大饥荒他这个狗日的就不会放任饿死上千万人而不顾
> 
> 真是个傻逼啊，不抗美援朝，国家安全都没有保障。真是个大傻逼

所以香港人过的比大陆人还差？去你妈的国家安全，中国就应该被殖民300年，垃圾国家

**Comment by clintisgoodboy** [comment]
> > > > > > 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧
> > > > > 
> > > > > 
> > > > > 请停止你的傻逼行为，不是毛腊肉这个垃圾 志愿军战士不会白死20w的，所以骂他儿子有什么问题吗？
> > > > 
> > > > 
> > > > 白死20w，你的认知真的是绝了，看来小学肯定没读完。
> > > 
> > > 
> > > 守在中国境内能死20w我吃屎，况且我也不觉得美国佬会打中国，你看现在北朝鲜现在这样子对中国有什么卵用，能让中国经济增长还是怎么地？很多方面还不是得靠跟美国合作才能得到发展。而且当时以毛腊肉的尿性他真的把这些赴朝作战的人当人看了吗？我觉得他没有，要不然后面1960年左右发生的大饥荒他这个狗日的就不会放任饿死上千万人而不顾
> > 
> > 
> > 真是个傻逼啊，不抗美援朝，国家安全都没有保障。真是个大傻逼
> 
> 所以香港人过的比大陆人还差？去你妈的国家安全，中国就应该被殖民300年，垃圾国家

你个脑瘫玩意，去找你的日本爹，美国爷爷。去吧

**Comment by marmot-z** [comment]
> > > > > > 要不是牺牲在保家卫国战场上的烈士，能有和平安定的生活？repo主可能不知是哪个尼个生出来的种吧
> > > > > 
> > > > > 
> > > > > 请停止你的傻逼行为，不是毛腊肉这个垃圾 志愿军战士不会白死20w的，所以骂他儿子有什么问题吗？
> > > > 
> > > > 
> > > > 白死20w，你的认知真的是绝了，看来小学肯定没读完。
> > > 
> > > 
> > > 守在中国境内能死20w我吃屎，况且我也不觉得美国佬会打中国，你看现在北朝鲜现在这样子对中国有什么卵用，能让中国经济增长还是怎么地？很多方面还不是得靠跟美国合作才能得到发展。而且当时以毛腊肉的尿性他真的把这些赴朝作战的人当人看了吗？我觉得他没有，要不然后面1960年左右发生的大饥荒他这个狗日的就不会放任饿死上千万人而不顾
> > 
> > 
> > 真是个傻逼啊，不抗美援朝，国家安全都没有保障。真是个大傻逼
> 
> 所以香港人过的比大陆人还差？去你妈的国家安全，中国就应该被殖民300年，垃圾国家

傻逼
