### ISSUE TITLE
阿弥托福

### ISSUE THREAD

**Issue by lcsxia** [programthink/zhao#432]
赵家人

**Comment by fuckgfwgcd** [comment]
你们主子：道路自信、理论自信、制度自信、文化自信。自信成精了，为什么还要建个Firewall，让你们这群弱智的玩意，从狗洞爬到墙外来咬人

**Comment by DWFLZXJ** [comment]
去你的美国主子那边当狗吧。去做三等公民吧。这是你这个狗子的自由。搞的好像你是主子一样。lowb

**Comment by fuckgfwgcd** [comment]
> 去你的美国主子那边当狗吧。去做三等公民吧。这是你这个狗子的自由。搞的好像你是主子一样。lowb

你个五毛。你主子习包子为什么把自己的女儿习明泽，送到美国去读书，去当狗，去做三等公民

**Comment by fuckgfwgcd** [comment]
> 去你的美国主子那边当狗吧。去做三等公民吧。这是你这个狗子的自由。搞的好像你是主子一样。lowb

你一条断脊之犬，也敢在这里狂吠！你的主子，赵家人纷纷把自己的崽子送到美国去当狗，当三等公民，去享受自由。你却从狗洞里面爬出来，为了主人咬人，可怜的臭虫
