### ISSUE TITLE
伍豪嗨皮！

### ISSUE THREAD

**Issue by lcsxia** [programthink/zhao#436]
嗨皮伍豪！

**Comment by fishincat** [comment]
爱国和爱党是两回事，就我观察身边人，真正爱党的还是很少的，但是朴素的爱国者是多的。
你们这些人喜欢把这两类人统归成所谓“奴才”，我只能说除了挑起骂端，无益于解决任何事情。

**Comment by liu89501** [comment]
中国确实不缺傻逼，前有义和团后有红卫兵，再看看以后会出现个啥组织维护他们的习爸爸，

**Comment by 3GxnX82** [comment]
> 中国确实不缺傻逼，前有义和团后有红卫兵，再看看以后会出现个啥组织维护他们的习爸爸，
中国确实不缺那些不知道自己是被国外的真正的反华势力所利用，如法轮功，纽约时报等。法轮功创始人的妈都死了，傻逼才会信他。

**Comment by 3GxnX82** [comment]
> 

这说明还是有人反抗那些像傻逼一样的天天骂中国的废物叛徒猪

**Comment by liu89501** [comment]
> 



> > 
> 
> 这说明还是有人反抗那些像一样的天天骂中国的废物叛徒猪

我几年前还信中共，谁让他黑历史那么多，光是知道一个8964就直接让我觉得这是个黑社会组织，还有最近的西安疫情，完全不把西安普通民众当人看的。凭啥还有人吹中共的啊，中共倒了中国就亡了吗还是？
