### ISSUE TITLE
讲个笑话 中国言论自由

### ISSUE THREAD

**Issue by Corybyte** [programthink/zhao#445]

**Comment by xdsun777** [comment]
奇怪这不一直是美国一直标榜自己言论自由吗？为啥在总统大选前几天把特朗普的推特号被封了

**Comment by Jeff17kk** [comment]
> 奇怪这不一直是美国一直标榜自己言论自由吗？为啥在总统大选前几天把特朗普的推特号被封了
有没有一种可能，推特代表不了美国。

**Comment by Jeff17kk** [comment]
> 奇怪这不一直是美国一直标榜自己言论自由吗？为啥在总统大选前几天把特朗普的推特号被封了

有没有一种可能，推特代表不了美国。

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/160324795-c89011ea-ed68-49ce-b04e-ea6c5d3727a3.png)

**Comment by AnyWAT** [comment]
【转】最新消息：

特斯拉首席执行官埃隆·马斯克（Elon Musk）在对社交媒体平台致力于言论自由提出质疑后，收购了Twitter 9%的股份，成为其最大股东。

**Comment by llorz-o** [comment]
资本家管你言论自由不自由

**Comment by AnyWAT** [comment]
【转】马斯克给推特董事会的信：

我投资推特是因为我相信推特有成为全球自由言论平台的潜力。言论自由是民主体制的必需品。然而我意识到推特在现有体制下不可能成功，更不可能服务言论自由。所以我要以54.2元每股全面收购推特。这是最好也是最后的出价。若不同意，我将考虑出售我的股票。

马斯克在他给政府报备的收购计划中附上了他给推特董事会的信。其中彻底阐述了他收购推特就是为了使其成为一个自由言论的平台。

这封信简短而铿锵有力：要么卖了推特，拿钱走人；那么我抛售推特，股价必然断崖下跌，我再低价抄底。

马斯克给政府报备的文件中附上了他给推特董事长的电话摘要：

我不玩绕弯的游戏，我就直来直往。我决定全面收购，并把公司私有化。出价是最终的也是最好的，推特的股东会喜欢的。我对推特的管理团队没有信心。所以如果不同意，我就卖了我的股票。这不是威胁，只是推特不改变，根本不值得投资。

**Comment by lcy362** [comment]
> > 奇怪这不一直是美国一直标榜自己言论自由吗？为啥在总统大选前几天把特朗普的推特号被封了
> 
> 有没有一种可能，推特代表不了美国。

对对对，不好的都代表不了美国。

**Comment by lazerta** [comment]
言论自由是讲 公民和政府的事情。政府不能压制言路。公权力和私人权利是不一样的。特朗普被禁言反而是言论自由的胜利，哪怕是美国总统，也会被禁言而不是美国总统禁言别人

**Comment by krisfans** [comment]
笑了，你不会以为美国就有言论自由吧？你这种行为，在美国至少是FBI禁告，严重的直接背后中7枪自杀。
美国标榜的言论自由，私有财产神圣不可侵犯，科学体育啥啥啥没国界全是笑话，美国人自己都不信，更可笑的是我们的一些人把这个宝贝似的

**Comment by krisfans** [comment]
> > 奇怪这不一直是美国一直标榜自己言论自由吗？为啥在总统大选前几天把特朗普的推特号被封了
> 
> 有没有一种可能，推特代表不了美国。

有没有一种可能美国是世界所有丑恶的来源

**Comment by free-znet** [comment]
讲个笑话，私人财产神圣不可侵犯

**Comment by ours1984** [comment]
> > > 奇怪这不一直是美国一直标榜自己言论自由吗？为啥在总统大选前几天把特朗普的推特号被封了
> > 
> > 
> > 有没有一种可能，推特代表不了美国。
> 
> 有没有一种可能美国是世界所有丑恶的来源

有没有一种可能,中国是世界所有开源的来源

**Comment by jieran233** [comment]
哈哈哈哈哈哈哈哈

**Comment by ghost** [comment]
> 资本家管你言论自由不自由

“资本主义”是马克思凭空造出的一个词，在马克思发布自己理论之前根本没有这个词。凭空造出的词，不可信。

**Comment by krisfans** [comment]
> > 资本家管你言论自由不自由
> 
> “资本主义”是马克思凭空造出的一个词，在马克思发布自己理论之前根本没有这个词。凭空造出的词，不可信。

就你这逻辑别上github了。牛顿三大定律是牛顿凭空捏造出来的词，不可信。

**Comment by zzy-ac** [comment]
> 【转】马斯克给推特董事会的信：
> 
> 我投资推特是因为我相信推特有成为全球自由言论平台的潜力。言论自由是民主体制的必需品。然而我意识到推特在现有体制下不可能成功，更不可能服务言论自由。所以我要以54.2元每股全面收购推特。这是最好也是最后的出价。若不同意，我将考虑出售我的股票。
> 
> 马斯克在他给政府报备的收购计划中附上了他给推特董事会的信。其中彻底阐述了他收购推特就是为了使其成为一个自由言论的平台。
> 
> 这封信简短而铿锵有力：要么卖了推特，拿钱走人；那么我抛售推特，股价必然断崖下跌，我再低价抄底。
> 
> 马斯克给政府报备的文件中附上了他给推特董事长的电话摘要：
> 
> 我不玩绕弯的游戏，我就直来直往。我决定全面收购，并把公司私有化。出价是最终的也是最好的，推特的股东会喜欢的。我对推特的管理团队没有信心。所以如果不同意，我就卖了我的股票。这不是威胁，只是推特不改变，根本不值得投资。

讲个笑话，推特言论自由，然后第一时间ban掉俄语用户

**Comment by noctiro** [comment]
> > 资本家管你言论自由不自由
> 
> “资本主义”是马克思凭空造出的一个词，在马克思发布自己理论之前根本没有这个词。凭空造出的词，不可信。

我挺好奇你到底来github干什么？没有什么像样的仓库？专门反华？？？
