### ISSUE TITLE
还有这种脑残崽种啊，真会编故事啊，精神病院关不住你们，就祝你们早日进局子吧

### ISSUE THREAD

**Issue by xiaozhuai** [programthink/zhao#449]
汉奸走狗说的就是你 @programthink  狗东西，怕是日本人留下来的野种。去找你日本人野爹，或者去找你美国野爷爷。

**Comment by NoahBishop** [comment]
有理有据成编故事，我把话放这，当官的亲属不是一起当官就是发大财，全球都一个屎样
