### ISSUE TITLE
麻烦整理一份美国金融军工关系网络，让我们见识一下西方自由世界的言论自由，谢谢

### ISSUE THREAD

**Issue by yangkangdev** [programthink/zhao#455]

**Comment by tonyqus** [comment]
你不是正在体验西方言论自由嘛，你换gitee讨论时政试试，要珍惜。所以我从来不用gitee， oschina我也不用，鬼知道这网站整天在干嘛。

**Comment by liuxiaoping2020** [comment]
哦哦，你说的美国言论自由就是造谣攻击别的国家哦，你倒是整理一下美国军工金融网络哦，整理一下美国种族仇恨歧视历史咯，整理一下美国黑命贵咯✌✌

**Comment by yangkangdev** [comment]
别给我在这里耍小聪明，我只是想系统的了解一些美国金融军工关系网络，以及，为什么布什和小布什能都当大统领，克林顿和希拉里为什么都能成为如此厉害的政治权贵，还有占领国会山那个家伙为什么会在自家地下室自己对着自己后背来11枪自杀，爱泼斯坦的那个小岛，以及最近拜登的儿子，诸如此类

**Comment by tonyqus** [comment]
@yangkangnevergiveup  编大佬已经进去了呀，只能指望你了，做出来我们都去给你点赞。你说的那些好像基本是公开信息，你可以自行尝试google，然后整理出来供爱国人士参考。

**Comment by tonyqus** [comment]
@yangkangnevergiveup 我仔细围观了下你follow的人，大部分是洋人嘛，尽然还有一个是邪恶的google公司的，你这属于投敌行为啊，这样不好~ 
![image](https://user-images.githubusercontent.com/772561/167359390-92d6a3c5-0b6b-4e45-8c41-ab4aa3d82cb6.png)

**Comment by liuxiaoping2020** [comment]
> 是吗，公开信息？你去深挖了吗？你说的编大佬搞这个钱是哪里来的？或者中国政府有专门出资养狗来深挖吗？有没有人专门做一个美国黑命贵/美国警察暴力执法/美国种族歧视/种族仇恨/美国枪击案/美国入侵别的国家的纪录片？ 中国不屑于在花钱养狗造谣攻击别人，你不能把美国政府出资养狗咬别的国家叫言论自由吧

**Comment by tonyqus** [comment]
我看你把回复删了，我就想问问，你有什么证据证明编大佬拿了美国人的钱呢？还是你有警察的调查证据，有些东西不需要靠钱，那不是一样的，共军给你钱来这里骂的吗？又没有发你家族谱，我理解应该没有把，所以按照你的逻辑你肯定是收了中共的钱咯。

**Comment by liuxiaoping2020** [comment]
弟弟，我删除评论是不想跟一个躲在电脑后面的不敢以真实身份示人的low货浪费时间。我从来没有说你口中的编大佬收美国的钱，我说的是美国政府发钱养狗咬人，你喜欢对号入座，我也没有办法。另外，我本是一个专注于技术的，从来不关心什么狗屁政治，github居然给我推送这个毫无技术含量的垃圾库，我有理由相信这背后是有势力在推动。美国政府把花钱养狗咬人都立法了，所以我也有理由合理怀疑这个垃圾库就是政府资助的结果。另外，我没有骂任何人，我说的是美国花钱养狗，那种东西不配我给予它人的尊重。我是收钱了，但我没有收你说的共军或者中共的钱，我收的是教育部每个月给我发的生活费，怎么的，我收钱了，我公开承认，但我的言论只代表我自己，我对我的言论负责，我在武汉大学。你和你口中的编大佬敢公开自己吗，敢对自己言论负责吗，你们在哪里，low货！

**Comment by tonyqus** [comment]
可能我昨天态度有点差，主要是看了好几个类似的repo，看到一群喷子在issues里面围攻repo主要贡献者，负能量有点高。我先给你道个歉。武汉大学还是不错的，学术排名很好，至少比国内一大堆野鸡二流学校强多了。

推送算法可能是因为中文的关系，我也经常被推送各种不喜欢的repo，github的推荐算法做的很一般，我基本是靠follower的star来发现新项目。这一点medium.com就做的很不错，就是收费的，每月5刀，否则限量看文章。但你要说美国Githug公司故意推送，我觉得可能性非常小，故意推送需要专门设置推送规则的，吃饱了吧，github中文用户群体是小众群体，他没必要为了那2-3%来定制这东西，你如果搞过推荐算法，应该知道我在说什么。我的意思是国内媒体老是宣扬敌对势力这件事，我觉得有点扯把，据我所知国内的CIA间谍组织已经被CIA内部人士给出卖了，早几年就被端掉了，我一直关注讫情报界舆情，当然我其实只是一个码农，纯吃瓜而已。你要说国内现在有没有间谍，肯定有，但数量绝对没有国内媒体说的这么多，现在国内的氛围就是任何国内反对的声音都是境外敌对势力，这不是跟当年文革的口径非常类似嘛，所以我有的时候开玩笑，文革2.0开始了。

其实我对那个所谓的净网协会做过一些背调，非常山寨的组织，几个小朋友各种吹，警察不可能和他们合作，最多就是他们一厢情愿去某网站上举报而已。你们当网警都是吃素的啊，还有国保和国安系统，真的要查太容易了。我甚至怀疑编程随想并没有被抓，只是被喝茶警告了。从头到尾都没有警方的抓捕通告，然后最近来了一个杭州马某某，那群喷子像过了节一样开始对号入座了，各种庆祝编大佬被抓，这不是搞笑嘛，跟他们有啥关系，没证据瞎说有啥意思。

**Comment by tonyqus** [comment]
说到美国金融军工关系网，你可以先从[这个页面](https://en.wikipedia.org/wiki/List_of_United_States_defense_contractors)顺藤摸瓜。

**Comment by michael-hoo** [comment]
> 

我只想知道为什么你能在这里打完整的中文，现在墙内不都流行缩写了嘛🤣啥？美国的黑料啊，那没事了

**Comment by slightwangmin** [comment]
你一个中国人连自家的东西都没整明白就去操心美国的了这是有病么？而且谷歌都能搜到的公开信息需要你故弄玄虚什么呢😅, 连维基上不都有？
明明自己在国内自媒体看的所谓美国黑料，不是从西方主流媒体抄的就是自西方阴谋论小报搬运的，还反过来煞有介事叫人家去调查报道，真是要笑死个人。村通网也不至于这样啊。

**Comment by slightwangmin** [comment]
你一个中国人连自家的东西都还没整明白就去急急忙忙操心美国的人事了，这不是有病么。而且都是谷歌上都能搜到明网上的公开信息（包括满天飞的阴谋论网站在内）需要你在这儿神神秘秘故弄玄虚什么呢😅我寻思这不是连维基百科上都有？
明明自己在国内自媒体看的所谓美国黑料不是从西方主流媒体抄的就是自西方阴谋论小报搬运的，还反过来煞有介事地叫人家去调查报道，笑死。村通网也不至于这样啊。

**Comment by ghost** [comment]
没有啊，可以看玉渊潭天、赛雷三分钟之类的UP主，还有Bilibili历史区的，还有观察者网、四月网、红歌会、天涯论坛、百度贴吧，这分析的老多了去了。你不善用谷歌和百度深度挖掘信息，还给别人添加负担.......
再说你既然都进入墙外了，Wikipedia自己搜一下很难吗？美国国会图书馆、旧中国立法院图书馆之类的网站也是很好的信息来源，如果你是大陆人，你可以去北京国家图书馆和国家档案馆，查共产党存过的几乎是70年代之后的所有报纸和各地任免状。你实在不行，再问问你们大学的老师借个校内数据库用也可以啊。

**Comment by Potion1337** [comment]
> 哦哦，你说的美国言论自由就是造谣攻击别的国家哦，你倒是整理一下美国军工金融网络哦，整理一下美国种族仇恨歧视历史咯，整理一下美国黑命贵咯✌✌

那你是真2b啊。。。别人能让讨论，你支让讨论？看不惯你现在去派出所举报一下这个repo？

**Comment by Handsomewl** [comment]
粉红真是无处不在呢

**Comment by sc-syf** [comment]
> 你不是正在体验西方言论自由嘛，你换gitee讨论时政试试，要珍惜。所以我从来不用gitee， oschina我也不用，鬼知道这网站整天在干嘛。

@tonyqus 西方言论自由。特朗普发的推，谁删的？特朗普账号，被谁封禁的？他言论自由了吗？对西方有利的叫言论自由。对西方不利的直接封号，这叫言论自由？

**Comment by sc-syf** [comment]
> 你不是正在体验西方言论自由嘛，你换gitee讨论时政试试，要珍惜。所以我从来不用gitee， oschina我也不用，鬼知道这网站整天在干嘛。

@tonyqus elonmusk刚发的推：

> Most people don’t appreciate the significance of the point Matt was making: \*Every\* social media company is engaged in heavy censorship, with significant involvement of and, at times, explicit direction of the government. Google frequently makes links disappear, for example.

真的好自由啊。

**Comment by tonyqus** [comment]
我们讨论的是gitee和github，你扯twitter干嘛？你说的也没错，确实没有完全的言论自由，但总有个比较吧，你怎么不去gitee发这些呢？为啥要来github呢？这答案你应该比我清楚。@sc-syf

**Comment by tonyqus** [comment]
@sc-syf [这个影片](https://www.youtube.com/watch?v=T_soQ7EZkaQ)适合你，刚翻墙出来确实很难理解一个正常人本应拥有的自由言论，你离正常人的生活很近了，加油。

**Comment by sc-syf** [comment]
> @sc-syf [这个影片](https://www.youtube.com/watch?v=T_soQ7EZkaQ)适合你，刚翻墙出来确实很难理解一个正常人本应拥有的自由言论，你离正常人的生活很近了，加油。

@tonyqus     十年前我朋友也有去加拿大、日本的，不要再给我宣扬国外有多“言论自由”了。另外，小兄弟，你太自大了。十年前我用goagent的翻出去时候，你可能还在幼儿园玩泥巴。

**Comment by tonyqus** [comment]
@sc-syf 且假设你比我老吧，一个比我大这么多的程序员，尽然连github都没用过，真的好神奇！你这些年是怎么熬过来的？十年前连gitee都没有，你那时候用啥？svn？

我只是说明了国外比国内言论自由的事实，为啥你要说我自大呢？醒醒吧，既然年级这么大了，就别再做井底之蛙了。

我还是想问之前的问题：你为啥不去gitee发这些讨论呢？请正面回答。

**Comment by liuxiaoping2020** [comment]
tonyqus 弟弟 哥劝你还是多把注意力放在你的工作家庭和事业方面，如果你觉得自己的国家有不完美的地方你就努力，用你的行动去优化她。当欧美国家比你强大的时候，他们就跟你讲所谓的自由，当你的实力接近欧美国家的时候，欧美国家就会告诉你什么叫做国家安全，美国优先，基于（美国）规则的国际秩序。当你能在美国使用华为手机、比亚迪汽车的时候，当美国政客不再挖空心思整TK的时候，当美国不再公开资助各式各样的反华分裂势力攻击中国政府和体制的时候，当美国政府不在背后控制脸书推特谷歌的时候，当那些不同意见着坚守负责任不炮制散播谎言的底线的时候，当你们这些人不再动不动给不同意见这乱扣五毛支那小粉红的时候，你再来跟国人讲什么是自由。
另外，不要以为有些话你在美国的社交平台可以发表，在国内的社交平台不被允许，就简单的认为美国比中国有言论自由，美国的那个社交平台没有新闻审查，你看看脸书推特谷歌封杀了多少中国账号，又是怎么怎样在背后偷偷地限制不同意见这的声音，油管上面有多少不反华的频道不被限流或者直接取消收益，又有多少反华账号每天赚的盆满钵满？相信你也认同言论自由是有边界和规则的，中国的言论自由就是不能违反宪法和其他法律，不能危害中国的国家安全和发展利益，不能破坏民族团结，不能推翻现有体制，我相信这些基本要求也是美国的他们的社交媒体的要求，不然推特不会封杀川普，前快船老板不会强迫卖掉球队，美国黑人犯罪，他们的媒体不会说是黑人犯罪而是非洲裔犯罪。。。但是美国却长期资助那些长期使用谎言来攻击中国体制、破坏民族团结、仇恨中国人的言论，所以你还认为美国有言论自由吗。
最后，哥跟你说个大实话，啥是自由，当你强大了，有钱了，你就自由了！！ 好好学习好好工作！！
哥是实名回复你的，如果你不能实名回复，我认为你是个不负责任的怂货，你也就不要回复了，OK？

**Comment by tonyqus** [comment]
确实欧美国家并没有完全的自由，但和中国比起来还是自由很多，确实你说的没错，FANG也封账号，twitter也封，但封的尺度还是比国内平台松很多，这一点你不会否认吧。还是你有不同的想法？

疫情三年，武汉是重灾区，你应该知道我在说什么，不仅仅是言论自由，很多人人身自由受到限制，甚至付出了生命的代价，我相信你身边的同事或者亲戚也有类似的例子。爱一个国家并不是一味的服从，而是要去帮助他改善并且优化他，但优化靠什么？是靠解决提出问题的人吗？还是靠解决问题本身？作为一个PHD，你能回答我这个问题吗？

我不认同 强大了、有钱了就自由的说法，有钱人有有钱人的苦，并没有这么自由。人来到这个世界本身就是受苦的，这点基本的道理你不会不懂吧。

我不太明白实名回复能给带来什么？能说明一下吗？而且我这是大号，不是小号，如果要隐瞒身份，我完全可以用小号不是吗？

我不确定是哪方面的Phd，如果要说好好学习、好好工作的话，不如从做个正常人开始，能够自由的讨论学术问题、能够科学的提出问题，其实言论自由很多时候也决定了学术研究的高度，这或许也是国内学术腐败主要的原因吧，因为没有人在提出问题，还是在抄袭和集成。院士们在做包工头的工作、博士们在帮着导师完成各种外包项目，就没有搞学术。

如果你真想实名，比如发几篇你自己的论文，我拜读和学习下，可以吗？

**Comment by tonyqus** [comment]
@liuxiaoping2020 我发现你是研究covid方面的专家呀（如果有不对请纠正），失敬失敬！方便问一下为什么国内新冠治疗药物研发这么落后吗？疫情三年，最后都没有什么有效的治疗药物，放开后，让大家买普通感冒药和退烧药治疗，这到底是什么情况？这就是您说的好好学习 好好生活的结果吗？

**Comment by liuxiaoping2020** [comment]
实名就是代表自己对自己言论负责，我认为这是言论自由的前提。你都不敢对自己的言论负责，跟你在这里讨论有什么意义？

**Comment by tonyqus** [comment]
不实名就不是对自己的言论负责了？所以网上那些因言获罪的是抓错了？这逻辑不太对啊 @liuxiaoping2022

那你知道为什么国外的网站一般不要求实名认证吗？

**Comment by liuxiaoping2020** [comment]
那你告诉我你怎么对你现在的言论负责？

**Comment by tonyqus** [comment]
搞错了，原来你是骨科专家，那好像和新冠没啥关系，当我没说吧。该下班了，祝好好生活。

**Comment by tonyqus** [comment]
@liuxiaoping2020 刚吃完饭，我们心平气和的聊一下。

首先我跟你不熟，你上来就跟我说什么对自己言论负责，就感觉很不友好，这好像应该是警察在审问嫌疑人时说的话。我不知道你平时是怎么跟陌生人说话的，但这种方式就很容易吵架，这也导致了我刚才说话的方式也有点冲，可能中国人的不团结也正是从不友好打招呼开始的。

其次，你是医学专业的，我是信息学专业的，在实名认证方面我可能比你更专业一些（当然你要说你学历比我高我也没办法，确实PhD比较牛逼）。什么哥哥、弟弟、爷爷这种辈分或者年龄的东西在我看来和专业不专业一点关系没有。所以请不要以长者自居，这会让我觉得你不太像一个高学历受教育者。首先，国内网站的之所以要实名认证就是为了解决文字狱的管控问题，我一般把这玩意叫做文字狱 2.0。但实名认证和显示真名是两码事，比如微博上从来没有要求大家都用真名作为昵称，且不能更改。我只是友善的建议你，在网络环境里不要用真名或者真实的个人信息或者位置信息，理由很简单，网络是虚拟的，你都不知道谁是好人谁是坏人。既然我可以用你的所谓实名信息搜到你的论文，我相信有些别有用心的人可以搜到更多的信息，比如你的工作单位、医院甚至家庭住址，在这种大背景下，不管是墙内还是墙外，我都不建议你把个人信息暴露在网络上，因为很多时候即使你被霸凌了，你打了110也不会有人管你，我就经历过这样的事，所以我只是用我的亲身经历来提醒你，你如果觉得我不显示真实姓名就是不负责任，那是你的自由，我也没有办法，但法律不是这么定义的，所以我没有必要遵循你所谓的实名对等原则。

从这点上看，@sc-syf做的比你好很多，他啥信息都没留下，当然从我的角度看，这不影响我跟他交流，因为我也不是网警、也不是公检法，我要他真名和个人信息有啥用呢？除了举报，我实在想不到其他用途。

第三，其实我们讨论（吵架）的核心还是中国到底算不算言论自由，虽然大家观点不同，但我还是希望平等的交流，什么辈分之类的言论还是省省吧，就事论事，我看你照片我们应该年龄相仿、并没有差几年，即使我们有年龄差距，这好像也不妨碍我们讨论任何问题吧，我不知道你有没有做过交换学者，有没有感受过国外的学术氛围，国外的学术氛围就是挑战权威，这一点我想你应该比我清楚，如果不清楚，建议问下你在国外的学长或者同学。

最后，我对你并没有敌意，还是希望友善的讨论言论自由的问题本身，谢谢。

**Comment by fuyi1215** [comment]
要爱党，爹亲娘亲不如共产党亲。做好奴隶当好韭菜，不需要任何思想。听党话跟党走。

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tonyqus** [comment]
> 要爱党，爹亲娘亲不如共产党亲。做好奴隶当好韭菜，不需要任何思想。听党话跟党走。 Get Outlook for iOS<https://aka.ms/o0ukef>

你这话我倒是听过，上次去跟居委书记反映小区某问题，他就是绕来绕去跟我说：要听党话，别瞎逼逼，还质问我说，你历史没学过吗？5000年的封建王朝文化，意思是我是草民，他是官吏，被我怼回去了。然后我把和他的对话在小区群里公示给了邻居们看，然后引来了一位前公安局退休民警的邻居的怒骂，说他敢以几十年的党龄保证，这个居委书记就是流氓，看来不是我一个人觉得他流氓。有的时候，做一下刁民为居民争取利益也无偿不可，这可能就是@liuxiaoping2020所说的："如果你觉得自己的国家有不完美的地方你就努力，用你的行动去优化她"，不知道我这样的行为算不算优化国家呢？ @liuxiaoping2020

**Comment by tonyqus** [comment]
@sc-syf  言归正传，回过来聊 言论自由。我们举一些最近的例子：

索尼中国微博账号被禁言 
网易2022年度盘点视频被全网下架

其实这两个被禁的内容我都看了，我并没有觉得有什么关联，也并没有理解为什么一个非公检法的组织能够在几天内（甚至几小时内）判定一个公司账号违法了，你可能会说他们辱华了，但你能告诉我到底是什么是辱华吗？有没有一个明确的规则？即使有这样的规则，是不是应该由法院来裁决，走庭审流程，有书面的证据和判决书。目前微博和微信一般只显示你违法了，却什么都无法提供，也不说你哪几个字因为什么原因违法了。

如果这两个贴在在推特上发的话，你觉得twitter会封吗？不如你可以做个实验，把同样的帖子发上去，看看推特封不封？这样是不是最直接呢？那如果推特没有封，是不是可以证明国外的言论比国内自由些？还是说你有其他的观点？

**Comment by xvivx** [comment]
> 1234`qw12`

**Comment by gaozx5519** [comment]
> @liuxiaoping2020 我发现你是研究covid方面的专家呀（如果有不对请纠正），失敬失敬！方便问一下为什么国内新冠治疗药物研发这么落后吗？疫情三年，最后都没有什么有效的治疗药物，放开后，让大家买普通感冒药和退烧药治疗，这到底是什么情况？这就是您说的好好学习 好好生活的结果吗？

你好色请问为什么我无法完整浏览你们的对话呢  我看不到您这条评论回复的评论
