### ISSUE TITLE
开源交互学习网站搞成政治，那干嘛不收集全球的达官显贵。

### ISSUE THREAD

**Issue by PengFeiHu2019** [programthink/zhao#462]

**Comment by lcy362** [comment]
伟大的西方自由世界，哪有权贵

**Comment by tonyqus** [comment]
亲，github什么都有，开源不仅仅是软件，也有信息开源，比如这个repo。是你对github理解错了，不信你可以投诉这个repo试试github删不删

**Comment by krisfans** [comment]
> 亲，github什么都有，开源不仅仅是软件，也有信息开源，比如这个repo。是你对github理解错了，不信你可以投诉这个repo试试github删不删

搞得github很清高一样，俄罗斯，还有啥来着账号不是说封就封

**Comment by tonyqus** [comment]
那我给你理一下哦，github是美国公司，被微软收购了，人家是美国公司，要遵守美国法律，俄罗斯在制裁名单上，自然是要删的。就跟中国公司要遵守中国法律一样，这个你能全怪github吗？

你要骂去北京丹棱街5号微软大厦门口举牌子呀，我支持你！

**Comment by krisfans** [comment]
制裁别的国家是美国法律规定的？孝死。美国政府高层的决定美国企业就必须执行？美国政府凭什么干涉市场，自由贸易呢？

**Comment by free-znet** [comment]
人家这叫目标明确，只收了收集zg的钱，当然只收集zg的咯

**Comment by yuhangshen555** [comment]
https://zh.m.wikipedia.org/zh-hans/%E5%A4%AA%E5%AD%90%E5%85%9A
可以看看，你有兴趣也可以整理
但是人家可是拿钱的，你拿钱了吗？
说真要是中共给我钱我也去整理
搞得哪个国家没有一样
中国特色社会主义万岁（x）

**Comment by yuhangshen555** [comment]
> https://zh.m.wikipedia.org/zh-hans/%E5%A4%AA%E5%AD%90%E5%85%9A 可以看看，你有兴趣也可以整理 但是人家可是拿钱的，你拿钱了吗？ 说真要是中共给我钱我也去整理 搞得哪个国家没有一样 中国特色社会主义万岁（x）

**Comment by PengFeiHu2019** [comment]
> > https://zh.m.wikipedia.org/zh-hans/%E5%A4%AA%E5%AD%90%E5%85%9A 可以看看，你有兴趣也可以整理 但是人家可是拿钱的，你拿钱了吗？ 说真要是中共给我钱我也去整理 搞得哪个国家没有一样 中国特色社会主义万岁（x）

我不关心政治，我只是觉得傻逼。没有项目可以不做，你哪怕搞点什么C++，ruby，java学习资料也没这么傻逼

**Comment by PengFeiHu2019** [comment]
> 亲，github什么都有，开源不仅仅是软件，也有信息开源，比如这个repo。是你对github理解错了，不信你可以投诉这个repo试试github删不删

建议你们搞一个什么historyhub，backgroundhub，WorldBigFigurehub，满足你们挖料普及众人的兴趣，我对你这种政治库不感兴趣，我关心自己的生活。怎么，关心了这些库我能涨薪水吗？能多退税吗？甚至能改变什么吗？有着闲工夫我不能多跑个demo？

**Comment by yuhangshen555** [comment]
> > 亲，github什么都有，开源不仅仅是软件，也有信息开源，比如这个repo。是你对github理解错了，不信你可以投诉这个repo试试github删不删
> 
> 建议你们搞一个什么historyhub，backgroundhub，WorldBigFigurehub，满足你们挖料普及众人的兴趣，我对你这种政治库不感兴趣，我关心自己的生活。怎么，关心了这些库我能涨薪水吗？能多退税吗？甚至能改变什么吗？有着闲工夫我不能多跑个demo？

是这样的，我很赞同你的观点，因为大多数人都是这样想的，但这样想是错的，举个例子吧，清朝的时候，没人关心这个社会是否正确，只关心自己得不得钱，这难道不是错误的吗

**Comment by PengFeiHu2019** [comment]
> > > 亲，github什么都有，开源不仅仅是软件，也有信息开源，比如这个repo。是你对github理解错了，不信你可以投诉这个repo试试github删不删
> > 
> > 
> > 建议你们搞一个什么historyhub，backgroundhub，WorldBigFigurehub，满足你们挖料普及众人的兴趣，我对你这种政治库不感兴趣，我关心自己的生活。怎么，关心了这些库我能涨薪水吗？能多退税吗？甚至能改变什么吗？有着闲工夫我不能多跑个demo？
> 
> 是这样的，我很赞同你的观点，因为大多数人都是这样想的，但这样想是错的，举个例子吧，清朝的时候，没人关心这个社会是否正确，只关心自己得不得钱，这难道不是错误的吗

少扯淡，来来来，那告诉我，收集这种库和关心社会有jb关系。那知道了那谁谁是一把手，二把手，八把手，又怎么样？那这么喜欢收集，干脆去当狗仔，专职关注大人物呗，没准还能能到呢想要的东西。关注社会？这也叫关注社会？一没能力，二没建设性建议，就tm搞搞收集跟我说关注社会，滚犊子

**Comment by tonyqus** [comment]
> > 亲，github什么都有，开源不仅仅是软件，也有信息开源，比如这个repo。是你对github理解错了，不信你可以投诉这个repo试试github删不删
> 
> 建议你们搞一个什么historyhub，backgroundhub，WorldBigFigurehub，满足你们挖料普及众人的兴趣，我对你这种政治库不感兴趣，我关心自己的生活。怎么，关心了这些库我能涨薪水吗？能多退税吗？甚至能改变什么吗？有着闲工夫我不能多跑个demo？

之所以这个repo这么流行，可能还是因为共军秘密太多了，也不让大家讨论。全球其他家族并不是什么秘密，至少可以公开讨论，比如罗斯柴尔德家族，我经常看到油管上大家讨论影子政府、深层政府、共济会。哪天国内真正言论自由了，可能就没这么多人关心这个repo了，你觉得呢？

**Comment by NoahBishop** [comment]
因为其他的人家都摆烂，我就是把自己亲属靠关系让他们挣大钱，做大官，人物百科都给你放那了，收集什么？？？

**Comment by PengFeiHu2019** [comment]
> > > 亲，github什么都有，开源不仅仅是软件，也有信息开源，比如这个repo。是你对github理解错了，不信你可以投诉这个repo试试github删不删
> > 
> > 
> > 建议你们搞一个什么historyhub，backgroundhub，WorldBigFigurehub，满足你们挖料普及众人的兴趣，我对你这种政治库不感兴趣，我关心自己的生活。怎么，关心了这些库我能涨薪水吗？能多退税吗？甚至能改变什么吗？有着闲工夫我不能多跑个demo？
> 
> 之所以这个repo这么流行，可能还是因为共军秘密太多了，也不让大家讨论。全球其他家族并不是什么秘密，至少可以公开讨论，比如罗斯柴尔德家族，我经常看到油管上大家讨论影子政府、深层政府、共济会。哪天国内真正言论自由了，可能就没这么多人关心这个repo了，你觉得呢？

一句话，你们爱讨论什么关我屁事，我tm每天手里一堆事还要跟你研究这个，我还没这么闲着蛋疼，等哪天你们讨论出一个什么宇宙和平发展法则，或者是最终国家政体纲要再给说这些吧
