### ISSUE TITLE
操你妈

### ISSUE THREAD

**Issue by origin-coding** [programthink/zhao#474]

**Comment by origin-coding** [comment]
傻逼，在开源社区搞反动政治有意思？
我他吗就想看看代码，别在这里发这些阴阳怪气的东西

**Comment by yoholo** [comment]
无能狂怒，甚至反驳不了只能爆粗口。。。可怜

**Comment by Dedicatus5457** [comment]
一帮傻逼玩意狗屁不会来开源社区键政聊pol，爱tm聊滚去推特脸书tg聊，别搁着把开源社区整的乌烟瘴气

**Comment by PastelSubliminal** [comment]
确实晦气，国外能发这种东西的平台多了去了，哪发都行别搞来这里污染github和trending。开源社区是给它们搞这种东西的？

**Comment by ours1984** [comment]
> 一帮傻逼玩意狗屁不会来开源社区键政聊pol，爱tm聊滚去推特脸书tg聊，别搁着把开源社区整的乌烟瘴气

有国才有开源

**Comment by slightwangmin** [comment]
操你妈，这种正能量信息，叫做反动政治？丫脑浆被屎糊了吧。爱看看不看滚，井底之蛙逼事多。

**Comment by KingBaker** [comment]
粉蛆滚回去,去用祖国的gitee

**Comment by tonyqus** [comment]
楼主是不是对github有什么误解，Github从来都不只是代码分享平台，否则也不会成为世界第一。格局就跟gitee不同。

我们反过来推，如果Github不能放这些，那投诉之后不应该早就删掉了吗？你觉得我说的对吗？

**Comment by AnnualfireCHW** [comment]
> 操你妈，这种正能量信息，叫做反动政治？丫脑浆被屎糊了吧。爱看看不看滚，井底之蛙逼事多。

闭嘴吧，nt玩意，强的就是你这种不带脑子的，哪来的滚哪去？井底蛙是你吧，带着望远镜在这到处望真搞笑了。

**Comment by AnnualfireCHW** [comment]
> 操你妈，这种正能量信息，叫做反动政治？丫脑浆被屎糊了吧。爱看看不看滚，井底之蛙逼事多。

给你m爹舔py去，去YouTube的Facebook上聊，这么热爱你的m国，这点能耐都没有啊😋
