### ISSUE TITLE
开源仓库是十分脆弱的，不应夹杂政治

### ISSUE THREAD

**Issue by OctoberWithYou** [programthink/zhao#477]
开源仓库是十分脆弱的，不应夹杂政治，如果你想，大可以到facebook、推特等社交平台去发，github应该是程序员们交流技术的平台

**Comment by ours1984** [comment]
开源无国界,开源家是由国界的!

**Comment by cloudwindy** [comment]
你去 [996.ICU](https://github.com/996icu/996.ICU) 也说说呗

**Comment by ours1984** [comment]
> 你去 [996.ICU](https://github.com/996icu/996.ICU) 也说说呗

天将降大任疼于斯人也,快去吧骚年.我享受你的成果就好了

**Comment by tooeviltofall** [comment]
天安门广场是人民的，不应该屠杀人民
