### ISSUE TITLE
没有人开一个黑欧美历史的仓库吗？

### ISSUE THREAD

**Issue by WLDragon** [programthink/zhao#478]
github这么开放我相信是不会禁止任何有关陈列欧美黑历史的言论的
关于封杀github我对中国的做法也是很失望的。难道不能正面刚吗？真的觉得自己的国民都是傻子，分不清是非？
我只是想简简单单地学习和使用别人的优秀开源程序，以及分享自己的项目
是哪个傻逼在这上面搞政治？害得我又要花钱买梯子，FUCK

**Comment by michael-hoo** [comment]
利用欧美的言论自由来反对言论自由🤣真有你的

**Comment by JayChou55** [comment]
> github这么开放我相信是不会禁止任何有关陈列欧美黑历史的言论的 关于封杀github我对中国的做法也是很失望的。难道不能正面刚吗？真的觉得自己的国民都是傻子，分不清是非？ 我只是想简简单单地学习和使用别人的优秀开源程序，以及分享自己的项目 是哪个傻逼在这上面搞政治？害得我又要花钱买梯子，FUCK

就问你 为什么要搞一个墙，但凡有点脑子 都不会站队zg zf

**Comment by WLDragon** [comment]
> 就问你 为什么要搞一个墙，但凡有点脑子 都不会站队zg zf

呵呵，我也反对墙，但是我的祖国只能我自己骂，轮不到外人吠

**Comment by JayChou55** [comment]
> 

支持你，但，你这思维先送给我们自己吧，从上到下 你看全球还有几个发达国家我们没骂过没指责过呢。。。也就俄罗斯 塔利班 伊朗 朝鲜之类的zf 我们的d煤没怎么指责过。。。说到你反对强 你的反对 完全没用 甚至你连说都不敢说 可悲不。。。令人绝望的是，反对不仅仅局限于墙的事 而是穿插于生活的各方各面，我相信大多喷的是 目的也是希望它变好，墙里把嘴都封住了，只能在外面找个地方说了，但凡墙里能说，谁没事跑到外面喷。。。另外你敢骂你祖国吗？？？微博去骂骂看呢

**Comment by ours1984** [comment]
他们自己各种官方非官方新闻里早就黑遍了,他们的民众知道政府是个啥,他们是自由地选择了枪击每一天.轮不到github来黑.我们?我们这是利用了开源这个特性,利用github硬刚墙.从Google的屏蔽来看,github不屏蔽天理不容

**Comment by ours1984** [comment]
所以你就把买梯子这个责任算在了搞政治上?从来不思考一下的.那学生们不能用谷歌学术的责任又算在谁头上?算在全世界逆行的国家头上?他们喜欢搞政治?

**Comment by ours1984** [comment]
> > 
> 
> 支持你，但，你这思维先送给我们自己吧，从上到下 你看全球还有几个发达国家我们没骂过没指责过呢。。。也就俄罗斯 塔利班 伊朗 朝鲜之类的zf 我们的d煤没怎么指责过。。。说到你反对强 你的反对 完全没用 甚至你连说都不敢说 可悲不。。。令人绝望的是，反对不仅仅局限于墙的事 而是穿插于生活的各方各面，我相信大多喷的是 目的也是希望它变好，墙里把嘴都封住了，只能在外面找个地方说了，但凡墙里能说，谁没事跑到外面喷。。。另外你敢骂你祖国吗？？？微博去骂骂看呢

哪里没指责.最近朝鲜面对omicron搞躺平,好像还有声有色的,被我们全面封锁消息了

**Comment by WLDragon** [comment]
> 他们自己各种官方非官方新闻里早就黑遍了,他们的民众知道政府是个啥,他们是自由地选择了枪击每一天.轮不到github来黑.我们?我们这是利用了开源这个特性,利用github硬刚墙.从Google的屏蔽来看,github不屏蔽天理不容

看来我以暴治暴的想法确实是肤浅了，死猪不怕开水烫。既然环境是这样，我应该想办法去适应才对，而不是抱怨。物竞天择，适者生存。

**Comment by ours1984** [comment]
> 利用欧美的言论自由来反对言论自由🤣真有你的

还利用a来反对a,可真有你的.
你被国内`扛着红旗反红旗``利用维护纪律之名破坏纪律`这类垃圾话熏陶多了吧

**Comment by ours1984** [comment]
> > 利用欧美的言论自由来反对言论自由🤣真有你的
> 
> 还利用a来反对a,可真有你的. 你被国内`` 扛着红旗反红旗``利用维护纪律之名破坏纪律 ``这类垃圾话熏陶多了吧

能够`利用a来反对a的东西`,大多都是它本身不够a.
等到哪一天,欧美被我们实际渗透,自由称为一纸空文之后,我们才能堂而皇之说这句话

**Comment by JayChou55** [comment]
> 

秦人让你去建长城，你就建到死？     纯去适应这事 奴性未免也太足了，不如学下 d员们的操作 润了吧 至少也把子女送出去

**Comment by JayChou55** [comment]
> > 他们自己各种官方非官方新闻里早就黑遍了,他们的民众知道政府是个啥,他们是自由地选择了枪击每一天.轮不到github来黑.我们?我们这是利用了开源这个特性,利用github硬刚墙.从Google的屏蔽来看,github不屏蔽天理不容
> 
> 看来我以暴治暴的想法确实是肤浅了，死猪不怕开水烫。既然环境是这样，我应该想办法去适应才对，而不是抱怨。物竞天择，适者生存。

秦人让你去建长城，你就建到死？ 纯去适应这事 奴性未免也太足了，不如学下 d员们的操作 润了吧 至少也把子女送出去

**Comment by michael-hoo** [comment]
> > > 利用欧美的言论自由来反对言论自由🤣真有你的
> > 
> > 
> > 还利用a来反对a,可真有你的. 你被国内` 扛着红旗反红旗`利用维护纪律之名破坏纪律 ``这类垃圾话熏陶多了吧
> 
> 能够`利用a来反对a的东西`,大多都是它本身不够a. 等到哪一天,欧美被我们实际渗透,自由称为一纸空文之后,我们才能堂而皇之说这句话

1. 你这都不是“五十步笑百步”了，你这是“一千步笑五十步”……
2. 睡觉去吧，梦里什么都可以实现🤣

**Comment by WLDragon** [comment]
> > > 他们自己各种官方非官方新闻里早就黑遍了,他们的民众知道政府是个啥,他们是自由地选择了枪击每一天.轮不到github来黑.我们?我们这是利用了开源这个特性,利用github硬刚墙.从Google的屏蔽来看,github不屏蔽天理不容
> > 
> > 
> > 看来我以暴治暴的想法确实是肤浅了，死猪不怕开水烫。既然环境是这样，我应该想办法去适应才对，而不是抱怨。物竞天择，适者生存。
> 
> 秦人让你去建长城，你就建到死？ 纯去适应这事 奴性未免也太足了，不如学下 d员们的操作 润了吧 至少也把子女送出去

你是不是对适者生存有什么误解？现在github被墙了，我没能力把墙推倒我就翻墙，这叫适者生存。你为了能在美国做不用夹着尾巴的狗而到处抹黑自己的祖国这叫奴性。开什么玩笑？把子女送出去吃子弹吗？

**Comment by JayChou55** [comment]
> > > > 他们自己各种官方非官方新闻里早就黑遍了,他们的民众知道政府是个啥,他们是自由地选择了枪击每一天.轮不到github来黑.我们?我们这是利用了开源这个特性,利用github硬刚墙.从Google的屏蔽来看,github不屏蔽天理不容
> > > 
> > > 
> > > 看来我以暴治暴的想法确实是肤浅了，死猪不怕开水烫。既然环境是这样，我应该想办法去适应才对，而不是抱怨。物竞天择，适者生存。
> > 
> > 
> > 秦人让你去建长城，你就建到死？ 纯去适应这事 奴性未免也太足了，不如学下 d员们的操作 润了吧 至少也把子女送出去
> 
> 你是不是对适者生存有什么误解？现在github被墙了，我没能力把墙推倒我就翻墙，这叫适者生存。你为了能在美国做不用夹着尾巴的狗而到处抹黑自己的祖国这叫奴性。开什么玩笑？把子女送出去吃子弹吗？

送出去吃子弹这话，从你身上我只看到了 可悲

**Comment by slightwangmin** [comment]
粉蛆，畜生也，畏威而不怀德。 
不知各位有没有注意到这样一个规律：
你越是把小忠子修理得越惨，管得越狠，它们就越是不敢造次，反而还要给你歌功颂德、出书立传记，奉为祖宗顶礼膜拜。
譬如蒙古大汗忽必烈，譬如满洲皇帝努尔哈赤，譬如俄国沙皇斯大林，譬如苏维埃腊肉老贼，譬如刁皇我包。而那些对小忠子的脾气百般包容迁就的，给小忠子投资撒钱输送技术的，还有带它们入伙发财的，粉蛆反而恨得最深，叫嚣得最凶。

**Comment by slightwangmin** [comment]
笑死，人家又不用特地非法翻墙才能曝光自家的长老权贵，就连上网黑屁造谣散播阴谋论抹黑自己国家也构不成违法犯罪。
国内每天给你投喂的所谓黑料，不是经添油加醋后的西方主流媒体自己的公开报道，就是从西方阴谋论网站搬运的二手屎。说白了就是你连吃屎都赶不上新鲜的。还把批判政客权贵和国家体制这种随便来的事当什么宝呢。也不知楼主今年多大了。脑子是个好东西希望你也有。

**Comment by ours1984** [comment]
> 难道不能正面刚吗？真的觉得自己的国民都是傻子，分不清是非？

说到点子上了,正因为不是傻子,正因为人生来是可以愤青是非的
所以谁在怕

**Comment by dragonjay-lyj** [comment]
> > github这么开放我相信是不会禁止任何有关陈列欧美黑历史的言论的 关于封杀github我对中国的做法也是很失望的。难道不能正面刚吗？真的觉得自己的国民都是傻子，分不清是非？ 我只是想简简单单地学习和使用别人的优秀开源程序，以及分享自己的项目 是哪个傻逼在这上面搞政治？害得我又要花钱买梯子，FUCK
> 
> 就问你 为什么要搞一个墙，但凡有点脑子 都不会站队zg zf

哦~这香甜的空气，你看看美国没建墙现在成了什么样子，真美丽

**Comment by dragonjay-lyj** [comment]
> 

你难道不可悲吗？这么憎恨自己的国家，啧啧啧，还用着简体字，吃着中国的饭还反咬一口，现在本人是不是还在美国弗洛里亚大别墅里住着呢

**Comment by dragonjay-lyj** [comment]
> 笑死，人家又不用特地非法翻墙才能曝光自家的长老权贵，就连上网黑屁造谣散播阴谋论抹黑自己国家也构不成违法犯罪。 国内每天给你投喂的所谓黑料，不是经添油加醋后的西方主流媒体自己的公开报道，就是从西方阴谋论网站搬运的二手屎。说白了就是你连吃屎都赶不上新鲜的。还把批判政客权贵和国家体制这种随便来的事当什么宝呢。也不知楼主今年多大了。脑子是个好东西希望你也有。

这么喜欢吃西方的粑粑咋不钻进去呢，从你本身的立场出发骨子里就觉得中国人很贱，西方人高尚富贵多了，自己都那么贱低自己又何谈别人呢？

**Comment by dragonjay-lyj** [comment]
> > > 他们自己各种官方非官方新闻里早就黑遍了,他们的民众知道政府是个啥,他们是自由地选择了枪击每一天.轮不到github来黑.我们?我们这是利用了开源这个特性,利用github硬刚墙.从Google的屏蔽来看,github不屏蔽天理不容
> > 
> > 
> > 看来我以暴治暴的想法确实是肤浅了，死猪不怕开水烫。既然环境是这样，我应该想办法去适应才对，而不是抱怨。物竞天择，适者生存。
> 
> 秦人让你去建长城，你就建到死？ 纯去适应这事 奴性未免也太足了，不如学下 d员们的操作 润了吧 至少也把子女送出去

你难道不可悲吗？这么憎恨自己的国家，啧啧啧，还用着简体字，吃着中国的饭还反咬一口，现在本人是不是还在美国弗洛里亚大别墅里住着呢

**Comment by dragonjay-lyj** [comment]
> github这么开放我相信是不会禁止任何有关陈列欧美黑历史的言论的 关于封杀github我对中国的做法也是很失望的。难道不能正面刚吗？真的觉得自己的国民都是傻子，分不清是非？ 我只是想简简单单地学习和使用别人的优秀开源程序，以及分享自己的项目 是哪个傻逼在这上面搞政治？害得我又要花钱买梯子，FUCK

https://github.com/DragonJay666/-Europe-and-America 欢迎pull

**Comment by tianxin8848** [comment]
> > > > 他们自己各种官方非官方新闻里早就黑遍了,他们的民众知道政府是个啥,他们是自由地选择了枪击每一天.轮不到github来黑.我们?我们这是利用了开源这个特性,利用github硬刚墙.从Google的屏蔽来看,github不屏蔽天理不容
> > > 
> > > 
> > > 看来我以暴治暴的想法确实是肤浅了，死猪不怕开水烫。既然环境是这样，我应该想办法去适应才对，而不是抱怨。物竞天择，适者生存。
> > 
> > 
> > 秦人让你去建长城，你就建到死？ 纯去适应这事 奴性未免也太足了，不如学下 d员们的操作 润了吧 至少也把子女送出去
> 
> 你难道不可悲吗？这么憎恨自己的国家，啧啧啧，还用着简体字，吃着中国的饭还反咬一口，现在本人是不是还在美国弗洛里亚大别墅里住着呢

趙家奴隸適可而止，不是誰都想跟你一樣做黨匪的奴隸。

**Comment by xvivx** [comment]
> > 
> 
> 你难道不可悲吗？这么憎恨自己的国家，啧啧啧，还用着简体字，吃着中国的饭还反咬一口，现在本人是不是还在美国弗洛里亚大别墅里住着呢

他不写英文可能担心你看不懂，毕竟百度翻译的不准

**Comment by Gardenias-123** [comment]
> github这么开放我相信是不会禁止任何有关陈列欧美黑历史的言论的 关于封杀github我对中国的做法也是很失望的。难道不能正面刚吗？真的觉得自己的国民都是傻子，分不清是非？ 我只是想简简单单地学习和使用别人的优秀开源程序，以及分享自己的项目 是哪个傻逼在这上面搞政治？害得我又要花钱买梯子，FUCK

因为那些都是之前玩过的了，现在在弄也没什么人看。
不像这个repo，多少年前的东西了，现在还有人翻墙来骂
