### ISSUE TITLE
虽然作者是在陈述事实，但是跑到github搞这玩意恶心谁呢

### ISSUE THREAD

**Issue by swanine** [programthink/zhao#479]

**Comment by ours1984** [comment]
诺贝尔和平奖一把空椅子了解一下.难道跑到牢房里搞?

**Comment by tonyqus** [comment]
不就是个关系图谱嘛，涨知识而已，谈不上恶心。

**Comment by hdd99009** [comment]
至少可以恶心你

**Comment by ours1984** [comment]
> 不就是个关系图谱嘛，涨知识而已，谈不上恶心。

谁陈述事实,就是挖我祖宗十八代的祖坟

**Comment by xiaoqide** [comment]
2016年两会前夕，在他将《太子党关系网络》开源道GitHub上之后，中国当局借用一个“半官方”的组织“中国网络空间安全协会”针对这个项目的某篇文章向GitHub的网管发去了一份“删除令”，称其平台上的“zhao”项目诽谤中华人民共和国领导人习近平。这是自2014年以来 GitHub公布的史上第6个，也是来自中国的第一个“删除特定项目要求”，此前的5项都来自俄罗斯。之后GitHub对编程随想的“zhao”项目进行了选择性屏蔽，导致墙内的网民无法正常打开这个项目

**Comment by ours1984** [comment]
遥想学生当年,思想解放了,雄姿英发. 星星之火,壮烈燃烧
现如今,每天只是盯着祖坟,不知今夕何夕

> 最终政府方面于1月2日凌晨释放了全部被捕学生。至此，北京的“元旦风波”被平息，标志着前后历时27天的“八六学潮”结束。
八六学潮沿袭“[北京之春](https://zh.wikipedia.org/wiki/%E5%8C%97%E4%BA%AC%E4%B9%8B%E6%98%A5)”：“[不自由毋宁死](https://zh.wikipedia.org/wiki/%E4%B8%8D%E8%87%AA%E7%94%B1%E6%AF%8B%E5%AE%81%E6%AD%BB)”、“[没有民主就没有现代化](https://zh.wikipedia.org/w/index.php?title=%E6%B2%92%E6%9C%89%E6%B0%91%E4%B8%BB%E5%B0%B1%E6%B2%92%E6%9C%89%E7%8F%BE%E4%BB%A3%E5%8C%96&action=edit&redlink=1)”的口号来表达不满。学潮由合肥爆发，得到北京、[天津](https://zh.wikipedia.org/wiki/%E5%A4%A9%E6%B4%A5)、[哈尔滨](https://zh.wikipedia.org/wiki/%E5%93%88%E7%88%BE%E6%BF%B1)、[大连](https://zh.wikipedia.org/wiki/%E5%A4%A7%E9%80%A3)、[兰州](https://zh.wikipedia.org/wiki/%E8%98%AD%E5%B7%9E)、[郑州](https://zh.wikipedia.org/wiki/%E9%84%AD%E5%B7%9E)、[西安](https://zh.wikipedia.org/wiki/%E8%A5%BF%E5%AE%89)、[成都](https://zh.wikipedia.org/wiki/%E6%88%90%E9%83%BD)、[衡阳](https://zh.wikipedia.org/wiki/%E8%A1%A1%E9%99%BD)、[扬州](https://zh.wikipedia.org/wiki/%E6%8F%9A%E5%B7%9E)、[杭州](https://zh.wikipedia.org/wiki/%E6%9D%AD%E5%B7%9E)、南京、上海、[昆明](https://zh.wikipedia.org/wiki/%E6%98%86%E6%98%8E)、广州、[深圳](https://zh.wikipedia.org/wiki/%E6%B7%B1%E5%9C%B3)、[长沙](https://zh.wikipedia.org/wiki/%E9%95%B7%E6%B2%99)、[湘潭](https://zh.wikipedia.org/wiki/%E6%B9%98%E6%BD%AD)、[重庆](https://zh.wikipedia.org/wiki/%E9%87%8D%E6%85%B6)、武汉等20城市150所高校学生的串联响应。部分学生也借由示威活动反映对学校教育教学方式、校园环境和学生待遇的不满。

**Comment by ghost** [comment]
> 至少可以恶心你

《民政部关于对部分团体免予社团登记有关问题的通知》（民发〔2000〕256号）：“ 一、参加中国人民政治协商会议的人民团体不进行社团登记。参加中国人民政治协商会议的人民团体有：中华全国总工会、中国共产主义青年团、中华全国妇女联合会、中国科学技术协会、中华全国归国华侨联合会、中华全国台湾同胞联谊会、中华全国青年联合会、中华全国工商业联合会。”没有提及中共，因此中共仍需登记；未经民政部门登记、备案的组织，以社会组织名义开展活动，即为非法组织。

也就是说，“中共是非法政府”这句话在中国大陆也是正确的。不仅在美国等自由国家被打压，在中国大陆也有法律条文证明其非法。

**Comment by ghost** [comment]
> 至少可以恶心你

对的，这就是你的人生中的一大闪光点

**Comment by skygate2012** [comment]
你是恶心权贵关系网，还是恶心整理关系网的人呢？
