### ISSUE TITLE
脑残一般的玩意，跟run的作者一样

### ISSUE THREAD

**Issue by zhouxiaofu** [programthink/zhao#480]
国家冲刺阶段不进行添砖加瓦还他妈的拖后腿，恶心谁呢？就这还有10k的star，果然是学历越高越有汉奸潜质

**Comment by tonyqus** [comment]
怎么看出来这作者学历高的？

**Comment by ours1984** [comment]
建议多看v字仇杀队洗洗脑

**Comment by slightwangmin** [comment]
这是要冲刺准备大东亚圣战了？你这种脑残玩意被发配去作烧煤的薪柴倒是挺合适的

**Comment by ghost** [comment]
《民政部关于对部分团体免予社团登记有关问题的通知》（民发〔2000〕256号）：“ 一、参加中国人民政治协商会议的人民团体不进行社团登记。参加中国人民政治协商会议的人民团体有：中华全国总工会、中国共产主义青年团、中华全国妇女联合会、中国科学技术协会、中华全国归国华侨联合会、中华全国台湾同胞联谊会、中华全国青年联合会、中华全国工商业联合会。”

上面没有提及中共，因此中共仍需登记；未经民政部门登记、备案的组织，以社会组织名义开展活动，即为非法组织。这可是中共被自己制定的法律证明为非法政府。要说美国等西方国家打压中共还很常见，中共被自己的法律指出自己是非法的，这可就鲜为人知了。

**Comment by zzy-ac** [comment]
> 《民政部关于对部分团体免予社团登记有关问题的通知》（民发〔2000〕256号）：“ 一、参加中国人民政治协商会议的人民团体不进行社团登记。参加中国人民政治协商会议的人民团体有：中华全国总工会、中国共产主义青年团、中华全国妇女联合会、中国科学技术协会、中华全国归国华侨联合会、中华全国台湾同胞联谊会、中华全国青年联合会、中华全国工商业联合会。”
> 
> 上面没有提及中共，因此中共仍需登记；未经民政部门登记、备案的组织，以社会组织名义开展活动，即为非法组织。这可是中共被自己制定的法律证明为非法政府。要说美国等西方国家打压中共还很常见，中共被自己的法律指出自己是非法的，这可就鲜为人知了。

顯而易見的法盲吧你是？中共本來就不是政治協商會議的成員啊，執政黨和政協分不清也好意思出來秀智商嗎？

**Comment by luneice** [comment]
> 国家冲刺阶段不进行添砖加瓦还他妈的拖后腿，恶心谁呢？就这还有10k的star，果然是学历越高越有汉奸潜质

建这个仓库的人简直就脑残

**Comment by Dagwbl** [comment]
> 怎么看出来这作者学历高的？

学历确实不高，从他分析心理学那里的逻辑就可以看出，有没有本科都是个问题。

**Comment by dragonjay-lyj** [comment]
一个代码平台被搞的臭气熏天

**Comment by dragonjay-lyj** [comment]
> 国家冲刺阶段不进行添砖加瓦还他妈的拖后腿，恶心谁呢？就这还有10k的star，果然是学历越高越有汉奸潜质

别说，大部分Star的都是看乐子的

**Comment by VeraxLee** [comment]
国家冲刺阶段？房价民生民权没见冲刺，物价和管控倒是冲刺了。那你这大国冲刺和我什么关系？

**Comment by ours1984** [comment]
> 国家冲刺阶段？房价民生民权没见冲刺，物价和管控倒是冲刺了。那你这大国冲刺和我什么关系？

糊涂啊！无国哪有家！国家吃肉人民喝汤的！道理到底懂不懂！一样肤色和脸孔！吼！那你又要问国家吃肉谁在吃，你去听听二十大就知道了：共产党打江山，江山就是人民！

**Comment by unclefive55** [comment]
《社会契约论》诞生几百年了，当今社会还有如此之论，卢梭九泉下死不瞑目😅😅😅

**Comment by VeraxLee** [comment]
> > 国家冲刺阶段？房价民生民权没见冲刺，物价和管控倒是冲刺了。那你这大国冲刺和我什么关系？
> 
> 
> 
> 糊涂啊！无国哪有家！国家吃肉人民喝汤的！道理到底懂不懂！一样肤色和脸孔！吼！那你又要问国家吃肉谁在吃，你去听听二十大就知道了：共产党打江山，江山就是人民！

《社会契约论》诞生几百年了，当今社会还有如此之论，卢梭九泉下死不瞑目😅😅😅

**Comment by ours1984** [comment]
> > > 国家冲刺阶段？房价民生民权没见冲刺，物价和管控倒是冲刺了。那你这大国冲刺和我什么关系？
> > 
> > 
> > 糊涂啊！无国哪有家！国家吃肉人民喝汤的！道理到底懂不懂！一样肤色和脸孔！吼！那你又要问国家吃肉谁在吃，你去听听二十大就知道了：共产党打江山，江山就是人民！
> 
> 《社会契约论》诞生几百年了，当今社会还有如此之论，卢梭九泉下死不瞑目😅😅😅

国的家住在心里 家的国以和矗立
国是荣誉的毅力 家是幸福的洋溢
国的每一寸土地 家的每一个足迹
国与家连在一起 创造地球的奇迹
我爱我的国 我爱我的家
我爱我的国 我爱我的家
国是我的国 家是我的家
我爱我 国家

**Comment by unclefive55** [comment]
1.国家是表示：这个社会陷入了不可解决的自我矛盾，分裂为不可调和的对立面而又无力摆脱这些对立面。而为了使这些对立面、这些经济利益互相冲突的阶级，不致在无谓的斗争中把自己和社会消灭，就需要有一种表面上站在社会之上的力量来抑制冲突，把冲突保持在“秩序”的范围以内；这种从社会中产生但又居于社会之上并且日益同社会相异化的力量，就是国家。
“國家是階級矛盾不可調和的產物”

by 恩格斯《家庭，私有制与国家的起源》

2.No taxation without representation.无代表，不納稅。
 ( Jonathan Mayhew, 1750~1760 )

3.毛説：“現在谈愛国·那是愛誰的国？蒋介石的國吧？”“少数人的國，他們少數人去爱吧。”
“一個不是人民選舉出来的政府，有什麽脸面代表這個团家？爱這樣的国家，就是對祖國的背叛”
by 1946年大連大眾書店出版《毛選》

**Comment by VeraxLee** [comment]
> > > > 国家冲刺阶段？房价民生民权没见冲刺，物价和管控倒是冲刺了。那你这大国冲刺和我什么关系？
> > > 
> > > 
> > > 糊涂啊！无国哪有家！国家吃肉人民喝汤的！道理到底懂不懂！一样肤色和脸孔！吼！那你又要问国家吃肉谁在吃，你去听听二十大就知道了：共产党打江山，江山就是人民！
> > 
> > 《社会契约论》诞生几百年了，当今社会还有如此之论，卢梭九泉下死不瞑目😅😅😅
> 
> 国的家住在心里 家的国以和矗立
> 国是荣誉的毅力 家是幸福的洋溢
> 国的每一寸土地 家的每一个足迹
> 国与家连在一起 创造地球的奇迹
> 我爱我的国 我爱我的家
> 我爱我的国 我爱我的家
> 国是我的国 家是我的家
> 我爱我 国家

1.国家是表示：这个社会陷入了不可解决的自我矛盾，分裂为不可调和的对立面而又无力摆脱这些对立面。而为了使这些对立面、这些经济利益互相冲突的阶级，不致在无谓的斗争中把自己和社会消灭，就需要有一种表面上站在社会之上的力量来抑制冲突，把冲突保持在“秩序”的范围以内；这种从社会中产生但又居于社会之上并且日益同社会相异化的力量，就是国家。
“國家是階級矛盾不可調和的產物”

by 恩格斯《家庭，私有制与国家的起源》

2.No taxation without representation.无代表，不納稅。
( Jonathan Mayhew, 1750~1760 )

3.毛説：“現在谈愛国·那是愛誰的国？蒋介石的國吧？”“少数人的國，他們少數人去爱吧。”
“一個不是人民選舉出来的政府，有什麽脸面代表這個团家？爱這樣的国家，就是對祖國的背叛”
by 1946年大連大眾書店出版《毛選》

**Comment by VeraxLee** [comment]
> > > > 国家冲刺阶段？房价民生民权没见冲刺，物价和管控倒是冲刺了。那你这大国冲刺和我什么关系？
> > > 
> > > 
> > > 糊涂啊！无国哪有家！国家吃肉人民喝汤的！道理到底懂不懂！一样肤色和脸孔！吼！那你又要问国家吃肉谁在吃，你去听听二十大就知道了：共产党打江山，江山就是人民！
> > 
> > 《社会契约论》诞生几百年了，当今社会还有如此之论，卢梭九泉下死不瞑目😅😅😅
> 
> 国的家住在心里 家的国以和矗立
> 国是荣誉的毅力 家是幸福的洋溢
> 国的每一寸土地 家的每一个足迹
> 国与家连在一起 创造地球的奇迹
> 我爱我的国 我爱我的家
> 我爱我的国 我爱我的家
> 国是我的国 家是我的家
> 我爱我 国家

順便一提，我很討厭這首歌，當年團建我被迫拉出來去給這首歌指導手語，從那時起我就厭惡中國社會的這種體制了。 Doing task by force without feedback.

**Comment by luneice** [comment]
总有一些傻逼以某种合乎情理的逻辑，从某些地方断章取义的解读。用金灿荣老师的话讲，这类人就像苍蝇一样。总特么活在粪坑里。你特么觉得其他国家好赶紧特么移民，别特么像个傻逼一样。当然，任何组织社会都会存在问题矛盾，有建设性的意见和建议可以好好探讨。总特么有一波人碍事。

**Comment by luneice** [comment]
总有一些傻逼以某种合乎情理的逻辑，从某些地方断章取义的解读。用金灿荣老师的话讲，这类人就像苍蝇一样。总特么活在粪坑里。你特么觉得其他国家好赶紧特么移民，别特么像个傻逼一样。当然，任何组织社会都会存在问题矛盾，有建设性的意见和建议可以好好探讨。总特么有一波人碍事。

**Comment by luneice** [comment]
总有一些傻逼以某种合乎情理的逻辑，从某些地方断章取义的解读。用金灿荣老师的话讲，这类人就像苍蝇一样。总特么活在粪坑里。你特么觉得其他国家好赶紧特么移民，别特么像个傻逼一样。当然，任何组织社会都会存在问题矛盾，有建设性的意见和建议可以好好探讨。总特么有一波人碍事。

**Comment by VeraxLee** [comment]
> 总有一些傻逼以某种合乎情理的逻辑，从某些地方断章取义的解读。用金灿荣老师的话讲，这类人就像苍蝇一样。总特么活在粪坑里。你特么觉得其他国家好赶紧特么移民，别特么像个傻逼一样。当然，任何组织社会都会存在问题矛盾，有建设性的意见和建议可以好好探讨。总特么有一波人碍事。

那为什么张维为移民了呢🤣🤣🤣🤣

**Comment by xvivx** [comment]
> 总有一些傻逼以某种合乎情理的逻辑，从某些地方断章取义的解读。用金灿荣老师的话讲，这类人就像苍蝇一样。总特么活在粪坑里。你特么觉得其他国家好赶紧特么移民，别特么像个傻逼一样。当然，任何组织社会都会存在问题矛盾，有建设性的意见和建议可以好好探讨。总特么有一波人碍事。
就是你这种满嘴不干净的人撑起了国家的文明
