### ISSUE TITLE
此仓库建得好

### ISSUE THREAD

**Issue by Dagwbl** [programthink/zhao#492]
为什么建得好，因为有助于团结和唤醒各位仁人志士。

每个人出身谁能做主？家和国都是一出生就注定了的，按照社会发展模式，国本来就是家的延伸，哪儿养育你，你就守护哪儿就行了。

天天吵吵，企图各种方式渗透，改变别人的想法和自己的家国对立？用点高级的手段吧。

不管你在台湾还是在美国，还是在大陆，最重要的是过好自己的生活，再有多余能力多考虑建设好自己国家，OK？

别像个傻逼一样知道点以前政府犯的错误，就哔哔赖赖嘲笑别人。

不止以前政府会犯错误，现在也会，将来也会！

世界上任何一个国家都会！

有能力就改变自己的家庭，改变自己的国家，让他变得更好，没能力就尽力照顾好自己就行了，而不是像个没有脑子吃里扒外的东西，自己对家国无益，甚至还帮助外人企图唾骂毁掉自己的家国。

真的无语，老子就想上来学点新奇的东西，纯纯被你恶心到了，你建这个仓库你就建，没谁会说你啥，本来这个仓库也就是幸存者效应，啥都不是的普通人你也不写上来？就是别tm在readme夹带一些阴阳怪气的话行不行？世界的蛀虫，人类之耻！

**Comment by a9** [comment]
全中国人或多或少都知道政府以前犯过的错，大家最多就是惊讶一下。为什么？
  因为民众知道好歹，知道和平来之不易。民众知道有个可以建国的政府能够保障大部分不作死的人的生命安全，知道有个政党领导人民救活了一个破碎不堪的文明古国。
  中国人看重的是未来，这个星球上中华文明可以一直延续，历史是好是坏爱谁谁写，只要不是那些欺负过我们的人写就行。
  都可以翻墙啊，为什么看不到战火和动乱都财产在哪些国家，和平稳定在哪些国家呢？是个人认知导致的双标还是蓄意图谋胡乱引导明眼人看清楚了。
  每个国家的政府不是生来就会治理国家的，你指望一个野生的政党天生就给你把国家治理的妥妥贴贴的，没有缺点没有敌人？美国那帮乌七八糟的政府还不是把国家治理的妥妥贴贴的，是不是得暴乱也可以妥善镇压。
  奉劝打简体字的各位，打字前想想自己现在身处的位置，想想你的祖先是哪个民族。
  中国这片国土上，几千年各个朝代分分合合，有国家治理的好的朝代，也有不好被推翻的。但是那是我们自己民族文化和历史的内部演变，轮不到别的民族和国家指手画脚，更不想我们自己人还打自己人得脸！

**Comment by 8964bj** [comment]
人犯错要负法律责任，政府犯错就算了？害死几千万人叫犯错吗？犯罪不被清算还能继续骑在人民头上拉屎。草

**Comment by a9** [comment]
> 人犯错要负法律责任，政府犯错就算了？害死几千万人叫犯错吗？犯罪不被清算还能继续骑在人民头上拉屎。草

https://zh.m.wikipedia.org/zh/%E5%8D%B0%E7%AC%AC%E5%AE%89%E5%A4%A7%E5%B1%A0%E6%AE%BA%E5%88%97%E8%A1%A8

洗洗睡吧，又不是只有中国政府干过这事。是个政府都会有昏庸的时段，有本事你就推翻他，口花花的有什么用。
你让谁来清算呢？你自己？还是找别的国家来清算呢？还是你自己创建个新党派自己成军？

这个党派已成气候，在你有生之年看看能不能看到它倒台，我估计你是看不到了。

看不到还吐槽有啥用呢，反过来想想，它的过错给你照成什么影响了呢？如果它倒台到底是谁来上台，你能决定吗？

不能决定就闭嘴，口嗨嗨而已。这种口嗨不明智。生活还得继续对吧。

**Comment by Dagwbl** [comment]
傻逼，你自己想想国家颠覆会造成什么样的后果，到时候这又是不是犯错，为啥非要一错再错

**Comment by zhangchi25806** [comment]
国家如果颠覆了就怪人民，国家如果变好了就谢政府
挺可爱的
