### ISSUE TITLE
you can you up

### ISSUE THREAD

**Issue by a9** [programthink/zhao#493]
全中国人或多或少都知道政府以前犯过的错，大家最多就是惊讶一下。为什么？ 因为民众知道好歹，知道和平来之不易。民众知道有个可以建国的政府能够保障大部分不作死的人的生命安全，知道有个政党领导人民救活了一个破碎不堪的文明古国。 中国人看重的是未来，这个星球上中华文明可以一直延续，历史是好是坏爱谁谁写，只要不是那些欺负过我们的人写就行。 都可以翻墙啊，为什么看不到战火和动乱都出现在哪些国家，和平稳定在哪些国家呢？是个人认知导致的双标还是蓄意图谋胡乱引导明眼人看清楚了。 每个国家的政府不是生来就会治理国家的，你指望一个野生的政党天生就给你把国家治理的妥妥贴贴的，没有缺点没有敌人？美国那帮乌七八糟的政府还不是把国家治理的妥妥贴贴的，时不时的暴乱也可以妥善镇压。 奉劝打简体字的各位，打字前想想自己现在身处的位置，想想你的祖先是哪个民族。 中国这片国土上，几千年各个朝代分分合合，有国家治理的好的朝代，也有不好被推翻的。但是那是我们自己民族文化和历史的内部演变，轮不到别的民族和国家指手画脚，更不想我们自己人还打自己人得脸！

**Comment by dragonjay-lyj** [comment]
正解

**Comment by 8964bj** [comment]
放屁

**Comment by xijinping0** [comment]
支持！中华民族的希望，看得靠我们党，靠习近平。

![68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f46665533584c49565541415f656c323f666f726d61743d6a7067266e616d653d736d616c6c](https://user-images.githubusercontent.com/111333464/196914442-5547dc41-ae29-46eb-a9c1-3a93760d2059.jpeg)
