### ISSUE TITLE
既然你們如此自私到不管他人死活

### ISSUE THREAD

**Issue by itisbenjamin** [programthink/zhao#51]
既然你們覺得所有人的死活都和你們無關。
所有災禍的受害者，被欺壓的人們都和你們無關。
這些當權者肆意橫行和你們無關。

那麼。

現在就滾回牆裡去。

你們是死是活要不要用Github也和我們無關。

誰管你。

---

2016-04-09
我覺得這個 issue 裡的回覆都很讓我噁心，所以關閉。

**Comment by vczh** [comment]
这话我就不爱听了。当权者怎么就不管人民死活了，从被八国联军、日本和美国蹂躏到了195x年，用了几十年发展成这样，这才是政府对人民最大的贡献。

**Comment by antipoliongithub** [comment]
@itisbenjamin 你说话的口吻跟GCD在上个世纪二三十年代说的话真是很像啊，一副愤世嫉俗的样子。偌大一个中国就算是GCD下课了，交给你这等人，怕是人民大众的生活更要陷入水深火热之中。

你这等人，自己所谓的革命志士，不论身处何土何时，除了反抗还是反抗，在中国反GCD，在中东大概就是人肉炸弹，因为你这等人内心就是黑暗的，如你自己所说“_我覺得每個人都會有一種自我毀滅的傾向，有時候我的確想毀掉這一切_”，所以你才会觉得“_這個國已經沒救了，而我也已經沒救了。_”。你有没有救没关系，但是请你不要动辄拿出“_所有人的死活_”这样的字眼出来吓人，你代表不了所有人。

孔子说“不在其位不谋其政”，反过来就是让人们“各司其职”，每个人把自己的本质工作做好了，社会自然就好了。GCD有没有做好我不去谈，但起码作为自己，我认为我在为自己的职位尽职尽责，我在为这个社会做出贡献。我不会认为“這個國已經沒救了”，我更不会认为我自己没救了。

对你这等自己想死还想拉着别人去死的人，我指向说：我呸！

**Comment by itisbenjamin** [comment]
@antipoliongithub

蛤蛤，昨天特意發了一篇釣魚文，沒想到還真是上鉤了。
你不覺得我那篇文章漏洞很大？我就憑一晚上的時間，還喝多了，能寫出一個主題？
我真厲害喔。

我既然選擇隱匿，那麼所有的用詞都是推敲過的，怎麼可能會被你這種被人戳穿惱羞成怒一口氣回覆這麼多issue的人抓住把柄。

每個issue都挨個回一遍，真是辛苦你了。

還有你這種人永遠都是奴性不改，誰說我要上台了？
你們就不能自己選個人上台？

拜託，能不能動用點你那可憐的腦子。

我都快笑死了。

你既然是Github使用者，拿出自己的帳號啊，頂著一個什麼都沒有的空號，只能說明你是五毛。

**Comment by itisbenjamin** [comment]
@vczh 

呵呵。

**Comment by justjavac** [comment]
轮带逛
