### ISSUE TITLE
最近更新都是五年前，估计是资金断裂，最近又有新资金注入了。大家举报了就好，维护社区环境

### ISSUE THREAD

**Issue by AelepantB** [programthink/zhao#519]
![网页捕获_26-3-2023_214727_github com](https://user-images.githubusercontent.com/104605918/227780212-81450c28-7791-44ce-bfd7-6a9f5d7185a5.jpeg)
![屏幕截图 2023-03-26 214750 (2)](https://user-images.githubusercontent.com/104605918/227780377-56bf33ae-d489-48cd-b3df-7a9d827f9054.jpg)

**Comment by tonyqus** [comment]
我都等了10年了，这个repo不知道被举报了多少次了，我就没见过有人成功过

**Comment by tonyqus** [comment]
`AelepantB is united with all Russians and people of Ukraine who not being brainwashed by government- and corporate-controlled news media.` 

所以你是俄粉？能给我说说你支持俄罗斯的理由吗？

**Comment by AelepantB** [comment]
我的立场同俄罗斯人民与没被洗脑的乌克兰人民站在一起。与github官方社区的立场不同，github官方只和乌克兰站在一起。

前段时间，在联合国大会上为俄乌冲突进行了两次默哀。一次是乌克兰发起的，为纪念当时遇难的乌克兰人；第二次是俄罗斯发起的，为纪念从2014年开始所有遇难的乌克兰人和俄罗斯人。中国代表只在第二次默哀时起立了。

如果想聊聊具体的理由，先谈谈你的看法

**Comment by jhdxr** [comment]
简中互联网低学历低智商用户的典型特征：中国所有的问题，不是资本指使的，就是海外情报部门赞助来抹黑的。

**Comment by Naville** [comment]
[庚子俄难](https://zh.wikipedia.org/wiki/庚子俄难) 怎么回事呢

**Comment by AelepantB** [comment]
> 简中互联网低学历低智商用户的典型特征：中国所有的问题，不是资本指使的，就是海外情报部门赞助来抹黑的。

在一个技术社区看到了键政的帖子本来就够让人恶心，社区还不管理（为什么不管理呢？）跟更恶心的是，进了厕所帖子就一定会踩到狗屎。

是不是，翔同志

**Comment by tonyqus** [comment]
这个repo本来就是政治类repo，谁规定github只能搞编程技术类repo的？你是不是墙内呆太久了，被洗过头了。如果Github不允许非技术类repo，那恐怕不可能成为全球最流行的开源平台。反观国内的平台各种莫名其妙的审查才叫恶心，我从来不用，我只想做个正常人。

**Comment by AelepantB** [comment]
> 这个repo本来就是政治类repo，谁规定github只能搞编程技术类repo的？你是不是墙内呆太久了，被洗过头了。如果Github不允许非技术类repo，那恐怕不可能成为全球最流行的开源平台。反观国内的平台各种莫名其妙的审查才叫恶心，我从来不用，我只想做个正常人。

呦，你还知道github是开源平台啊。拿github键政还振振有词，就这还想做正常人，脑子不知道干啥用的？你不会还支持乌克兰吧，你是不是还支持台湾独立啊，日本殖民你是不是也觉得挺好的

**Comment by AelepantB** [comment]
> 这个repo本来就是政治类repo，谁规定github只能搞编程技术类repo的？你是不是墙内呆太久了，被洗过头了。如果Github不允许非技术类repo，那恐怕不可能成为全球最流行的开源平台。反观国内的平台各种莫名其妙的审查才叫恶心，我从来不用，我只想做个正常人。

呦，你还知道github是开源平台啊。拿github键政还振振有词，就这还想做正常人，脑子不知道干啥用的？你不会还支持乌克兰吧，你是不是还支持台湾独立啊，日本殖民你是不是也觉得挺好的

**Comment by Naville** [comment]
别转移话题啊 你鹅爹屠华的事情你怎么评价呀亲爱的

**Comment by AelepantB** [comment]
> 别转移话题啊 你鹅爹屠华的事情你怎么评价呀亲爱的

没有屠杀印第安人过分，也没贩卖黑奴过分，从数量上就不是一个量级。

这件事告诉我永远不要试图进一个肮脏的厕所，踩一脚翔真是晦气

**Comment by jhdxr** [comment]
> > 简中互联网低学历低智商用户的典型特征：中国所有的问题，不是资本指使的，就是海外情报部门赞助来抹黑的。
> 
> 在一个技术社区看到了键政的帖子本来就够让人恶心，社区还不管理（为什么不管理呢？）跟更恶心的是，进了厕所帖子就一定会踩到狗屎。
> 
> 是不是，翔同志

一些小知识：
1. 你不是第一个想举报的，也不是声音最大的——这个repo中国政府已经举报过了，github也进行过处理了。所以如果你是在墙内直接访问应该看到是一个451
1. 翻墙在中国大陆地区是违法行为。不信你可以去警察局报警试试，不管是举报这个repo还是举报其他三观正常的用户，看看谁会被处罚
2. Github **不只是** 技术社区。你可以点开 Community Guideline看看，
> We are committed to making GitHub an environment that welcomes all the different voices and perspectives our community has to offer, while maintaining a safe place for developers to do their best work.

墙内的太监当久了，总需要一些主子管着自己。一条活在厕所里的狗跑到外面来还急不可耐地向主子表示忠心，可笑可笑。

**Comment by AelepantB** [comment]
> > > 简中互联网低学历低智商用户的典型特征：中国所有的问题，不是资本指使的，就是海外情报部门赞助来抹黑的。
> > 
> > 
> > 在一个技术社区看到了键政的帖子本来就够让人恶心，社区还不管理（为什么不管理呢？）跟更恶心的是，进了厕所帖子就一定会踩到狗屎。
> > 是不是，翔同志
> 
> 一些小知识：
> 
> 1. 你不是第一个想举报的，也不是声音最大的——这个repo中国政府已经举报过了，github也进行过处理了。所以如果你是在墙内直接访问应该看到是一个451
> 2. 翻墙在中国大陆地区是违法行为。不信你可以去警察局报警试试，不管是举报这个repo还是举报其他三观正常的用户，看看谁会被处罚
> 3. Github **不只是** 技术社区。你可以点开 Community Guideline看看，
> 
> > We are committed to making GitHub an environment that welcomes all the different voices and perspectives our community has to offer, while maintaining a safe place for developers to do their best work.我们致力于使 GitHub 成为一个欢迎我们社区必须提供的所有不同声音和观点的环境，同时为开发人员提供一个安全的地方来发挥他们最好的工作。
> 
> 墙内的太监当久了，总需要一些主子管着自己。一条活在厕所里的狗跑到外面来还急不可耐地向主子表示忠心，可笑可笑。

进厕所总有一堆蛆围上来，还是厕所的烂蛆。读读你的你写的，连基本的逻辑都没有。GIthub只会处理骂美国政府揭露美国财阀的，你发一个拜登的关系图上来？

进厕所本来就恶心，本来想搞搞卫生，围上来一堆烂蛆，这些蛆在厕所呆久了看到人都激动。估计平时也没什么人理这些烂蛆

**Comment by zhangchi25806** [comment]
你问他为什么饿着肚子，他会跟你说，王老爷家的大儿子，年轻的时候，有一个早吃了三个馒头，噎得打了几十个隔，哎呀，可是笑死人了。
