### ISSUE TITLE
原来这个哥们是个无业游民

### ISSUE THREAD

**Issue by Insua** [programthink/zhao#520]
大学也没念完。。。。

**Comment by ghost** [comment]
上不上大学都没关系，网上可以学知识。

**Comment by tonyqus** [comment]
对对，无业游民拿到了上海户口，目前他所在小区的房子均价8w-9w。

请问你搞定上海户口了吗？ 买得起上海的房子吗？@Insua

**Comment by Jason111112** [comment]
无业游民能当上奥运会信息系统总工，你能吗？

**Comment by huangkj** [comment]
比你当5毛强多了

**Comment by Kusou1** [comment]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/57334674/229015090-38460a0a-b9be-4d2c-a159-c4d0e3d85cd9.png">

**Comment by xiwinnie8964** [comment]
你这是在讽刺谁？胆儿挺肥啊。

**Comment by Mo-Tu** [comment]
![image](https://user-images.githubusercontent.com/104690150/229660153-df5f80c2-8db4-460d-a755-49d1351aa71a.png)

**Comment by ghost** [comment]
> 大学也没念完。。。。

全球10大最成功的退学创业的富豪：
第一名、微软创始人比尔·盖茨，身价1490亿美元，从哈佛退学。
第二名、Facebook创始人扎克伯格，身价1290亿美元，从哈佛退学。
第三名、谷歌创始人拉里·佩奇，身价1170亿美元，从密歇根大学退学。
第四名、甲骨文公司创始人拉里·埃里森，身价1010亿美元，从伊利诺伊大学退学。
第五名、西班牙服装公司Inditex（Zara品牌）的创始人阿曼西奥·奥特加，身价747亿美元，从学校辍学。
第六名、戴尔公司创始人迈克尔·[戴尔](https://xueqiu.com/S/04331?from=status_stock_match)，身价490亿美元，从得克萨斯大学退学。
第七名、和记黄埔创始人李嘉诚，身价340亿美元，从学校辍学。
第八名、Facebook的联合创始人达斯汀·莫斯科维茨，身价209亿美元，从哈佛大学退学。
第九名、推特、Square创始人杰克·多西，身价137亿美元，从密苏里州科技大学退学。
第十名、WhatsApp创始人简·库姆，身价132亿美元，从圣何塞大学退学

**Comment by Subdue0** [comment]
我们早就被生长环境给洗脑咯！包括我自己，也深受生长环境洗涤。我们的潜意识认为，人一定要有一份工作，一定要有点钱，一定要结婚生子，即便自己不承认这些，但细想自己，想要的东西，也是大框架中的。

**Comment by run2763** [comment]
华语油管推荐列表
https://github.com/run2763/awesome-youtubers

**Comment by liu89501** [comment]
你不也就这水平，反驳的没有一点说服力，我看你连人家一根屌毛都不如

**Comment by InfinityDJKing** [comment]
> > 大学也没念完。。。。
> 
> 全球10大最成功的退学创业的富豪： 第一名、微软创始人比尔·盖茨，身价1490亿美元，从哈佛退学。 第二名、Facebook创始人扎克伯格，身价1290亿美元，从哈佛退学。 第三名、谷歌创始人拉里·佩奇，身价1170亿美元，从密歇根大学退学。 第四名、甲骨文公司创始人拉里·埃里森，身价1010亿美元，从伊利诺伊大学退学。 第五名、西班牙服装公司Inditex（Zara品牌）的创始人阿曼西奥·奥特加，身价747亿美元，从学校辍学。 第六名、戴尔公司创始人迈克尔·[戴尔](https://xueqiu.com/S/04331?from=status_stock_match)，身价490亿美元，从得克萨斯大学退学。 第七名、和记黄埔创始人李嘉诚，身价340亿美元，从学校辍学。 第八名、Facebook的联合创始人达斯汀·莫斯科维茨，身价209亿美元，从哈佛大学退学。 第九名、推特、Square创始人杰克·多西，身价137亿美元，从密苏里州科技大学退学。 第十名、WhatsApp创始人简·库姆，身价132亿美元，从圣何塞大学退学

李嘉诚是因为没钱才辍学的吧

**Comment by Insua** [comment]
承德程序员事件爆发后 我深刻的认识到了自己以前的浅薄 这个习家帝国祝早日灭亡
