### ISSUE TITLE
有这闲心为什么不去解密一些美国的权贵家族呢？

### ISSUE THREAD

**Issue by youmingdot** [programthink/zhao#59]
一心在中国搞煽颠，不知道吃的是孙家还是李家的饭。

另外，别TM一堆人在下面起哄，你们以为推翻了政府你们上台国家就能富强？也不看看你们美爸的自由明主推行到哪，哪里就遭殃，光以为自由民主好，吃不饱穿不暖也觉得自由民主好，到底是谁没脑子。

**Comment by gmail12** [comment]
我今天最后一次浪费口水了.
党是亲美的.






 
Sender: 有明
Send Time: 2016-06-23 21:08
Receiver: programthink/zhao
Subject: [programthink/zhao] 有这闲心为什么不去解密一些美国的权贵家族呢？ (#59)
一心在中国搞煽颠，不知道吃的是孙家还是李家的饭。
另外，别TM一堆人在下面起哄，你们以为推翻了政府你们上台国家就能富强？也不看看你们美爸的自由明主推行到哪，哪里就遭殃，光以为自由民主好，吃不饱穿不暖也觉得自由民主好，到底是谁没脑子。

**Comment by ccpBuster** [comment]
没错，所以你这种支那猪贱畜也只配当个贱奴。

**Comment by youmingdot** [comment]
你们要闹要曝光去该去的地方，来这里博什么感情，这里是搞程序的地方。好嘛，我和别人吵架，去你家闹，非要你管，这是什么，这是绑架。就这点能耐也只能天天在墙外闹了，还好有堵墙，你们来不了我家闹。

**Comment by huangyeshudian** [comment]
“有这闲心为什么不去解密一些美国的权贵家族呢？”因为我不是美国人啊。。。

**Comment by MrCoder** [comment]
有这个闲心为什么要去解密美国的权贵家族呢？自己的闲心难道不是想用在什么地方用在什么地方吗？

**Comment by xuxiansenTaurus** [comment]
楼主是逗逼么？美国的事情有美国国民管，需要你管么？

**Comment by yfszzx** [comment]
@xuxiansenTaurus 楼主不是逗逼，楼主是傻逼

**Comment by BennyThink** [comment]
因为博主是中国人。诉诸恐惧。
