### ISSUE TITLE
Github上最无聊的“项目”

### ISSUE THREAD

**Issue by nipao** [programthink/zhao#65]
翻来翻就那些个破文章
起趁早关了吧

**Comment by q6286142** [comment]
确实很无聊，都为黑而黑。。。

**Comment by XYScience** [comment]
没事干闲的蛋疼。知道那么多，你咋不上天啊。别污染了github！

**Comment by soulofc** [comment]
5毛楼主，滚，你主子说了不走西方的一套，你来西方办的网站干什么？楼主滚出github

**Comment by nipao** [comment]
@soulofc 你真的很无聊，而且还无口德
就此中止，别再回复，你继续经营你这伟大的项目吧
