### ISSUE TITLE
傻逼项目傻逼的作者

### ISSUE THREAD

**Issue by zacharyzh** [programthink/zhao#69]
你非你妈个逼的把政治牵扯到技术领域嘛？死全家的玩意儿。你特么这么牛逼怎么不去天安门示威。窝囊狗。

**Comment by zacharyzh** [comment]
最瞧不起你这些没有本事，就知道骂政府的人。

**Comment by xuxiansenTaurus** [comment]
里面哪里骂政府了，只是把人员之间的关系，职位写出来了，系统整理了下，
连这点逻辑思维都没有，还是别做程序员了吧。

**Comment by soulofc** [comment]
5毛急了，哈哈，支持作者，14亿个顶

**Comment by GreatFireChina** [comment]
五毛看看我们这个 https://github.com/greatfire/wiki/ 估计更加激动了

**Comment by zacharyzh** [comment]
5毛。。。

我只想说，如果你那么牛逼你就坐到那个位置上面去。如果坐不到你又要怪谁呢。你只能怪你老祖宗没去打鬼子啊。

最讨厌以侮辱别人来哗众取宠的人。有本事你上，不行就别特么逼逼。

**Comment by zacharyzh** [comment]
真尼玛没出息。我中华民族五千年文化，如今怎么净出你们这种玩意儿。

**Comment by loveyanbei** [comment]
66666,五毛来github来了？

**Comment by KamikazeChan** [comment]
奴才做慣了，說話就這樣，不用理這傻逼了

**Comment by clhaaaa** [comment]
https://github.com/programthink/zhao/issues/38那你们这是几个意思？zhao项目把人员之间的关系写出来这个没啥的，issues38就纯属造谣了，习仲勋是有心脏病的，当年开会发作，当时江泽民还给他喂药。这个是查得到的。我只想说，你们写代码写多了脑子也坏了是吗？非要搞得github被墙是吗？我身在墙外这事情对我没有影响，可是国内的用户会因为你们增加多少困扰呢？

**Comment by Meng-Gen** [comment]
你不要生氣啦，每個人價值觀本來就有所不同，如果想要強迫別人都接受你的觀點，除非你是包子帝，可是共產黨就一位包子帝，順從包子帝的遊戲規則，究竟是個人自由選擇，還是被自由的選擇，這值得想想。有想過其他國家根本不屑牆 github 的原因嗎？

**Comment by Snrat** [comment]
不用理这货，估计神经病吧。。不想骂人说脏话。

**Comment by etata** [comment]
我最瞧不起@zacharyzh 你牛逼你把zhao项目关了啊。就知道瞎几把比比。

**Comment by etata** [comment]
@clhaaaa 你煞笔啊，这是开源，自由提交。难道因为你这个人垃圾，就不让你提交代码了？

**Comment by CANGJINKONG** [comment]
@zacharyzh 正是因为自由在中国屡遭封杀才有编程随想等人的存在，通过Github反抗可以用最少成本得到最大效果。你可以表达自己的观点，但脏话很难受到别人的欢迎
@GreatFireChina 根据我的经验，五毛党通常为了挣钱复制粘贴，人畜无害，从来不会跟别人吵架，把政治倾向与你相反的人扣一顶五毛的帽子不是高素质的表现

**Comment by youhaibo** [comment]
这些信息是不是已经涉及到了国家安全了？

**Comment by loveyanbei** [comment]
@youhaibo 公布财产=国家安全，这个洗地0分

**Comment by zacharyzh** [comment]
@CANGJINKONG 天天没本事就知道喷自己国家的人，看不起。这种人只能骂，无话可讲。

**Comment by fuckzacharyzh** [comment]
你他妈有本事？一看就知道你丫就是个在北京的外地逼，有本事怎么不去建设自己家乡，抢占我北京的工作资源，臭傻逼滚回外地

**Comment by zacharyzh** [comment]
5毛本性暴露无遗，马甲都穿上了

**Comment by cjtcthr** [comment]
你妈死了废物

**Comment by cjtcthr** [comment]
你非你妈个逼的把你的傻逼气息牵到这里来嘛？死全家的玩意儿。你特么这么牛逼怎么不去白宫示威。窝囊狗。

**Comment by cjtcthr** [comment]
你真是一只滞纳死猪

**Comment by MrPresidentCh** [comment]
请问，就算是骂土共，就等于人家没本事吗？如果你连这逻辑都想不明白，我觉得你真不应该搞程序，因为程序需要逻辑思维，你显然不行。

**Comment by cjtcthr** [comment]
@zacharyzh 你妈死了

**Comment by uroot666** [comment]
@zacharyzh 你这种SX居然会用github表示值得鼓励。

**Comment by SinGeno** [comment]
@zacharyzh 上来就骂街，除了彰显素质低下，还有其他？

> 你非你妈个逼的把政治牵扯到技术领域嘛？死全家的玩意儿。你特么这么牛逼怎么不去天安门示威。窝囊狗。

按照你这个逻辑，对中国政府不满意，就要去政府的象征地示威。 那你对这个项目不满意，也没见你去GITHUB门口示威啊。

> 我只想说，如果你那么牛逼你就坐到那个位置上面去。如果坐不到你又要怪谁呢。你只能怪你老祖宗没去打鬼子啊。

你牛逼，你做到GITHUB项目管理的位置上，把项目删了呀。如果坐不到你又要怪谁呢。你只能怪你老祖宗没把你生在美国？

**Comment by yj19810322** [comment]
@zacharyzh  你妈个屄的把非要把傻屄气息带到技术领域嘛？死全家的玩意儿。你特么这么牛逼怎么不去19大上抗议示威GFW。窝囊狗。
最瞧不起你这种没有本事，就知道骂项目作者的人。真是当奴才跪久了站不起来了。

**Comment by YrlixJoe** [comment]
反对在github上讨论政治的声音充分表明，共匪愚民、奴民政策的成功 #40

**Comment by SinGeno** [comment]
@zacharyzh commented on Jul 23, 2016

@CANGJINKONG 天天没本事就知道喷自己国家的人，看不起。这种人只能骂，无话可讲。
--

這句話說你自己的時候，一點錯都沒有，就你這個智商還要上github，怪不得只能咋呼。

**Comment by zacharyzh** [comment]
窝囊狗太多，惹不起你们。你们好自为之吧。
