### ISSUE TITLE
实在为Github的前途担忧。以前不是有VPN项目被强制下线的教训吗

### ISSUE THREAD

**Issue by zhongyang** [programthink/zhao#7]

**Comment by yeahwu** [comment]
github的翻墙项目不要太多好吧，不会翻墙还有脸在github上混？

**Comment by yeahwu** [comment]
给你普及一下吧。
XX-Net，Shadowsocks，Lantern，Goagent，Goproxy，v2ray，torproject……
github的翻墙项目不要太多好吧，不会翻墙还有脸在github上混？

**Comment by posclegom** [comment]
只要不是违反GitHub的ToS的内容都可以放在GitHub上，楼主不要做精赵，不要自我阉割，不要做奴才。

**Comment by panzer1313208** [comment]
@zhongyang github又不是国内软件。可能被强制下线吗？VPN是作者泄露了个人信息然后被共产党查水表了吧？跨省追捕？网警？跟github没关系。

**Comment by chitanda** [comment]
说的是SS吧。。作者一直用的通用ID，而且人在国内。so...

**Comment by zhongyang** [comment]
@posclegom,我竟然无言以对，太偏激

**Comment by posclegom** [comment]
＠panzer1313208 我看你说的对

**Comment by posclegom** [comment]
另外楼主，抱歉如果我看起来太偏激。每当我看到呼吁自宫的太监言论我就感觉很讨厌。

**Comment by antipoliongithub** [comment]
@posclegom ，你大概自己觉得是“我自横刀向天笑”，其实比起“引刀成一快”都远远不如，就别再四川跳梁了
