### ISSUE TITLE
墙内程序员必须说一句

### ISSUE THREAD

**Issue by dxhisboy** [programthink/zhao#74]
为什么不弄到wiki？弄到github几个意思？

**Comment by nipao** [comment]
傻逼呗，还有什么意思
看过，笑过就算了

**Comment by Hit410** [comment]
都是些奇葩，wiki是分散的，這裏做集合。況且人家放哪裏干你們P事？他拉屎你們是不是也要趕來擦擦？

**Comment by GreatFireChina** [comment]
请看我们的wiki https://github.com/greatfire/wiki/

**Comment by KamikazeChan** [comment]
憑什麼不能弄到github，github是你趙家人開的網站？

**Comment by Martin-Tan** [comment]
成天搞这些哗众取宠的幺蛾子。等Github 被block之后我还要花更多的精力去寻找代码。F**k you!!

**Comment by KamikazeChan** [comment]
連翻墻都不會還當什麼程序員,回家養豬吧

**Comment by dxhisboy** [comment]
> 連翻墻都不會還當什麼程序員,回家養豬吧
人在墙内，虽然网不在，不然应该451了吧。

**Comment by dxhisboy** [comment]
>成天搞这些哗众取宠的幺蛾子。等Github 被block之后我还要花更多的精力去寻找代码。F**k you!!

斯德哥尔摩。。。

**Comment by honokachika** [comment]
233
笑看。

**Comment by OxygenLiu** [comment]
我看这个项目很好！墙内的程序猿们，是抬头做人的时候了

**Comment by honokachika** [comment]
就是就是。

**Comment by jazy1982** [comment]
在笼子里待习惯了的鸟会认为飞翔是一种病！
