### ISSUE TITLE
这种东西，墙就墙了吧

### ISSUE THREAD

**Issue by wuwen1030** [programthink/zhao#78]
披着自由的外衣在这为了反对而反对，不过又是另一政治喉舌而已，请还Github个清净。

**Comment by hypogaea** [comment]
@wuwen1030 喷子还有xx分钟到达战场，碾碎他们:joy:

**Comment by bugparty** [comment]
部分被墙，为github的机智点赞

**Comment by hypogaea** [comment]
@bugparty 这样挺好的，完美地规避了中国大陆的政策限制，又保障了广大程序猿的利益。这才是良心企业啊。

**Comment by Meng-Gen** [comment]
人不能為了反對而反對嗎？

當你覺得這句話有問題，你也在反對「為了反對而反對」。人性本來就有各種面貌，我們要做的是容忍，而不是統一化。

**Comment by bugparty** [comment]
是啊

**Comment by ccpBuster** [comment]
呵呵
粪坑蛆竟然有底气叫嚣“还Github个清净”，雾霾吸太多脑子瓦特了，傻逼！

**Comment by xuruoyu** [comment]
这些人应该去facebook上发这种信息，反正被封了，而不是在github上搞这套，好好的代码分享网站搞成了政治宣传网。。。

**Comment by soulofc** [comment]
你这种人该滚出github，你主子说了不搞西方那套，你来西方人搞的网站干什么？你当这里是墙内啊，煞笔，对屁民满是手段，在民主国家你和你主子啥都不是，想在这里撒泼，门都没有

在 2016-07-15 02:40:59，xuruoyu <notifications@github.com> 写道：


这些人应该去facebook上发这种信息，反正被封了，而不是在github上搞这套，好好的代码分享网站搞成了政治宣传网。。。

**Comment by MrPresidentCh** [comment]
墙内有很多托管，你可以用墙内的，外国是自由世界，自我审查价值观不符合人类世界。

**Comment by MrPresidentCh** [comment]
连喉舌的含义都不懂，A控制B，那么B称为喉舌，请问人家编程啥时候被什么具体人物控制了，立场也算是喉舌吗？别歪曲了。请提供必要证据。你国媒体是你党控制的，控制的依据是自我审查与gfw。

**Comment by MrPresidentCh** [comment]
啥是自由外衣？民主制的宽容限度在于不能宽容反对民主制的人，其目标就是法西斯主义。
你可以自由在这讨论，但是你利用人家给予你自由的权力来反这里的自由体制，那么你就是法西斯主义。你犯了法西斯主义，法西斯就是利用自由选举制度上台搞独裁的。
因此，自由民主国家，唯一需要反的就是，想利用人家的自由体制，而反自由体制的人。

**Comment by lanhin** [comment]
乌烟瘴气，不敢苟同

**Comment by kimchi-shi** [comment]
大家都想荫蔽家族，后代，但是不代表合法，有这种家族图的出现，只能说人民英雄纪念碑代表的那些烈士的血都白流了。
其次，我们就是应该在github这种地方发，越是能够给国内的程序员制造障碍，才越能激化他们和TG的矛盾。
只有国内的矛盾激化到一定程度了，才可能团结国内的同志，才可能有所改变。
