### ISSUE TITLE
不管怎么样，至少我在中国过的很好。

### ISSUE THREAD

**Issue by Meteor-fly** [programthink/zhao#79]
虽然不知道作者你是哪个国家的，出于什么目的。
也不管你里面的内容是真实的还是虚假的，至少我们目前看到的都是真实的。
换句话说，如果天下是你打下来的，你怎么为你的后代谋福利，我都无话可说。
但是你不是，不能说中国的领导人百分百的完美，但是能够看到他们为中国带来的改变，那么多飞机失联，什么时候中国的飞机失联了？那么多国家的人被ISIS杀害，什么时候看到过中国人被ISIS杀掉的？
不管我们的政府为此付出了什么，总之我明白一件事，我们国家没有硝烟，没有战争，起码还能让你们一群白眼狼在这里上网喷自己的国家，而不像叙利亚的同胞无家可归。

至于防火墙？国家不想让你上外网你以为就你那点水平能突破的了？把海底光缆断了，你什么SSH，VPN，管用吗？

醒醒吧，中国现在发展的太快，国外有些组织眼红，想要从中破坏，有些人还在这里喷自己国家的人，我真是想不通，可能是屎吃多的症状。

我只在乎一件事，我出生在中国，生长在中国，无论他好坏，都是我的家，他不好只能我们自己人说，还轮不到你一个外人在这里逼逼，懂吗？如果有一天别人把你们家人的照片故意丑化，然后公布在网上你是什么心情？习近平不仅仅是一个主席，他还是一位丈夫和父亲。这么随意侮辱别人，多行不义必自毙，希望你好自为之！

**Comment by Meteor-fly** [comment]
有那点时间让你们来这里喷自己国家，不如去学学技术，整天抱怨这个抱怨那个，你自己就是个菜逼，你还怪房价高？大城市房价高，你去小城市啊，自己不努力还想过得好，还怪国家，国家欠你的？

**Comment by walkthehorizon** [comment]
我也这么想，就本库来说，完完全全就是一个毫无涵养与道德的衰货处心积虑的抹黑中共罢了，也许国内有很多这样那样的问题，但这些年的进步大家有目共睹，关于作者所绘制的所谓“黑暗关系图”，你有点文化常识好么，这是中国几千年积累形成的风气，改革是需要时间和机遇的，就算是发达国家的总统和高层难道就没有那些黑恶的关系网？就没有干过见不得人的事？一个真正想帮助改善社会生存环境的人是尽自己的一份力去做出改变，去推动改革，去贡献自己的一份力，而不是在这不停地抹黑，制造恐慌和焦虑

**Comment by malinkang** [comment]
真的是搞的github也被墙。

**Comment by bugparty** [comment]
那你好好过，跟别我们凑热闹，道不同不相为谋！

**Comment by loveyanbei** [comment]
赵国这么好，那上什么国外网站，你有通敌嫌疑

**Comment by walkthehorizon** [comment]
滚犊子吧，强词夺理，清朝末期都能意识到师夷长技以制夷，你还在这强调闭关锁国政策，我也不是什么职业的水军，只是看不惯你们这些只知道抹黑自己民族的2货罢了，，，这要是战争时期你肯定汉奸一条a

**Comment by siatechno** [comment]
walkthehorizon, 这个傻逼。进步不进步跟揭露真相有狗逼的矛盾？

**Comment by siatechno** [comment]
Metor-fly, 你这个傻逼，揭露真相跟黑不黑国家有狗逼的矛盾？

**Comment by Meteor-fly** [comment]
我发现你们这些动不动就说自己国家的，真是有意思，这就好像，你妈现在正在被这个项目的作者操，而且还操怀孕了，你在一边鼓掌叫好，还说你妈今天水比较少，你是不是要帮着他把你妈多弄出点水来，让人家操的舒服点？

**Comment by Meteor-fly** [comment]
什么思想，自己国家好不好，自己没长眼吗，封锁网络是做得不对，但是不还给你留一条VPN的路让你出来骂自己国家吗？如果不封锁网络更多喷子都出来，那才真的正中像作者这样别有用心人的下怀，我爱不爱共产党我不知道，我只知道我是个中国人，睡觉，你们慢慢在这里喷吧，可见你们在平时生活中也不是个懂得感恩的人，没有共产党，说不定你现在都是日本人的孙子了。

**Comment by chonghua** [comment]
我相信大部分人都是爱国的！请注意，是爱国！而不是爱其它什么

**Comment by KamikazeChan** [comment]
既然你過這麼好，滾回墻內和你的韃靼說去啊，github不適合你這樣的兔雜

**Comment by tonylx86** [comment]
小子，中共就封网这一条足够国民推翻它了，这是原则性的作恶，说明我国的政治秩序仍旧是建立在古代模式下的，这种强大的另一面就是反人类，第三帝国也很强大不是吗，然后呢？相比IS，中共才是是全世界最恐怖的敌人，切勿助纣为虐啊。

**Comment by bugparty** [comment]
说土共好的，别翻墙，翻墙前你经过土共批准了吗，你撸管前抄党章了吗，土共腊肉跟当时的日本关系可好了，经常出卖抗战的国民军情报，没有土共中国解放的更快，你除了背教科书还能干啥，土共说你妈是妓女你也信啊？我们爱国，所以要争取真想，土共算什么，能代表全国吗？你问全国人民同意吗？

2016-07-02 11:50 GMT+08:00 tonylx86 <notifications@github.com>:

**Comment by Meteor-fly** [comment]
bugparty 这种事情也就在自己国家说一说，家丑还不能外扬呢，你们这种傻逼非要把这些弄到国际平台，要是在战争年代，绝对是个好汉奸，帮助日本人日你妈那种。

**Comment by jazy1982** [comment]
楼主五毛领好！

**Comment by jazy1982** [comment]
@Meteor-fly 汉奸这一称呼其实还是挺光荣的。

顺便说一下，赵国的汉奸可不是谁想当就能当的。

再推测一下，如果在家里你老公把你家暴了，估计你也不会报警吧，家丑不能外扬嘛！

**Comment by Meteor-fly** [comment]
.
