### ISSUE TITLE
会被墙的

### ISSUE THREAD

**Issue by SiriusGuo** [programthink/zhao#8]
建议迁移到自己的网站上去。

**Comment by posclegom** [comment]
只要不是违反GitHub的ToS的内容都可以放在GitHub上，楼主不要做精赵，不要自我阉割，不要做奴才。

**Comment by posclegom** [comment]
你也配姓赵？

**Comment by antipoliongithub** [comment]
@posclegom ，你大概自己觉得是“我自横刀向天笑”，其实比起“引刀成一快”都远远不如，就别再四处跳梁了
