### ISSUE TITLE
请不要道貌岸然的污染github，谢谢

### ISSUE THREAD

**Issue by lihongxun945** [programthink/zhao#85]
**有一群人，他们在任何地方，任何时候都要去讲政治，如果别人制止他们，说这里不是讲政治的地方，他们就会以道貌岸然的批评别人。**

我不反对你们去揭露某些不为人知的秘密，但是，**github是一个程序员用的技术类的网站，是用来交流技术而不是讨论政治的**，你们现在冲上来，在一个技术网站上发一些政治敏感的东西，不觉得不合适吗？竟然还有脸写“不谴责强盗反而谴责卖家”？

你们这种方式，除了扰乱这个良好的技术社区，还有什么意义吗？如果你真的想做，请你自己去建一个网站，请你自己去组织游行，而不是在github上创建这样一个项目。

**对于这种人，请理智的人敢于大声说“滚出去”**

谢谢！

**Comment by KamikazeChan** [comment]
這個項目在這裡你可以選擇不看,又不是你家TG拿刀逼你的,連翻墻都不會還當什麼程序員,趕緊滾回家養豬吧

**Comment by lihongxun945** [comment]
@KamikazeChan 呵呵，露出本性了吧，讲一下道理就开始人身攻击。墙都不会翻是怎么回复你的？

照你这么说，别人冲进你家里拉屎 是不是你选择不看就行了？

**Comment by KamikazeChan** [comment]
五毛滾出github吧，這裡不適合你

**Comment by lihongxun945** [comment]
@KamikazeChan  笑死了，不讲道理，人身攻击，扣帽子。可悲~

**Comment by KamikazeChan** [comment]
有什麼事回牆內和你的韃靼說去，github不是由你們說了算ok

**Comment by lihongxun945** [comment]
几句话基本可以看清一个人的嘴脸：）

**Comment by KamikazeChan** [comment]
你有本事你把這個項目黑了啊，不然在這裡bb算個j8

**Comment by lihongxun945** [comment]
请继续秀出你的智商和人品下限 ：）

**Comment by yiguihai** [comment]
滾！✌[手動滑稽]

**Comment by 73883999** [comment]
所以我大声地说：楼主滚出去
