### ISSUE TITLE
没有共产党 才有新中国

### ISSUE THREAD

**Issue by zdu-strong** [programthink/zhao#934]
没有共产党才有新中国
没有共产党才有新中国
共产党腐败为自己
共产党它一心卖中国
它指给了人民死亡的道路
它领导中国走向黑暗
它杀害了国人八千万
它败坏了人民道德
它建设了流氓土匪窝
它实行了独裁坏处多
没有共产党才有新中国
没有共产党才有新中国

**Comment by AunlitDrean** [comment]
你好，能交流一下吗

**Comment by sunpx3** [comment]
你这不也是走了极端吗， 需要共产党，但不能仅仅有共产党，需要多党，需要制衡的力量，不能让那些官僚想干啥就干啥。

**Comment by zdu-strong** [comment]
> 你这不也是走了极端吗， 需要共产党，但不能仅仅有共产党，需要多党，需要制衡的力量，不能让那些官僚想干啥就干啥。

那是你的事, 与我无关.
